/*
 *	autogen/server/zone/objects/tangible/tool/ShipPaintKit.cpp generated by engine3 IDL compiler 0.70
 */

#include "ShipPaintKit.h"

/*
 *	ShipPaintKitStub
 */

enum {RPC_GETPRIMARYUSED__ = 3649515406,RPC_SETPRIMARYUSED__BOOL_,RPC_GETSECONDARYUSED__,RPC_SETSECONDARYUSED__BOOL_};

ShipPaintKit::ShipPaintKit() : TangibleObject(DummyConstructorParameter::instance()) {
	ShipPaintKitImplementation* _implementation = new ShipPaintKitImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("ShipPaintKit");
}

ShipPaintKit::ShipPaintKit(DummyConstructorParameter* param) : TangibleObject(param) {
	_setClassName("ShipPaintKit");
}

ShipPaintKit::~ShipPaintKit() {
}



bool ShipPaintKit::getPrimaryUsed() const {
	ShipPaintKitImplementation* _implementation = static_cast<ShipPaintKitImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETPRIMARYUSED__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->getPrimaryUsed();
	}
}

void ShipPaintKit::setPrimaryUsed(bool value) {
	ShipPaintKitImplementation* _implementation = static_cast<ShipPaintKitImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETPRIMARYUSED__BOOL_);
		method.addBooleanParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setPrimaryUsed(value);
	}
}

bool ShipPaintKit::getSecondaryUsed() const {
	ShipPaintKitImplementation* _implementation = static_cast<ShipPaintKitImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSECONDARYUSED__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->getSecondaryUsed();
	}
}

void ShipPaintKit::setSecondaryUsed(bool value) {
	ShipPaintKitImplementation* _implementation = static_cast<ShipPaintKitImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSECONDARYUSED__BOOL_);
		method.addBooleanParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setSecondaryUsed(value);
	}
}

DistributedObjectServant* ShipPaintKit::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ShipPaintKit::_getImplementationForRead() const {
	return _impl;
}

void ShipPaintKit::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ShipPaintKitImplementation
 */

ShipPaintKitImplementation::ShipPaintKitImplementation(DummyConstructorParameter* param) : TangibleObjectImplementation(param) {
	_initializeImplementation();
}


ShipPaintKitImplementation::~ShipPaintKitImplementation() {
}


void ShipPaintKitImplementation::finalize() {
}

void ShipPaintKitImplementation::_initializeImplementation() {
	_setClassHelper(ShipPaintKitHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ShipPaintKitImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ShipPaintKit*>(stub);
	TangibleObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ShipPaintKitImplementation::_getStub() {
	return _this.get();
}

ShipPaintKitImplementation::operator const ShipPaintKit*() {
	return _this.get();
}

void ShipPaintKitImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ShipPaintKitImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ShipPaintKitImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ShipPaintKitImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ShipPaintKitImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ShipPaintKitImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ShipPaintKitImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ShipPaintKitImplementation::_serializationHelperMethod() {
	TangibleObjectImplementation::_serializationHelperMethod();

	_setClassName("ShipPaintKit");

}

void ShipPaintKitImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipPaintKitImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ShipPaintKitImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x9e2b6880: //ShipPaintKit.primaryUsed
		TypeInfo<bool >::parseFromBinaryStream(&primaryUsed, stream);
		return true;

	case 0xa702191c: //ShipPaintKit.secondaryUsed
		TypeInfo<bool >::parseFromBinaryStream(&secondaryUsed, stream);
		return true;

	}

	return false;
}

void ShipPaintKitImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipPaintKitImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipPaintKitImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x9e2b6880; //ShipPaintKit.primaryUsed
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&primaryUsed, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xa702191c; //ShipPaintKit.secondaryUsed
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&secondaryUsed, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void ShipPaintKitImplementation::writeJSON(nlohmann::json& j) {
	TangibleObjectImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["primaryUsed"] = primaryUsed;

	thisObject["secondaryUsed"] = secondaryUsed;

	j["ShipPaintKit"] = thisObject;
}

ShipPaintKitImplementation::ShipPaintKitImplementation() : TangibleObjectImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/tool/ShipPaintKit.idl():  		primaryUsed = false;
	primaryUsed = false;
	// server/zone/objects/tangible/tool/ShipPaintKit.idl():  		secondaryUsed = false;
	secondaryUsed = false;
}

bool ShipPaintKitImplementation::getPrimaryUsed() const{
	// server/zone/objects/tangible/tool/ShipPaintKit.idl():  		return primaryUsed;
	return primaryUsed;
}

void ShipPaintKitImplementation::setPrimaryUsed(bool value) {
	// server/zone/objects/tangible/tool/ShipPaintKit.idl():  		primaryUsed = value;
	primaryUsed = value;
}

bool ShipPaintKitImplementation::getSecondaryUsed() const{
	// server/zone/objects/tangible/tool/ShipPaintKit.idl():  		return secondaryUsed;
	return secondaryUsed;
}

void ShipPaintKitImplementation::setSecondaryUsed(bool value) {
	// server/zone/objects/tangible/tool/ShipPaintKit.idl():  		secondaryUsed = value;
	secondaryUsed = value;
}

/*
 *	ShipPaintKitAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ShipPaintKitAdapter::ShipPaintKitAdapter(ShipPaintKit* obj) : TangibleObjectAdapter(obj) {
}

void ShipPaintKitAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_GETPRIMARYUSED__:
		{
			
			bool _m_res = getPrimaryUsed();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_SETPRIMARYUSED__BOOL_:
		{
			bool value = inv->getBooleanParameter();
			
			setPrimaryUsed(value);
			
		}
		break;
	case RPC_GETSECONDARYUSED__:
		{
			
			bool _m_res = getSecondaryUsed();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_SETSECONDARYUSED__BOOL_:
		{
			bool value = inv->getBooleanParameter();
			
			setSecondaryUsed(value);
			
		}
		break;
	default:
		TangibleObjectAdapter::invokeMethod(methid, inv);
	}
}

bool ShipPaintKitAdapter::getPrimaryUsed() const {
	return (static_cast<ShipPaintKit*>(stub))->getPrimaryUsed();
}

void ShipPaintKitAdapter::setPrimaryUsed(bool value) {
	(static_cast<ShipPaintKit*>(stub))->setPrimaryUsed(value);
}

bool ShipPaintKitAdapter::getSecondaryUsed() const {
	return (static_cast<ShipPaintKit*>(stub))->getSecondaryUsed();
}

void ShipPaintKitAdapter::setSecondaryUsed(bool value) {
	(static_cast<ShipPaintKit*>(stub))->setSecondaryUsed(value);
}

/*
 *	ShipPaintKitHelper
 */

ShipPaintKitHelper* ShipPaintKitHelper::staticInitializer = ShipPaintKitHelper::instance();

ShipPaintKitHelper::ShipPaintKitHelper() {
	className = "ShipPaintKit";

	Core::getObjectBroker()->registerClass(className, this);
}

void ShipPaintKitHelper::finalizeHelper() {
	ShipPaintKitHelper::finalize();
}

DistributedObject* ShipPaintKitHelper::instantiateObject() {
	return new ShipPaintKit(DummyConstructorParameter::instance());
}

DistributedObjectServant* ShipPaintKitHelper::instantiateServant() {
	return new ShipPaintKitImplementation();
}

DistributedObjectPOD* ShipPaintKitHelper::instantiatePOD() {
	return new ShipPaintKitPOD();
}

DistributedObjectAdapter* ShipPaintKitHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ShipPaintKitAdapter(static_cast<ShipPaintKit*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ShipPaintKitPOD
 */

ShipPaintKitPOD::~ShipPaintKitPOD() {
	finalize();
}

ShipPaintKitPOD::ShipPaintKitPOD(void) {
	_className = "ShipPaintKit";
}


void ShipPaintKitPOD::writeJSON(nlohmann::json& j) {
	TangibleObjectPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (primaryUsed)
		thisObject["primaryUsed"] = primaryUsed.value();

	if (secondaryUsed)
		thisObject["secondaryUsed"] = secondaryUsed.value();

	j["ShipPaintKit"] = thisObject;
}


void ShipPaintKitPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipPaintKitPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipPaintKitPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (primaryUsed) {
	_nameHashCode = 0x9e2b6880; //ShipPaintKit.primaryUsed
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&primaryUsed.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (secondaryUsed) {
	_nameHashCode = 0xa702191c; //ShipPaintKit.secondaryUsed
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&secondaryUsed.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ShipPaintKitPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x9e2b6880: //ShipPaintKit.primaryUsed
		{
			bool _mnprimaryUsed;
			TypeInfo<bool >::parseFromBinaryStream(&_mnprimaryUsed, stream);
			primaryUsed = std::move(_mnprimaryUsed);
		}
		return true;

	case 0xa702191c: //ShipPaintKit.secondaryUsed
		{
			bool _mnsecondaryUsed;
			TypeInfo<bool >::parseFromBinaryStream(&_mnsecondaryUsed, stream);
			secondaryUsed = std::move(_mnsecondaryUsed);
		}
		return true;

	}

	return false;
}

void ShipPaintKitPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipPaintKitPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ShipPaintKitPOD::writeObjectCompact(ObjectOutputStream* stream) {
	TangibleObjectPOD::writeObjectCompact(stream);

	TypeInfo<bool >::toBinaryStream(&primaryUsed.value(), stream);

	TypeInfo<bool >::toBinaryStream(&secondaryUsed.value(), stream);


}

