/*
 *	autogen/server/zone/objects/ship/components/ShipCounterMeasureComponent.cpp generated by engine3 IDL compiler 0.70
 */

#include "ShipCounterMeasureComponent.h"

/*
 *	ShipCounterMeasureComponentStub
 */

enum {RPC_GETEFFECTIVENESSMIN__ = 3337695987,RPC_GETEFFECTIVENESSMAX__,RPC_GETREFIRERATE__,RPC_GETENERGYPERSHOT__,};

ShipCounterMeasureComponent::ShipCounterMeasureComponent() : Component(DummyConstructorParameter::instance()) {
	ShipCounterMeasureComponentImplementation* _implementation = new ShipCounterMeasureComponentImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("ShipCounterMeasureComponent");
}

ShipCounterMeasureComponent::ShipCounterMeasureComponent(DummyConstructorParameter* param) : Component(param) {
	_setClassName("ShipCounterMeasureComponent");
}

ShipCounterMeasureComponent::~ShipCounterMeasureComponent() {
}



float ShipCounterMeasureComponent::getEffectivenessMin() {
	ShipCounterMeasureComponentImplementation* _implementation = static_cast<ShipCounterMeasureComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETEFFECTIVENESSMIN__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getEffectivenessMin();
	}
}

float ShipCounterMeasureComponent::getEffectivenessMax() {
	ShipCounterMeasureComponentImplementation* _implementation = static_cast<ShipCounterMeasureComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETEFFECTIVENESSMAX__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getEffectivenessMax();
	}
}

float ShipCounterMeasureComponent::getRefireRate() {
	ShipCounterMeasureComponentImplementation* _implementation = static_cast<ShipCounterMeasureComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETREFIRERATE__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getRefireRate();
	}
}

float ShipCounterMeasureComponent::getEnergyPerShot() {
	ShipCounterMeasureComponentImplementation* _implementation = static_cast<ShipCounterMeasureComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETENERGYPERSHOT__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getEnergyPerShot();
	}
}

void ShipCounterMeasureComponent::loadTemplateData(SharedObjectTemplate* templateData) {
	ShipCounterMeasureComponentImplementation* _implementation = static_cast<ShipCounterMeasureComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->loadTemplateData(templateData);
	}
}

void ShipCounterMeasureComponent::updateCraftingValues(CraftingValues* values, bool firstUpdate) {
	ShipCounterMeasureComponentImplementation* _implementation = static_cast<ShipCounterMeasureComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->updateCraftingValues(values, firstUpdate);
	}
}

void ShipCounterMeasureComponent::fillAttributeList(AttributeListMessage* msg, CreatureObject* object) {
	ShipCounterMeasureComponentImplementation* _implementation = static_cast<ShipCounterMeasureComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(msg, object);
	}
}

DistributedObjectServant* ShipCounterMeasureComponent::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ShipCounterMeasureComponent::_getImplementationForRead() const {
	return _impl;
}

void ShipCounterMeasureComponent::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ShipCounterMeasureComponentImplementation
 */

ShipCounterMeasureComponentImplementation::ShipCounterMeasureComponentImplementation(DummyConstructorParameter* param) : ComponentImplementation(param) {
	_initializeImplementation();
}


ShipCounterMeasureComponentImplementation::~ShipCounterMeasureComponentImplementation() {
}


void ShipCounterMeasureComponentImplementation::finalize() {
}

void ShipCounterMeasureComponentImplementation::_initializeImplementation() {
	_setClassHelper(ShipCounterMeasureComponentHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ShipCounterMeasureComponentImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ShipCounterMeasureComponent*>(stub);
	ComponentImplementation::_setStub(stub);
}

DistributedObjectStub* ShipCounterMeasureComponentImplementation::_getStub() {
	return _this.get();
}

ShipCounterMeasureComponentImplementation::operator const ShipCounterMeasureComponent*() {
	return _this.get();
}

void ShipCounterMeasureComponentImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ShipCounterMeasureComponentImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ShipCounterMeasureComponentImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ShipCounterMeasureComponentImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ShipCounterMeasureComponentImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ShipCounterMeasureComponentImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ShipCounterMeasureComponentImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ShipCounterMeasureComponentImplementation::_serializationHelperMethod() {
	ComponentImplementation::_serializationHelperMethod();

	_setClassName("ShipCounterMeasureComponent");

}

void ShipCounterMeasureComponentImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipCounterMeasureComponentImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ShipCounterMeasureComponentImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ComponentImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x8ba65df0: //ShipCounterMeasureComponent.effectivenessMin
		TypeInfo<float >::parseFromBinaryStream(&effectivenessMin, stream);
		return true;

	case 0x57798860: //ShipCounterMeasureComponent.effectivenessMax
		TypeInfo<float >::parseFromBinaryStream(&effectivenessMax, stream);
		return true;

	case 0xfa06c540: //ShipCounterMeasureComponent.refireRate
		TypeInfo<float >::parseFromBinaryStream(&refireRate, stream);
		return true;

	case 0x7b0606cb: //ShipCounterMeasureComponent.energyPerShot
		TypeInfo<float >::parseFromBinaryStream(&energyPerShot, stream);
		return true;

	}

	return false;
}

void ShipCounterMeasureComponentImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipCounterMeasureComponentImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipCounterMeasureComponentImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ComponentImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x8ba65df0; //ShipCounterMeasureComponent.effectivenessMin
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&effectivenessMin, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x57798860; //ShipCounterMeasureComponent.effectivenessMax
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&effectivenessMax, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xfa06c540; //ShipCounterMeasureComponent.refireRate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&refireRate, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x7b0606cb; //ShipCounterMeasureComponent.energyPerShot
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&energyPerShot, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

ShipCounterMeasureComponentImplementation::ShipCounterMeasureComponentImplementation() : ComponentImplementation() {
	_initializeImplementation();
	// server/zone/objects/ship/components/ShipCounterMeasureComponent.idl():  		effectivenessMin = 0.f;
	effectivenessMin = 0.f;
	// server/zone/objects/ship/components/ShipCounterMeasureComponent.idl():  		effectivenessMax = 0.f;
	effectivenessMax = 0.f;
	// server/zone/objects/ship/components/ShipCounterMeasureComponent.idl():  		refireRate = 0.f;
	refireRate = 0.f;
	// server/zone/objects/ship/components/ShipCounterMeasureComponent.idl():  		energyPerShot = 0.f;
	energyPerShot = 0.f;
}

float ShipCounterMeasureComponentImplementation::getEffectivenessMin() {
	// server/zone/objects/ship/components/ShipCounterMeasureComponent.idl():  		return effectivenessMin;
	return effectivenessMin;
}

float ShipCounterMeasureComponentImplementation::getEffectivenessMax() {
	// server/zone/objects/ship/components/ShipCounterMeasureComponent.idl():  		return effectivenessMax;
	return effectivenessMax;
}

float ShipCounterMeasureComponentImplementation::getRefireRate() {
	// server/zone/objects/ship/components/ShipCounterMeasureComponent.idl():  		return refireRate;
	return refireRate;
}

float ShipCounterMeasureComponentImplementation::getEnergyPerShot() {
	// server/zone/objects/ship/components/ShipCounterMeasureComponent.idl():  		return energyPerShot;
	return energyPerShot;
}

/*
 *	ShipCounterMeasureComponentAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ShipCounterMeasureComponentAdapter::ShipCounterMeasureComponentAdapter(ShipCounterMeasureComponent* obj) : ComponentAdapter(obj) {
}

void ShipCounterMeasureComponentAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_GETEFFECTIVENESSMIN__:
		{
			
			float _m_res = getEffectivenessMin();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETEFFECTIVENESSMAX__:
		{
			
			float _m_res = getEffectivenessMax();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETREFIRERATE__:
		{
			
			float _m_res = getRefireRate();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETENERGYPERSHOT__:
		{
			
			float _m_res = getEnergyPerShot();
			resp->insertFloat(_m_res);
		}
		break;
	default:
		ComponentAdapter::invokeMethod(methid, inv);
	}
}

float ShipCounterMeasureComponentAdapter::getEffectivenessMin() {
	return (static_cast<ShipCounterMeasureComponent*>(stub))->getEffectivenessMin();
}

float ShipCounterMeasureComponentAdapter::getEffectivenessMax() {
	return (static_cast<ShipCounterMeasureComponent*>(stub))->getEffectivenessMax();
}

float ShipCounterMeasureComponentAdapter::getRefireRate() {
	return (static_cast<ShipCounterMeasureComponent*>(stub))->getRefireRate();
}

float ShipCounterMeasureComponentAdapter::getEnergyPerShot() {
	return (static_cast<ShipCounterMeasureComponent*>(stub))->getEnergyPerShot();
}

/*
 *	ShipCounterMeasureComponentHelper
 */

ShipCounterMeasureComponentHelper* ShipCounterMeasureComponentHelper::staticInitializer = ShipCounterMeasureComponentHelper::instance();

ShipCounterMeasureComponentHelper::ShipCounterMeasureComponentHelper() {
	className = "ShipCounterMeasureComponent";

	Core::getObjectBroker()->registerClass(className, this);
}

void ShipCounterMeasureComponentHelper::finalizeHelper() {
	ShipCounterMeasureComponentHelper::finalize();
}

DistributedObject* ShipCounterMeasureComponentHelper::instantiateObject() {
	return new ShipCounterMeasureComponent(DummyConstructorParameter::instance());
}

DistributedObjectServant* ShipCounterMeasureComponentHelper::instantiateServant() {
	return new ShipCounterMeasureComponentImplementation();
}

DistributedObjectPOD* ShipCounterMeasureComponentHelper::instantiatePOD() {
	return new ShipCounterMeasureComponentPOD();
}

DistributedObjectAdapter* ShipCounterMeasureComponentHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ShipCounterMeasureComponentAdapter(static_cast<ShipCounterMeasureComponent*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ShipCounterMeasureComponentPOD
 */

ShipCounterMeasureComponentPOD::~ShipCounterMeasureComponentPOD() {
	finalize();
}

ShipCounterMeasureComponentPOD::ShipCounterMeasureComponentPOD(void) {
	_className = "ShipCounterMeasureComponent";
}


void ShipCounterMeasureComponentPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipCounterMeasureComponentPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipCounterMeasureComponentPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ComponentPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (effectivenessMin) {
	_nameHashCode = 0x8ba65df0; //ShipCounterMeasureComponent.effectivenessMin
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&effectivenessMin.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (effectivenessMax) {
	_nameHashCode = 0x57798860; //ShipCounterMeasureComponent.effectivenessMax
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&effectivenessMax.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (refireRate) {
	_nameHashCode = 0xfa06c540; //ShipCounterMeasureComponent.refireRate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&refireRate.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (energyPerShot) {
	_nameHashCode = 0x7b0606cb; //ShipCounterMeasureComponent.energyPerShot
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&energyPerShot.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ShipCounterMeasureComponentPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ComponentPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x8ba65df0: //ShipCounterMeasureComponent.effectivenessMin
		{
			float _mneffectivenessMin;
			TypeInfo<float >::parseFromBinaryStream(&_mneffectivenessMin, stream);
			effectivenessMin = std::move(_mneffectivenessMin);
		}
		return true;

	case 0x57798860: //ShipCounterMeasureComponent.effectivenessMax
		{
			float _mneffectivenessMax;
			TypeInfo<float >::parseFromBinaryStream(&_mneffectivenessMax, stream);
			effectivenessMax = std::move(_mneffectivenessMax);
		}
		return true;

	case 0xfa06c540: //ShipCounterMeasureComponent.refireRate
		{
			float _mnrefireRate;
			TypeInfo<float >::parseFromBinaryStream(&_mnrefireRate, stream);
			refireRate = std::move(_mnrefireRate);
		}
		return true;

	case 0x7b0606cb: //ShipCounterMeasureComponent.energyPerShot
		{
			float _mnenergyPerShot;
			TypeInfo<float >::parseFromBinaryStream(&_mnenergyPerShot, stream);
			energyPerShot = std::move(_mnenergyPerShot);
		}
		return true;

	}

	return false;
}

void ShipCounterMeasureComponentPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipCounterMeasureComponentPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ShipCounterMeasureComponentPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ComponentPOD::writeObjectCompact(stream);

	TypeInfo<float >::toBinaryStream(&effectivenessMin.value(), stream);

	TypeInfo<float >::toBinaryStream(&effectivenessMax.value(), stream);

	TypeInfo<float >::toBinaryStream(&refireRate.value(), stream);

	TypeInfo<float >::toBinaryStream(&energyPerShot.value(), stream);


}

