/*
 *	autogen/server/zone/objects/ship/components/ShipMissileComponent.h generated by engine3 IDL compiler 0.70
 */

#ifndef SHIPMISSILECOMPONENT_H_
#define SHIPMISSILECOMPONENT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "templates/SharedObjectTemplate.h"

#include "server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "server/zone/objects/tangible/component/Component.h"

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipMissileComponent : public Component {
public:
	ShipMissileComponent();

	float getMaxDamage();

	float getMinDamage();

	float getArmorEffectiveness();

	float getShieldEffectiveness();

	float getRefireRate();

	void loadTemplateData(SharedObjectTemplate* templateData);

	void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ShipMissileComponent(DummyConstructorParameter* param);

	virtual ~ShipMissileComponent();

	friend class ShipMissileComponentHelper;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipMissileComponentImplementation : public ComponentImplementation {
protected:
	float maxDamage;

	float minDamage;

	float armorEffectiveness;

	float shieldEffectiveness;

	float refireRate;

public:
	ShipMissileComponentImplementation();

	ShipMissileComponentImplementation(DummyConstructorParameter* param);

	float getMaxDamage();

	float getMinDamage();

	float getArmorEffectiveness();

	float getShieldEffectiveness();

	float getRefireRate();

	void loadTemplateData(SharedObjectTemplate* templateData);

	virtual void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	WeakReference<ShipMissileComponent*> _this;

	operator const ShipMissileComponent*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ShipMissileComponentImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ShipMissileComponent;
};

class ShipMissileComponentAdapter : public ComponentAdapter {
public:
	ShipMissileComponentAdapter(ShipMissileComponent* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	float getMaxDamage();

	float getMinDamage();

	float getArmorEffectiveness();

	float getShieldEffectiveness();

	float getRefireRate();

};

class ShipMissileComponentHelper : public DistributedObjectClassHelper, public Singleton<ShipMissileComponentHelper> {
	static ShipMissileComponentHelper* staticInitializer;

public:
	ShipMissileComponentHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ShipMissileComponentHelper>;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipMissileComponentPOD : public ComponentPOD {
public:
	Optional<float> maxDamage;

	Optional<float> minDamage;

	Optional<float> armorEffectiveness;

	Optional<float> shieldEffectiveness;

	Optional<float> refireRate;

	String _className;
	ShipMissileComponentPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ShipMissileComponentPOD();

};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

#endif /*SHIPMISSILECOMPONENTPOD_H_*/
