/*
 *	autogen/server/zone/objects/ship/components/ShipReactorComponent.cpp generated by engine3 IDL compiler 0.70
 */

#include "ShipReactorComponent.h"

#include "server/zone/objects/ship/ShipObject.h"

#include "server/zone/objects/creature/CreatureObject.h"

/*
 *	ShipReactorComponentStub
 */

enum {RPC_GETREACTORGENERATIONRATE__ = 3017350929,RPC_SETREACTORGENERATIONRATE__FLOAT_,};

ShipReactorComponent::ShipReactorComponent() : ShipComponent(DummyConstructorParameter::instance()) {
	ShipReactorComponentImplementation* _implementation = new ShipReactorComponentImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("ShipReactorComponent");
}

ShipReactorComponent::ShipReactorComponent(DummyConstructorParameter* param) : ShipComponent(param) {
	_setClassName("ShipReactorComponent");
}

ShipReactorComponent::~ShipReactorComponent() {
}



float ShipReactorComponent::getReactorGenerationRate() {
	ShipReactorComponentImplementation* _implementation = static_cast<ShipReactorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETREACTORGENERATIONRATE__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getReactorGenerationRate();
	}
}

void ShipReactorComponent::setReactorGenerationRate(float value) {
	ShipReactorComponentImplementation* _implementation = static_cast<ShipReactorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETREACTORGENERATIONRATE__FLOAT_);
		method.addFloatParameter(value);

		method.executeWithVoidReturn();
	} else {
		_implementation->setReactorGenerationRate(value);
	}
}

void ShipReactorComponent::loadTemplateData(SharedObjectTemplate* templateData) {
	ShipReactorComponentImplementation* _implementation = static_cast<ShipReactorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->loadTemplateData(templateData);
	}
}

void ShipReactorComponent::updateCraftingValues(CraftingValues* values, bool firstUpdate) {
	ShipReactorComponentImplementation* _implementation = static_cast<ShipReactorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->updateCraftingValues(values, firstUpdate);
	}
}

void ShipReactorComponent::fillAttributeList(AttributeListMessage* msg, CreatureObject* object) {
	ShipReactorComponentImplementation* _implementation = static_cast<ShipReactorComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(msg, object);
	}
}

void ShipReactorComponent::install(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient) {
	ShipReactorComponentImplementation* _implementation = static_cast<ShipReactorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->install(owner, component, slot, notifyClient);
	}
}

void ShipReactorComponent::uninstall(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient) {
	ShipReactorComponentImplementation* _implementation = static_cast<ShipReactorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->uninstall(owner, component, slot, notifyClient);
	}
}

DistributedObjectServant* ShipReactorComponent::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ShipReactorComponent::_getImplementationForRead() const {
	return _impl;
}

void ShipReactorComponent::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ShipReactorComponentImplementation
 */

ShipReactorComponentImplementation::ShipReactorComponentImplementation(DummyConstructorParameter* param) : ShipComponentImplementation(param) {
	_initializeImplementation();
}


ShipReactorComponentImplementation::~ShipReactorComponentImplementation() {
}


void ShipReactorComponentImplementation::finalize() {
}

void ShipReactorComponentImplementation::_initializeImplementation() {
	_setClassHelper(ShipReactorComponentHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ShipReactorComponentImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ShipReactorComponent*>(stub);
	ShipComponentImplementation::_setStub(stub);
}

DistributedObjectStub* ShipReactorComponentImplementation::_getStub() {
	return _this.get();
}

ShipReactorComponentImplementation::operator const ShipReactorComponent*() {
	return _this.get();
}

void ShipReactorComponentImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ShipReactorComponentImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ShipReactorComponentImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ShipReactorComponentImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ShipReactorComponentImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ShipReactorComponentImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ShipReactorComponentImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ShipReactorComponentImplementation::_serializationHelperMethod() {
	ShipComponentImplementation::_serializationHelperMethod();

	_setClassName("ShipReactorComponent");

}

void ShipReactorComponentImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipReactorComponentImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ShipReactorComponentImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ShipComponentImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x7c735b1a: //ShipReactorComponent.reactorGenerationRate
		TypeInfo<float >::parseFromBinaryStream(&reactorGenerationRate, stream);
		return true;

	}

	return false;
}

void ShipReactorComponentImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipReactorComponentImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipReactorComponentImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ShipComponentImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x7c735b1a; //ShipReactorComponent.reactorGenerationRate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&reactorGenerationRate, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

ShipReactorComponentImplementation::ShipReactorComponentImplementation() : ShipComponentImplementation() {
	_initializeImplementation();
	// server/zone/objects/ship/components/ShipReactorComponent.idl():  		reactorGenerationRate = 0.f;
	reactorGenerationRate = 0.f;
}

float ShipReactorComponentImplementation::getReactorGenerationRate() {
	// server/zone/objects/ship/components/ShipReactorComponent.idl():  		return reactorGenerationRate;
	return reactorGenerationRate;
}

void ShipReactorComponentImplementation::setReactorGenerationRate(float value) {
	// server/zone/objects/ship/components/ShipReactorComponent.idl():  		reactorGenerationRate = value;
	reactorGenerationRate = value;
}

/*
 *	ShipReactorComponentAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ShipReactorComponentAdapter::ShipReactorComponentAdapter(ShipReactorComponent* obj) : ShipComponentAdapter(obj) {
}

void ShipReactorComponentAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_GETREACTORGENERATIONRATE__:
		{
			
			float _m_res = getReactorGenerationRate();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETREACTORGENERATIONRATE__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			setReactorGenerationRate(value);
			
		}
		break;
	default:
		ShipComponentAdapter::invokeMethod(methid, inv);
	}
}

float ShipReactorComponentAdapter::getReactorGenerationRate() {
	return (static_cast<ShipReactorComponent*>(stub))->getReactorGenerationRate();
}

void ShipReactorComponentAdapter::setReactorGenerationRate(float value) {
	(static_cast<ShipReactorComponent*>(stub))->setReactorGenerationRate(value);
}

/*
 *	ShipReactorComponentHelper
 */

ShipReactorComponentHelper* ShipReactorComponentHelper::staticInitializer = ShipReactorComponentHelper::instance();

ShipReactorComponentHelper::ShipReactorComponentHelper() {
	className = "ShipReactorComponent";

	Core::getObjectBroker()->registerClass(className, this);
}

void ShipReactorComponentHelper::finalizeHelper() {
	ShipReactorComponentHelper::finalize();
}

DistributedObject* ShipReactorComponentHelper::instantiateObject() {
	return new ShipReactorComponent(DummyConstructorParameter::instance());
}

DistributedObjectServant* ShipReactorComponentHelper::instantiateServant() {
	return new ShipReactorComponentImplementation();
}

DistributedObjectPOD* ShipReactorComponentHelper::instantiatePOD() {
	return new ShipReactorComponentPOD();
}

DistributedObjectAdapter* ShipReactorComponentHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ShipReactorComponentAdapter(static_cast<ShipReactorComponent*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ShipReactorComponentPOD
 */

ShipReactorComponentPOD::~ShipReactorComponentPOD() {
	finalize();
}

ShipReactorComponentPOD::ShipReactorComponentPOD(void) {
	_className = "ShipReactorComponent";
}


void ShipReactorComponentPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipReactorComponentPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipReactorComponentPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ShipComponentPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (reactorGenerationRate) {
	_nameHashCode = 0x7c735b1a; //ShipReactorComponent.reactorGenerationRate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&reactorGenerationRate.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ShipReactorComponentPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ShipComponentPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x7c735b1a: //ShipReactorComponent.reactorGenerationRate
		{
			float _mnreactorGenerationRate;
			TypeInfo<float >::parseFromBinaryStream(&_mnreactorGenerationRate, stream);
			reactorGenerationRate = std::move(_mnreactorGenerationRate);
		}
		return true;

	}

	return false;
}

void ShipReactorComponentPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipReactorComponentPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ShipReactorComponentPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ShipComponentPOD::writeObjectCompact(stream);

	TypeInfo<float >::toBinaryStream(&reactorGenerationRate.value(), stream);


}

