/*
 *	autogen/server/zone/objects/ship/components/ShipReactorComponent.h generated by engine3 IDL compiler 0.70
 */

#ifndef SHIPREACTORCOMPONENT_H_
#define SHIPREACTORCOMPONENT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace ship {

class ShipObject;

class ShipObjectPOD;

} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship;

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

#include "server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "templates/SharedObjectTemplate.h"

#include "server/zone/objects/ship/components/ShipComponent.h"

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipReactorComponent : public ShipComponent {
public:
	ShipReactorComponent();

	float getReactorGenerationRate();

	void setReactorGenerationRate(float value);

	void loadTemplateData(SharedObjectTemplate* templateData);

	void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	void install(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient);

	void uninstall(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ShipReactorComponent(DummyConstructorParameter* param);

	virtual ~ShipReactorComponent();

	friend class ShipReactorComponentHelper;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipReactorComponentImplementation : public ShipComponentImplementation {
protected:
	float reactorGenerationRate;

public:
	ShipReactorComponentImplementation();

	ShipReactorComponentImplementation(DummyConstructorParameter* param);

	float getReactorGenerationRate();

	void setReactorGenerationRate(float value);

	void loadTemplateData(SharedObjectTemplate* templateData);

	virtual void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	virtual void install(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient);

	virtual void uninstall(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient);

	WeakReference<ShipReactorComponent*> _this;

	operator const ShipReactorComponent*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ShipReactorComponentImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ShipReactorComponent;
};

class ShipReactorComponentAdapter : public ShipComponentAdapter {
public:
	ShipReactorComponentAdapter(ShipReactorComponent* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	float getReactorGenerationRate();

	void setReactorGenerationRate(float value);

};

class ShipReactorComponentHelper : public DistributedObjectClassHelper, public Singleton<ShipReactorComponentHelper> {
	static ShipReactorComponentHelper* staticInitializer;

public:
	ShipReactorComponentHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ShipReactorComponentHelper>;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipReactorComponentPOD : public ShipComponentPOD {
public:
	Optional<float> reactorGenerationRate;

	String _className;
	ShipReactorComponentPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ShipReactorComponentPOD();

};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

#endif /*SHIPREACTORCOMPONENTPOD_H_*/
