/*
 *	autogen/server/zone/objects/ship/components/ShipWeaponComponent.h generated by engine3 IDL compiler 0.70
 */

#ifndef SHIPWEAPONCOMPONENT_H_
#define SHIPWEAPONCOMPONENT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace ship {

class ShipObject;

class ShipObjectPOD;

} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship;

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

#include "server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "templates/SharedObjectTemplate.h"

#include "server/zone/objects/tangible/component/Component.h"

#include "server/zone/objects/ship/components/ShipComponent.h"

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipWeaponComponent : public ShipComponent {
public:
	ShipWeaponComponent();

	float getMaxDamage();

	float getMinDamage();

	float getShieldEffectiveness();

	float getArmorEffectiveness();

	float getRefireRate();

	float getEnergyPerShot();

	int getAmmoClass();

	void setMaxDamage(float value);

	void setMinDamage(float value);

	void setShieldEffectiveness(float value);

	void setArmorEffectiveness(float value);

	void setRefireRate(float value);

	void setEnergyPerShot(float value);

	void setAmmoClass(int value);

	void loadTemplateData(SharedObjectTemplate* templateData);

	void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	void install(CreatureObject* owner, ShipObject* ship, int slot, bool notifyClient);

	void uninstall(CreatureObject* owner, ShipObject* ship, int slot, bool notifyClient);

	void installAmmo(CreatureObject* owner, ShipObject* ship, Component* ammo, int slot, bool notifyClient);

	void uninstallAmmo(CreatureObject* owner, ShipObject* ship, int slot, bool notifyClient);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ShipWeaponComponent(DummyConstructorParameter* param);

	virtual ~ShipWeaponComponent();

	friend class ShipWeaponComponentHelper;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipWeaponComponentImplementation : public ShipComponentImplementation {
protected:
	float maxDamage;

	float minDamage;

	float armorEffectiveness;

	float shieldEffectiveness;

	float refireRate;

	float energyPerShot;

	int ammoClass;

public:
	ShipWeaponComponentImplementation();

	ShipWeaponComponentImplementation(DummyConstructorParameter* param);

	float getMaxDamage();

	float getMinDamage();

	float getShieldEffectiveness();

	float getArmorEffectiveness();

	float getRefireRate();

	float getEnergyPerShot();

	int getAmmoClass();

	void setMaxDamage(float value);

	void setMinDamage(float value);

	void setShieldEffectiveness(float value);

	void setArmorEffectiveness(float value);

	void setRefireRate(float value);

	void setEnergyPerShot(float value);

	void setAmmoClass(int value);

	void loadTemplateData(SharedObjectTemplate* templateData);

	virtual void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	virtual void install(CreatureObject* owner, ShipObject* ship, int slot, bool notifyClient);

	virtual void uninstall(CreatureObject* owner, ShipObject* ship, int slot, bool notifyClient);

	virtual void installAmmo(CreatureObject* owner, ShipObject* ship, Component* ammo, int slot, bool notifyClient);

	virtual void uninstallAmmo(CreatureObject* owner, ShipObject* ship, int slot, bool notifyClient);

	WeakReference<ShipWeaponComponent*> _this;

	operator const ShipWeaponComponent*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ShipWeaponComponentImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ShipWeaponComponent;
};

class ShipWeaponComponentAdapter : public ShipComponentAdapter {
public:
	ShipWeaponComponentAdapter(ShipWeaponComponent* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	float getMaxDamage();

	float getMinDamage();

	float getShieldEffectiveness();

	float getArmorEffectiveness();

	float getRefireRate();

	float getEnergyPerShot();

	int getAmmoClass();

};

class ShipWeaponComponentHelper : public DistributedObjectClassHelper, public Singleton<ShipWeaponComponentHelper> {
	static ShipWeaponComponentHelper* staticInitializer;

public:
	ShipWeaponComponentHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ShipWeaponComponentHelper>;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipWeaponComponentPOD : public ShipComponentPOD {
public:
	Optional<float> maxDamage;

	Optional<float> minDamage;

	Optional<float> armorEffectiveness;

	Optional<float> shieldEffectiveness;

	Optional<float> refireRate;

	Optional<float> energyPerShot;

	Optional<int> ammoClass;

	String _className;
	ShipWeaponComponentPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ShipWeaponComponentPOD();

};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

#endif /*SHIPWEAPONCOMPONENTPOD_H_*/
