/*
 *	autogen/server/zone/objects/ship/components/ShipShieldComponent.h generated by engine3 IDL compiler 0.70
 */

#ifndef SHIPSHIELDCOMPONENT_H_
#define SHIPSHIELDCOMPONENT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace ship {

class ShipObject;

class ShipObjectPOD;

} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship;

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

#include "server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "templates/SharedObjectTemplate.h"

#include "server/zone/objects/ship/components/ShipComponent.h"

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipShieldComponent : public ShipComponent {
public:
	ShipShieldComponent();

	float getRearHitpoints();

	float getFrontHitpoints();

	float getRechargeRate();

	void setRearHitpoints(float value);

	void setFrontHitpoints(float value);

	void setRechargeRate(float value);

	void loadTemplateData(SharedObjectTemplate* templateData);

	void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	void install(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient);

	void uninstall(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ShipShieldComponent(DummyConstructorParameter* param);

	virtual ~ShipShieldComponent();

	friend class ShipShieldComponentHelper;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipShieldComponentImplementation : public ShipComponentImplementation {
protected:
	float rearHitpoints;

	float frontHitpoints;

	float rechargeRate;

public:
	ShipShieldComponentImplementation();

	ShipShieldComponentImplementation(DummyConstructorParameter* param);

	float getRearHitpoints();

	float getFrontHitpoints();

	float getRechargeRate();

	void setRearHitpoints(float value);

	void setFrontHitpoints(float value);

	void setRechargeRate(float value);

	void loadTemplateData(SharedObjectTemplate* templateData);

	virtual void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	virtual void install(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient);

	virtual void uninstall(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient);

	WeakReference<ShipShieldComponent*> _this;

	operator const ShipShieldComponent*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ShipShieldComponentImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ShipShieldComponent;
};

class ShipShieldComponentAdapter : public ShipComponentAdapter {
public:
	ShipShieldComponentAdapter(ShipShieldComponent* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	float getRearHitpoints();

	float getFrontHitpoints();

	float getRechargeRate();

	void setRearHitpoints(float value);

	void setFrontHitpoints(float value);

	void setRechargeRate(float value);

};

class ShipShieldComponentHelper : public DistributedObjectClassHelper, public Singleton<ShipShieldComponentHelper> {
	static ShipShieldComponentHelper* staticInitializer;

public:
	ShipShieldComponentHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ShipShieldComponentHelper>;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipShieldComponentPOD : public ShipComponentPOD {
public:
	Optional<float> rearHitpoints;

	Optional<float> frontHitpoints;

	Optional<float> rechargeRate;

	String _className;
	ShipShieldComponentPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ShipShieldComponentPOD();

};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

#endif /*SHIPSHIELDCOMPONENTPOD_H_*/
