/*
 *	autogen/server/zone/objects/ship/components/ShipBoosterComponent.cpp generated by engine3 IDL compiler 0.70
 */

#include "ShipBoosterComponent.h"

#include "server/zone/objects/ship/ShipObject.h"

#include "server/zone/objects/creature/CreatureObject.h"

/*
 *	ShipBoosterComponentStub
 */

enum {RPC_GETBOOSTERACCELERATION__ = 1035601341,RPC_GETBOOSTERENERGYCONSUMPTIONRATE__,RPC_GETBOOSTERENERGY__,RPC_GETBOOSTERRECHARGERATE__,RPC_GETBOOSTERSPEED__,};

ShipBoosterComponent::ShipBoosterComponent() : ShipComponent(DummyConstructorParameter::instance()) {
	ShipBoosterComponentImplementation* _implementation = new ShipBoosterComponentImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("ShipBoosterComponent");
}

ShipBoosterComponent::ShipBoosterComponent(DummyConstructorParameter* param) : ShipComponent(param) {
	_setClassName("ShipBoosterComponent");
}

ShipBoosterComponent::~ShipBoosterComponent() {
}



float ShipBoosterComponent::getBoosterAcceleration() {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETBOOSTERACCELERATION__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getBoosterAcceleration();
	}
}

float ShipBoosterComponent::getBoosterEnergyConsumptionRate() {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETBOOSTERENERGYCONSUMPTIONRATE__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getBoosterEnergyConsumptionRate();
	}
}

float ShipBoosterComponent::getBoosterEnergy() {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETBOOSTERENERGY__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getBoosterEnergy();
	}
}

float ShipBoosterComponent::getBoosterRechargeRate() {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETBOOSTERRECHARGERATE__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getBoosterRechargeRate();
	}
}

float ShipBoosterComponent::getBoosterSpeed() {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETBOOSTERSPEED__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getBoosterSpeed();
	}
}

void ShipBoosterComponent::setBoosterAcceleration(float accel) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->setBoosterAcceleration(accel);
	}
}

void ShipBoosterComponent::setBoosterEnergyConsumptionRate(float rate) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->setBoosterEnergyConsumptionRate(rate);
	}
}

void ShipBoosterComponent::setBoosterEnergy(float energy) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->setBoosterEnergy(energy);
	}
}

void ShipBoosterComponent::setBoosterRechargeRate(float rate) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->setBoosterRechargeRate(rate);
	}
}

void ShipBoosterComponent::setBoosterSpeed(float speed) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->setBoosterSpeed(speed);
	}
}

void ShipBoosterComponent::loadTemplateData(SharedObjectTemplate* templateData) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->loadTemplateData(templateData);
	}
}

void ShipBoosterComponent::updateCraftingValues(CraftingValues* values, bool firstUpdate) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->updateCraftingValues(values, firstUpdate);
	}
}

void ShipBoosterComponent::fillAttributeList(AttributeListMessage* msg, CreatureObject* object) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(msg, object);
	}
}

void ShipBoosterComponent::install(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->install(owner, component, slot, notifyClient);
	}
}

void ShipBoosterComponent::uninstall(CreatureObject* owner, ShipObject* component, int slot, bool notifyClient) {
	ShipBoosterComponentImplementation* _implementation = static_cast<ShipBoosterComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->uninstall(owner, component, slot, notifyClient);
	}
}

DistributedObjectServant* ShipBoosterComponent::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ShipBoosterComponent::_getImplementationForRead() const {
	return _impl;
}

void ShipBoosterComponent::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ShipBoosterComponentImplementation
 */

ShipBoosterComponentImplementation::ShipBoosterComponentImplementation(DummyConstructorParameter* param) : ShipComponentImplementation(param) {
	_initializeImplementation();
}


ShipBoosterComponentImplementation::~ShipBoosterComponentImplementation() {
}


void ShipBoosterComponentImplementation::finalize() {
}

void ShipBoosterComponentImplementation::_initializeImplementation() {
	_setClassHelper(ShipBoosterComponentHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ShipBoosterComponentImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ShipBoosterComponent*>(stub);
	ShipComponentImplementation::_setStub(stub);
}

DistributedObjectStub* ShipBoosterComponentImplementation::_getStub() {
	return _this.get();
}

ShipBoosterComponentImplementation::operator const ShipBoosterComponent*() {
	return _this.get();
}

void ShipBoosterComponentImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ShipBoosterComponentImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ShipBoosterComponentImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ShipBoosterComponentImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ShipBoosterComponentImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ShipBoosterComponentImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ShipBoosterComponentImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ShipBoosterComponentImplementation::_serializationHelperMethod() {
	ShipComponentImplementation::_serializationHelperMethod();

	_setClassName("ShipBoosterComponent");

}

void ShipBoosterComponentImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipBoosterComponentImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ShipBoosterComponentImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ShipComponentImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x5d4872e4: //ShipBoosterComponent.boosterConsumptionRate
		TypeInfo<float >::parseFromBinaryStream(&boosterConsumptionRate, stream);
		return true;

	case 0x1b172013: //ShipBoosterComponent.boosterAcceleration
		TypeInfo<float >::parseFromBinaryStream(&boosterAcceleration, stream);
		return true;

	case 0x694d274: //ShipBoosterComponent.boosterEnergy
		TypeInfo<float >::parseFromBinaryStream(&boosterEnergy, stream);
		return true;

	case 0x2433decc: //ShipBoosterComponent.boosterRechargeRate
		TypeInfo<float >::parseFromBinaryStream(&boosterRechargeRate, stream);
		return true;

	case 0x7679225f: //ShipBoosterComponent.boosterSpeed
		TypeInfo<float >::parseFromBinaryStream(&boosterSpeed, stream);
		return true;

	}

	return false;
}

void ShipBoosterComponentImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipBoosterComponentImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipBoosterComponentImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ShipComponentImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x5d4872e4; //ShipBoosterComponent.boosterConsumptionRate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterConsumptionRate, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x1b172013; //ShipBoosterComponent.boosterAcceleration
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterAcceleration, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x694d274; //ShipBoosterComponent.boosterEnergy
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterEnergy, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x2433decc; //ShipBoosterComponent.boosterRechargeRate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterRechargeRate, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x7679225f; //ShipBoosterComponent.boosterSpeed
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterSpeed, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

ShipBoosterComponentImplementation::ShipBoosterComponentImplementation() : ShipComponentImplementation() {
	_initializeImplementation();
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterConsumptionRate = 0.f;
	boosterConsumptionRate = 0.f;
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterAcceleration = 0.f;
	boosterAcceleration = 0.f;
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterEnergy = 0.f;
	boosterEnergy = 0.f;
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterRechargeRate = 0.f;
	boosterRechargeRate = 0.f;
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterSpeed = 0.f;
	boosterSpeed = 0.f;
}

float ShipBoosterComponentImplementation::getBoosterAcceleration() {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		return boosterAcceleration;
	return boosterAcceleration;
}

float ShipBoosterComponentImplementation::getBoosterEnergyConsumptionRate() {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		return boosterConsumptionRate;
	return boosterConsumptionRate;
}

float ShipBoosterComponentImplementation::getBoosterEnergy() {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		return boosterEnergy;
	return boosterEnergy;
}

float ShipBoosterComponentImplementation::getBoosterRechargeRate() {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		return boosterRechargeRate;
	return boosterRechargeRate;
}

float ShipBoosterComponentImplementation::getBoosterSpeed() {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		return boosterSpeed;
	return boosterSpeed;
}

void ShipBoosterComponentImplementation::setBoosterAcceleration(float accel) {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterAcceleration = accel;
	boosterAcceleration = accel;
}

void ShipBoosterComponentImplementation::setBoosterEnergyConsumptionRate(float rate) {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterConsumptionRate = rate;
	boosterConsumptionRate = rate;
}

void ShipBoosterComponentImplementation::setBoosterEnergy(float energy) {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterEnergy = energy;
	boosterEnergy = energy;
}

void ShipBoosterComponentImplementation::setBoosterRechargeRate(float rate) {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterRechargeRate = rate;
	boosterRechargeRate = rate;
}

void ShipBoosterComponentImplementation::setBoosterSpeed(float speed) {
	// server/zone/objects/ship/components/ShipBoosterComponent.idl():  		boosterSpeed = speed;
	boosterSpeed = speed;
}

/*
 *	ShipBoosterComponentAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ShipBoosterComponentAdapter::ShipBoosterComponentAdapter(ShipBoosterComponent* obj) : ShipComponentAdapter(obj) {
}

void ShipBoosterComponentAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_GETBOOSTERACCELERATION__:
		{
			
			float _m_res = getBoosterAcceleration();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETBOOSTERENERGYCONSUMPTIONRATE__:
		{
			
			float _m_res = getBoosterEnergyConsumptionRate();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETBOOSTERENERGY__:
		{
			
			float _m_res = getBoosterEnergy();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETBOOSTERRECHARGERATE__:
		{
			
			float _m_res = getBoosterRechargeRate();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETBOOSTERSPEED__:
		{
			
			float _m_res = getBoosterSpeed();
			resp->insertFloat(_m_res);
		}
		break;
	default:
		ShipComponentAdapter::invokeMethod(methid, inv);
	}
}

float ShipBoosterComponentAdapter::getBoosterAcceleration() {
	return (static_cast<ShipBoosterComponent*>(stub))->getBoosterAcceleration();
}

float ShipBoosterComponentAdapter::getBoosterEnergyConsumptionRate() {
	return (static_cast<ShipBoosterComponent*>(stub))->getBoosterEnergyConsumptionRate();
}

float ShipBoosterComponentAdapter::getBoosterEnergy() {
	return (static_cast<ShipBoosterComponent*>(stub))->getBoosterEnergy();
}

float ShipBoosterComponentAdapter::getBoosterRechargeRate() {
	return (static_cast<ShipBoosterComponent*>(stub))->getBoosterRechargeRate();
}

float ShipBoosterComponentAdapter::getBoosterSpeed() {
	return (static_cast<ShipBoosterComponent*>(stub))->getBoosterSpeed();
}

/*
 *	ShipBoosterComponentHelper
 */

ShipBoosterComponentHelper* ShipBoosterComponentHelper::staticInitializer = ShipBoosterComponentHelper::instance();

ShipBoosterComponentHelper::ShipBoosterComponentHelper() {
	className = "ShipBoosterComponent";

	Core::getObjectBroker()->registerClass(className, this);
}

void ShipBoosterComponentHelper::finalizeHelper() {
	ShipBoosterComponentHelper::finalize();
}

DistributedObject* ShipBoosterComponentHelper::instantiateObject() {
	return new ShipBoosterComponent(DummyConstructorParameter::instance());
}

DistributedObjectServant* ShipBoosterComponentHelper::instantiateServant() {
	return new ShipBoosterComponentImplementation();
}

DistributedObjectPOD* ShipBoosterComponentHelper::instantiatePOD() {
	return new ShipBoosterComponentPOD();
}

DistributedObjectAdapter* ShipBoosterComponentHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ShipBoosterComponentAdapter(static_cast<ShipBoosterComponent*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ShipBoosterComponentPOD
 */

ShipBoosterComponentPOD::~ShipBoosterComponentPOD() {
	finalize();
}

ShipBoosterComponentPOD::ShipBoosterComponentPOD(void) {
	_className = "ShipBoosterComponent";
}


void ShipBoosterComponentPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipBoosterComponentPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipBoosterComponentPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ShipComponentPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (boosterConsumptionRate) {
	_nameHashCode = 0x5d4872e4; //ShipBoosterComponent.boosterConsumptionRate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterConsumptionRate.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (boosterAcceleration) {
	_nameHashCode = 0x1b172013; //ShipBoosterComponent.boosterAcceleration
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterAcceleration.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (boosterEnergy) {
	_nameHashCode = 0x694d274; //ShipBoosterComponent.boosterEnergy
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterEnergy.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (boosterRechargeRate) {
	_nameHashCode = 0x2433decc; //ShipBoosterComponent.boosterRechargeRate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterRechargeRate.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (boosterSpeed) {
	_nameHashCode = 0x7679225f; //ShipBoosterComponent.boosterSpeed
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&boosterSpeed.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ShipBoosterComponentPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ShipComponentPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x5d4872e4: //ShipBoosterComponent.boosterConsumptionRate
		{
			float _mnboosterConsumptionRate;
			TypeInfo<float >::parseFromBinaryStream(&_mnboosterConsumptionRate, stream);
			boosterConsumptionRate = std::move(_mnboosterConsumptionRate);
		}
		return true;

	case 0x1b172013: //ShipBoosterComponent.boosterAcceleration
		{
			float _mnboosterAcceleration;
			TypeInfo<float >::parseFromBinaryStream(&_mnboosterAcceleration, stream);
			boosterAcceleration = std::move(_mnboosterAcceleration);
		}
		return true;

	case 0x694d274: //ShipBoosterComponent.boosterEnergy
		{
			float _mnboosterEnergy;
			TypeInfo<float >::parseFromBinaryStream(&_mnboosterEnergy, stream);
			boosterEnergy = std::move(_mnboosterEnergy);
		}
		return true;

	case 0x2433decc: //ShipBoosterComponent.boosterRechargeRate
		{
			float _mnboosterRechargeRate;
			TypeInfo<float >::parseFromBinaryStream(&_mnboosterRechargeRate, stream);
			boosterRechargeRate = std::move(_mnboosterRechargeRate);
		}
		return true;

	case 0x7679225f: //ShipBoosterComponent.boosterSpeed
		{
			float _mnboosterSpeed;
			TypeInfo<float >::parseFromBinaryStream(&_mnboosterSpeed, stream);
			boosterSpeed = std::move(_mnboosterSpeed);
		}
		return true;

	}

	return false;
}

void ShipBoosterComponentPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipBoosterComponentPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ShipBoosterComponentPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ShipComponentPOD::writeObjectCompact(stream);

	TypeInfo<float >::toBinaryStream(&boosterConsumptionRate.value(), stream);

	TypeInfo<float >::toBinaryStream(&boosterAcceleration.value(), stream);

	TypeInfo<float >::toBinaryStream(&boosterEnergy.value(), stream);

	TypeInfo<float >::toBinaryStream(&boosterRechargeRate.value(), stream);

	TypeInfo<float >::toBinaryStream(&boosterSpeed.value(), stream);


}

