/*
 *	autogen/server/zone/objects/ship/components/ShipChassisComponent.h generated by engine3 IDL compiler 0.70
 */

#ifndef SHIPCHASSISCOMPONENT_H_
#define SHIPCHASSISCOMPONENT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "templates/SharedObjectTemplate.h"

#include "server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.h"

#include "server/zone/objects/ship/components/ShipComponent.h"

#include "system/util/Vector.h"

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipChassisComponent : public ShipComponent {
public:
	ShipChassisComponent();

	String getCertificationRequired();

	int getTotalSkillsRequired();

	String getSkillRequired(int index);

	String getChassisDeed();

	int getDealerFee();

	void setCertificationRequired(String& cert);

	void loadTemplateData(SharedObjectTemplate* templateData);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ShipChassisComponent(DummyConstructorParameter* param);

	virtual ~ShipChassisComponent();

	friend class ShipChassisComponentHelper;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipChassisComponentImplementation : public ShipComponentImplementation {
	String chassisDeed;

	String certification;

	Vector<String> skillsRequired;

	int dealerFee;

	bool pob;

public:
	ShipChassisComponentImplementation();

	ShipChassisComponentImplementation(DummyConstructorParameter* param);

	String getCertificationRequired();

	int getTotalSkillsRequired();

	String getSkillRequired(int index);

	String getChassisDeed();

	int getDealerFee();

	void setCertificationRequired(String& cert);

	void loadTemplateData(SharedObjectTemplate* templateData);

	void fillAttributeList(AttributeListMessage* msg, CreatureObject* object);

	virtual void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	WeakReference<ShipChassisComponent*> _this;

	operator const ShipChassisComponent*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ShipChassisComponentImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ShipChassisComponent;
};

class ShipChassisComponentAdapter : public ShipComponentAdapter {
public:
	ShipChassisComponentAdapter(ShipChassisComponent* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	String getCertificationRequired();

	int getTotalSkillsRequired();

	String getSkillRequired(int index);

	String getChassisDeed();

	int getDealerFee();

	void setCertificationRequired(String& cert);

};

class ShipChassisComponentHelper : public DistributedObjectClassHelper, public Singleton<ShipChassisComponentHelper> {
	static ShipChassisComponentHelper* staticInitializer;

public:
	ShipChassisComponentHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ShipChassisComponentHelper>;
};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace components {

class ShipChassisComponentPOD : public ShipComponentPOD {
public:
	Optional<String> chassisDeed;

	Optional<String> certification;

	Optional<int> dealerFee;

	Optional<bool> pob;

	String _className;
	ShipChassisComponentPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ShipChassisComponentPOD();

};

} // namespace components
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::components;

#endif /*SHIPCHASSISCOMPONENTPOD_H_*/
