/*
 *	autogen/server/zone/objects/tangible/item/CreditChipObject.cpp generated by engine3 IDL compiler 0.70
 */

#include "CreditChipObject.h"

#include "server/zone/packets/object/ObjectMenuResponse.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

/*
 *	CreditChipObjectStub
 */

enum {RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_,};

CreditChipObject::CreditChipObject() : TangibleObject(DummyConstructorParameter::instance()) {
	CreditChipObjectImplementation* _implementation = new CreditChipObjectImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("CreditChipObject");
}

CreditChipObject::CreditChipObject(DummyConstructorParameter* param) : TangibleObject(param) {
	_setClassName("CreditChipObject");
}

CreditChipObject::~CreditChipObject() {
}



void CreditChipObject::fillObjectMenuResponse(ObjectMenuResponse* menuResponse, CreatureObject* player) {
	CreditChipObjectImplementation* _implementation = static_cast<CreditChipObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillObjectMenuResponse(menuResponse, player);
	}
}

int CreditChipObject::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	CreditChipObjectImplementation* _implementation = static_cast<CreditChipObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_);
		method.addObjectParameter(player);
		method.addByteParameter(selectedID);

		return method.executeWithSignedIntReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		assert((player == NULL) || player->isLockedByCurrentThread());
		return _implementation->handleObjectMenuSelect(player, selectedID);
	}
}

void CreditChipObject::fillAttributeList(AttributeListMessage* msg, CreatureObject* player) {
	CreditChipObjectImplementation* _implementation = static_cast<CreditChipObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(msg, player);
	}
}

DistributedObjectServant* CreditChipObject::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* CreditChipObject::_getImplementationForRead() const {
	return _impl;
}

void CreditChipObject::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	CreditChipObjectImplementation
 */

CreditChipObjectImplementation::CreditChipObjectImplementation(DummyConstructorParameter* param) : TangibleObjectImplementation(param) {
	_initializeImplementation();
}


CreditChipObjectImplementation::~CreditChipObjectImplementation() {
}


void CreditChipObjectImplementation::finalize() {
}

void CreditChipObjectImplementation::_initializeImplementation() {
	_setClassHelper(CreditChipObjectHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void CreditChipObjectImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<CreditChipObject*>(stub);
	TangibleObjectImplementation::_setStub(stub);
}

DistributedObjectStub* CreditChipObjectImplementation::_getStub() {
	return _this.get();
}

CreditChipObjectImplementation::operator const CreditChipObject*() {
	return _this.get();
}

void CreditChipObjectImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void CreditChipObjectImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void CreditChipObjectImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void CreditChipObjectImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void CreditChipObjectImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void CreditChipObjectImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void CreditChipObjectImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void CreditChipObjectImplementation::_serializationHelperMethod() {
	TangibleObjectImplementation::_serializationHelperMethod();

	_setClassName("CreditChipObject");

}

void CreditChipObjectImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(CreditChipObjectImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool CreditChipObjectImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void CreditChipObjectImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = CreditChipObjectImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int CreditChipObjectImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

void CreditChipObjectImplementation::writeJSON(nlohmann::json& j) {
	TangibleObjectImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
}

CreditChipObjectImplementation::CreditChipObjectImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/item/CreditChipObject.idl():  		Logger.setLoggingName("CreditChipObject");
	Logger::setLoggingName("CreditChipObject");
	// server/zone/objects/tangible/item/CreditChipObject.idl():  		initializeMembers();
	initializeMembers();
}

/*
 *	CreditChipObjectAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


CreditChipObjectAdapter::CreditChipObjectAdapter(CreditChipObject* obj) : TangibleObjectAdapter(obj) {
}

void CreditChipObjectAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			byte selectedID = inv->getByteParameter();
			
			int _m_res = handleObjectMenuSelect(player, selectedID);
			resp->insertSignedInt(_m_res);
		}
		break;
	default:
		TangibleObjectAdapter::invokeMethod(methid, inv);
	}
}

int CreditChipObjectAdapter::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	return (static_cast<CreditChipObject*>(stub))->handleObjectMenuSelect(player, selectedID);
}

/*
 *	CreditChipObjectHelper
 */

CreditChipObjectHelper* CreditChipObjectHelper::staticInitializer = CreditChipObjectHelper::instance();

CreditChipObjectHelper::CreditChipObjectHelper() {
	className = "CreditChipObject";

	Core::getObjectBroker()->registerClass(className, this);
}

void CreditChipObjectHelper::finalizeHelper() {
	CreditChipObjectHelper::finalize();
}

DistributedObject* CreditChipObjectHelper::instantiateObject() {
	return new CreditChipObject(DummyConstructorParameter::instance());
}

DistributedObjectServant* CreditChipObjectHelper::instantiateServant() {
	return new CreditChipObjectImplementation();
}

DistributedObjectPOD* CreditChipObjectHelper::instantiatePOD() {
	return new CreditChipObjectPOD();
}

DistributedObjectAdapter* CreditChipObjectHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new CreditChipObjectAdapter(static_cast<CreditChipObject*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	CreditChipObjectPOD
 */

CreditChipObjectPOD::~CreditChipObjectPOD() {
	finalize();
}

CreditChipObjectPOD::CreditChipObjectPOD(void) {
	_className = "CreditChipObject";
}


void CreditChipObjectPOD::writeJSON(nlohmann::json& j) {
	TangibleObjectPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
}


void CreditChipObjectPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = CreditChipObjectPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int CreditChipObjectPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool CreditChipObjectPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void CreditChipObjectPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(CreditChipObjectPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void CreditChipObjectPOD::writeObjectCompact(ObjectOutputStream* stream) {
	TangibleObjectPOD::writeObjectCompact(stream);


}

