/*
 *	autogen/server/zone/objects/area/areashapes/CuboidAreaShape.h generated by engine3 IDL compiler 0.70
 */

#ifndef CUBOIDAREASHAPE_H_
#define CUBOIDAREASHAPE_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace areashapes {

class SphereAreaShape;

class SphereAreaShapePOD;

} // namespace areashapes
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::areashapes;

#include "engine/util/u3d/Vector3.h"

#include "server/zone/objects/area/areashapes/AreaShape.h"

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace areashapes {

class CuboidAreaShape : public AreaShape {
public:
	CuboidAreaShape();

	void setDimensions(float len, float wid, float hght);

	Vector3 getCuboidDimensions() const;

	float getVolume();

	float getHeight();

	float getWidth();

	float getLength();

	float getMinX();

	float getMinY();

	float getMinZ();

	float getMaxX();

	float getMaxY();

	float getMaxZ();

	/**
	 * Check if the coordinate is within the area shape.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 * @param z the z coordinate.
	 * @return true if the coordinate is within the area shape.
	 */
	bool containsPoint(float x, float z, float y) const;

	/**
	 * Check if the coordinate is within the area shape.
	 * @param point the point to check if it is within the area shape.
	 * @return true if the coordinate is within the area shape.
	 */
	bool containsPoint(const Vector3& point) const;

	/**
	 * Get the minimum radius of a circle bounding the area shape.
	 * @return the minimum bonding radius.
	 */
	float getRadius() const;

	/**
	 * Generate a random position within the area.
	 * @return a random position within the area.
	 */
	Vector3 getRandomPosition() const;

	/**
	 * Generate a random position within the area with the supplied origin and radius as limits.
	 * @param origin the origin coordinate to generate the random position from.
	 * @param minDistance the minimum distance from the origin.
	 * @param maxDistance the maximum distance from the origin.
	 * @return a random position within the area.
	 */
	Vector3 getRandomPosition(const Vector3& origin, float minDistance, float maxDistance) const;

	/**
	 * Check if this area shape intersects with the supplied area shape.
	 * @param areaShape the area shape to check for intersections with.s
	 * @return true if the area shapes intersects each other.
	 */
	bool intersectsWith(AreaShape* areaShape) const;

	/**
	 * Check if this is a cuboid area shape.
	 * @return true if it is a cuboid area shape.
	 */
	bool isCuboidAreaShape() const;

	String getDimensionLog();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	CuboidAreaShape(DummyConstructorParameter* param);

	virtual ~CuboidAreaShape();

	friend class CuboidAreaShapeHelper;
};

} // namespace areashapes
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::areashapes;

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace areashapes {

class CuboidAreaShapeImplementation : public AreaShapeImplementation {
protected:
	float length;

	float width;

	float height;

	float minX;

	float maxX;

	float minY;

	float maxY;

	float minZ;

	float maxZ;

public:
	CuboidAreaShapeImplementation();

	CuboidAreaShapeImplementation(DummyConstructorParameter* param);

	void setDimensions(float len, float wid, float hght);

	Vector3 getCuboidDimensions() const;

	float getVolume();

	float getHeight();

	float getWidth();

	float getLength();

	float getMinX();

	float getMinY();

	float getMinZ();

	float getMaxX();

	float getMaxY();

	float getMaxZ();

	/**
	 * Check if the coordinate is within the area shape.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 * @param z the z coordinate.
	 * @return true if the coordinate is within the area shape.
	 */
	bool containsPoint(float x, float z, float y) const;

	/**
	 * Check if the coordinate is within the area shape.
	 * @param point the point to check if it is within the area shape.
	 * @return true if the coordinate is within the area shape.
	 */
	bool containsPoint(const Vector3& point) const;

	/**
	 * Get the minimum radius of a circle bounding the area shape.
	 * @return the minimum bonding radius.
	 */
	float getRadius() const;

	/**
	 * Generate a random position within the area.
	 * @return a random position within the area.
	 */
	Vector3 getRandomPosition() const;

	/**
	 * Generate a random position within the area with the supplied origin and radius as limits.
	 * @param origin the origin coordinate to generate the random position from.
	 * @param minDistance the minimum distance from the origin.
	 * @param maxDistance the maximum distance from the origin.
	 * @return a random position within the area.
	 */
	Vector3 getRandomPosition(const Vector3& origin, float minDistance, float maxDistance) const;

	/**
	 * Check if this area shape intersects with the supplied area shape.
	 * @param areaShape the area shape to check for intersections with.s
	 * @return true if the area shapes intersects each other.
	 */
	bool intersectsWith(AreaShape* areaShape) const;

private:
	bool intersectsWithCuboid(CuboidAreaShape* cuboid) const;

	bool intersectsWithSphere(SphereAreaShape* sphere) const;

public:
	/**
	 * Check if this is a cuboid area shape.
	 * @return true if it is a cuboid area shape.
	 */
	bool isCuboidAreaShape() const;

	String getDimensionLog();

	WeakReference<CuboidAreaShape*> _this;

	operator const CuboidAreaShape*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~CuboidAreaShapeImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class CuboidAreaShape;
};

class CuboidAreaShapeAdapter : public AreaShapeAdapter {
public:
	CuboidAreaShapeAdapter(CuboidAreaShape* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void setDimensions(float len, float wid, float hght);

	float getVolume();

	float getHeight();

	float getWidth();

	float getLength();

	float getMinX();

	float getMinY();

	float getMinZ();

	float getMaxX();

	float getMaxY();

	float getMaxZ();

	bool containsPoint(float x, float z, float y) const;

	float getRadius() const;

	bool intersectsWith(AreaShape* areaShape) const;

	bool isCuboidAreaShape() const;

	String getDimensionLog();

};

class CuboidAreaShapeHelper : public DistributedObjectClassHelper, public Singleton<CuboidAreaShapeHelper> {
	static CuboidAreaShapeHelper* staticInitializer;

public:
	CuboidAreaShapeHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<CuboidAreaShapeHelper>;
};

} // namespace areashapes
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::areashapes;

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace areashapes {

class CuboidAreaShapePOD : public AreaShapePOD {
public:
	Optional<float> length;

	Optional<float> width;

	Optional<float> height;

	Optional<float> minX;

	Optional<float> maxX;

	Optional<float> minY;

	Optional<float> maxY;

	Optional<float> minZ;

	Optional<float> maxZ;

	String _className;
	CuboidAreaShapePOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~CuboidAreaShapePOD();

};

} // namespace areashapes
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::areashapes;

#endif /*CUBOIDAREASHAPEPOD_H_*/
