/*
 *	autogen/server/zone/objects/area/areashapes/CuboidAreaShape.cpp generated by engine3 IDL compiler 0.70
 */

#include "CuboidAreaShape.h"

#include "server/zone/objects/area/areashapes/SphereAreaShape.h"

/*
 *	CuboidAreaShapeStub
 */

enum {RPC_SETDIMENSIONS__FLOAT_FLOAT_FLOAT_ = 3956787085,RPC_GETVOLUME__,RPC_GETHEIGHT__,RPC_GETWIDTH__,RPC_GETLENGTH__,RPC_GETMINX__,RPC_GETMINY__,RPC_GETMINZ__,RPC_GETMAXX__,RPC_GETMAXY__,RPC_GETMAXZ__,RPC_CONTAINSPOINT__FLOAT_FLOAT_FLOAT_,RPC_GETRADIUS__,RPC_INTERSECTSWITH__AREASHAPE_,RPC_ISCUBOIDAREASHAPE__,RPC_GETDIMENSIONLOG__};

CuboidAreaShape::CuboidAreaShape() : AreaShape(DummyConstructorParameter::instance()) {
	CuboidAreaShapeImplementation* _implementation = new CuboidAreaShapeImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("CuboidAreaShape");
}

CuboidAreaShape::CuboidAreaShape(DummyConstructorParameter* param) : AreaShape(param) {
	_setClassName("CuboidAreaShape");
}

CuboidAreaShape::~CuboidAreaShape() {
}



void CuboidAreaShape::setDimensions(float len, float wid, float hght) {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETDIMENSIONS__FLOAT_FLOAT_FLOAT_);
		method.addFloatParameter(len);
		method.addFloatParameter(wid);
		method.addFloatParameter(hght);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setDimensions(len, wid, hght);
	}
}

Vector3 CuboidAreaShape::getCuboidDimensions() const {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getCuboidDimensions();
	}
}

float CuboidAreaShape::getVolume() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETVOLUME__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getVolume();
	}
}

float CuboidAreaShape::getHeight() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETHEIGHT__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getHeight();
	}
}

float CuboidAreaShape::getWidth() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETWIDTH__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getWidth();
	}
}

float CuboidAreaShape::getLength() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETLENGTH__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getLength();
	}
}

float CuboidAreaShape::getMinX() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETMINX__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getMinX();
	}
}

float CuboidAreaShape::getMinY() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETMINY__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getMinY();
	}
}

float CuboidAreaShape::getMinZ() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETMINZ__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getMinZ();
	}
}

float CuboidAreaShape::getMaxX() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETMAXX__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getMaxX();
	}
}

float CuboidAreaShape::getMaxY() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETMAXY__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getMaxY();
	}
}

float CuboidAreaShape::getMaxZ() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETMAXZ__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getMaxZ();
	}
}

bool CuboidAreaShape::containsPoint(float x, float z, float y) const {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CONTAINSPOINT__FLOAT_FLOAT_FLOAT_);
		method.addFloatParameter(x);
		method.addFloatParameter(z);
		method.addFloatParameter(y);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->containsPoint(x, z, y);
	}
}

bool CuboidAreaShape::containsPoint(const Vector3& point) const {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->containsPoint(point);
	}
}

float CuboidAreaShape::getRadius() const {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETRADIUS__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getRadius();
	}
}

Vector3 CuboidAreaShape::getRandomPosition() const {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getRandomPosition();
	}
}

Vector3 CuboidAreaShape::getRandomPosition(const Vector3& origin, float minDistance, float maxDistance) const {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getRandomPosition(origin, minDistance, maxDistance);
	}
}

bool CuboidAreaShape::intersectsWith(AreaShape* areaShape) const {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INTERSECTSWITH__AREASHAPE_);
		method.addObjectParameter(areaShape);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->intersectsWith(areaShape);
	}
}

bool CuboidAreaShape::isCuboidAreaShape() const {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISCUBOIDAREASHAPE__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isCuboidAreaShape();
	}
}

String CuboidAreaShape::getDimensionLog() {
	CuboidAreaShapeImplementation* _implementation = static_cast<CuboidAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETDIMENSIONLOG__);

		String _return_getDimensionLog;
		method.executeWithAsciiReturn(_return_getDimensionLog);
		return _return_getDimensionLog;
	} else {
		return _implementation->getDimensionLog();
	}
}

DistributedObjectServant* CuboidAreaShape::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* CuboidAreaShape::_getImplementationForRead() const {
	return _impl;
}

void CuboidAreaShape::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	CuboidAreaShapeImplementation
 */

CuboidAreaShapeImplementation::CuboidAreaShapeImplementation(DummyConstructorParameter* param) : AreaShapeImplementation(param) {
	_initializeImplementation();
}


CuboidAreaShapeImplementation::~CuboidAreaShapeImplementation() {
}


void CuboidAreaShapeImplementation::finalize() {
}

void CuboidAreaShapeImplementation::_initializeImplementation() {
	_setClassHelper(CuboidAreaShapeHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void CuboidAreaShapeImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<CuboidAreaShape*>(stub);
	AreaShapeImplementation::_setStub(stub);
}

DistributedObjectStub* CuboidAreaShapeImplementation::_getStub() {
	return _this.get();
}

CuboidAreaShapeImplementation::operator const CuboidAreaShape*() {
	return _this.get();
}

void CuboidAreaShapeImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void CuboidAreaShapeImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void CuboidAreaShapeImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void CuboidAreaShapeImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void CuboidAreaShapeImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void CuboidAreaShapeImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void CuboidAreaShapeImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void CuboidAreaShapeImplementation::_serializationHelperMethod() {
	AreaShapeImplementation::_serializationHelperMethod();

	_setClassName("CuboidAreaShape");

}

void CuboidAreaShapeImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(CuboidAreaShapeImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool CuboidAreaShapeImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (AreaShapeImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xa9105d36: //CuboidAreaShape.length
		TypeInfo<float >::parseFromBinaryStream(&length, stream);
		return true;

	case 0xacf023bd: //CuboidAreaShape.width
		TypeInfo<float >::parseFromBinaryStream(&width, stream);
		return true;

	case 0x7f122f41: //CuboidAreaShape.height
		TypeInfo<float >::parseFromBinaryStream(&height, stream);
		return true;

	case 0x36eb84c7: //CuboidAreaShape.minX
		TypeInfo<float >::parseFromBinaryStream(&minX, stream);
		return true;

	case 0xcda9c44a: //CuboidAreaShape.maxX
		TypeInfo<float >::parseFromBinaryStream(&maxX, stream);
		return true;

	case 0x322a9970: //CuboidAreaShape.minY
		TypeInfo<float >::parseFromBinaryStream(&minY, stream);
		return true;

	case 0xc968d9fd: //CuboidAreaShape.maxY
		TypeInfo<float >::parseFromBinaryStream(&maxY, stream);
		return true;

	case 0x3f69bfa9: //CuboidAreaShape.minZ
		TypeInfo<float >::parseFromBinaryStream(&minZ, stream);
		return true;

	case 0xc42bff24: //CuboidAreaShape.maxZ
		TypeInfo<float >::parseFromBinaryStream(&maxZ, stream);
		return true;

	}

	return false;
}

void CuboidAreaShapeImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = CuboidAreaShapeImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int CuboidAreaShapeImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = AreaShapeImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xa9105d36; //CuboidAreaShape.length
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&length, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xacf023bd; //CuboidAreaShape.width
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&width, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x7f122f41; //CuboidAreaShape.height
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&height, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x36eb84c7; //CuboidAreaShape.minX
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&minX, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xcda9c44a; //CuboidAreaShape.maxX
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&maxX, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x322a9970; //CuboidAreaShape.minY
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&minY, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xc968d9fd; //CuboidAreaShape.maxY
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&maxY, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x3f69bfa9; //CuboidAreaShape.minZ
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&minZ, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xc42bff24; //CuboidAreaShape.maxZ
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&maxZ, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

CuboidAreaShapeImplementation::CuboidAreaShapeImplementation() : AreaShapeImplementation() {
	_initializeImplementation();
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		length = 0.f;
	length = 0.f;
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		width = 0.f;
	width = 0.f;
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		height = 0.f;
	height = 0.f;
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		Logger.setLoggingName("CuboidAreaShape");
	Logger::setLoggingName("CuboidAreaShape");
}

float CuboidAreaShapeImplementation::getVolume() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return 2 * (length * width + length * height + width * height);
	return 2 * (length * width + length * height + width * height);
}

float CuboidAreaShapeImplementation::getHeight() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return height;
	return height;
}

float CuboidAreaShapeImplementation::getWidth() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return width;
	return width;
}

float CuboidAreaShapeImplementation::getLength() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return length;
	return length;
}

float CuboidAreaShapeImplementation::getMinX() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return minX;
	return minX;
}

float CuboidAreaShapeImplementation::getMinY() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return minX;
	return minX;
}

float CuboidAreaShapeImplementation::getMinZ() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return minX;
	return minX;
}

float CuboidAreaShapeImplementation::getMaxX() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return minX;
	return minX;
}

float CuboidAreaShapeImplementation::getMaxY() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return minX;
	return minX;
}

float CuboidAreaShapeImplementation::getMaxZ() {
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return minX;
	return minX;
}

bool CuboidAreaShapeImplementation::isCuboidAreaShape() const{
	// server/zone/objects/area/areashapes/CuboidAreaShape.idl():  		return true;
	return true;
}

/*
 *	CuboidAreaShapeAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


CuboidAreaShapeAdapter::CuboidAreaShapeAdapter(CuboidAreaShape* obj) : AreaShapeAdapter(obj) {
}

void CuboidAreaShapeAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_SETDIMENSIONS__FLOAT_FLOAT_FLOAT_:
		{
			float len = inv->getFloatParameter();
			float wid = inv->getFloatParameter();
			float hght = inv->getFloatParameter();
			
			setDimensions(len, wid, hght);
			
		}
		break;
	case RPC_GETVOLUME__:
		{
			
			float _m_res = getVolume();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETHEIGHT__:
		{
			
			float _m_res = getHeight();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETWIDTH__:
		{
			
			float _m_res = getWidth();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETLENGTH__:
		{
			
			float _m_res = getLength();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETMINX__:
		{
			
			float _m_res = getMinX();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETMINY__:
		{
			
			float _m_res = getMinY();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETMINZ__:
		{
			
			float _m_res = getMinZ();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETMAXX__:
		{
			
			float _m_res = getMaxX();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETMAXY__:
		{
			
			float _m_res = getMaxY();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETMAXZ__:
		{
			
			float _m_res = getMaxZ();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_CONTAINSPOINT__FLOAT_FLOAT_FLOAT_:
		{
			float x = inv->getFloatParameter();
			float z = inv->getFloatParameter();
			float y = inv->getFloatParameter();
			
			bool _m_res = containsPoint(x, z, y);
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_GETRADIUS__:
		{
			
			float _m_res = getRadius();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_INTERSECTSWITH__AREASHAPE_:
		{
			AreaShape* areaShape = static_cast<AreaShape*>(inv->getObjectParameter());
			
			bool _m_res = intersectsWith(areaShape);
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_ISCUBOIDAREASHAPE__:
		{
			
			bool _m_res = isCuboidAreaShape();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_GETDIMENSIONLOG__:
		{
			
			String _m_res = getDimensionLog();
			resp->insertAscii(_m_res);
		}
		break;
	default:
		AreaShapeAdapter::invokeMethod(methid, inv);
	}
}

void CuboidAreaShapeAdapter::setDimensions(float len, float wid, float hght) {
	(static_cast<CuboidAreaShape*>(stub))->setDimensions(len, wid, hght);
}

float CuboidAreaShapeAdapter::getVolume() {
	return (static_cast<CuboidAreaShape*>(stub))->getVolume();
}

float CuboidAreaShapeAdapter::getHeight() {
	return (static_cast<CuboidAreaShape*>(stub))->getHeight();
}

float CuboidAreaShapeAdapter::getWidth() {
	return (static_cast<CuboidAreaShape*>(stub))->getWidth();
}

float CuboidAreaShapeAdapter::getLength() {
	return (static_cast<CuboidAreaShape*>(stub))->getLength();
}

float CuboidAreaShapeAdapter::getMinX() {
	return (static_cast<CuboidAreaShape*>(stub))->getMinX();
}

float CuboidAreaShapeAdapter::getMinY() {
	return (static_cast<CuboidAreaShape*>(stub))->getMinY();
}

float CuboidAreaShapeAdapter::getMinZ() {
	return (static_cast<CuboidAreaShape*>(stub))->getMinZ();
}

float CuboidAreaShapeAdapter::getMaxX() {
	return (static_cast<CuboidAreaShape*>(stub))->getMaxX();
}

float CuboidAreaShapeAdapter::getMaxY() {
	return (static_cast<CuboidAreaShape*>(stub))->getMaxY();
}

float CuboidAreaShapeAdapter::getMaxZ() {
	return (static_cast<CuboidAreaShape*>(stub))->getMaxZ();
}

bool CuboidAreaShapeAdapter::containsPoint(float x, float z, float y) const {
	return (static_cast<CuboidAreaShape*>(stub))->containsPoint(x, z, y);
}

float CuboidAreaShapeAdapter::getRadius() const {
	return (static_cast<CuboidAreaShape*>(stub))->getRadius();
}

bool CuboidAreaShapeAdapter::intersectsWith(AreaShape* areaShape) const {
	return (static_cast<CuboidAreaShape*>(stub))->intersectsWith(areaShape);
}

bool CuboidAreaShapeAdapter::isCuboidAreaShape() const {
	return (static_cast<CuboidAreaShape*>(stub))->isCuboidAreaShape();
}

String CuboidAreaShapeAdapter::getDimensionLog() {
	return (static_cast<CuboidAreaShape*>(stub))->getDimensionLog();
}

/*
 *	CuboidAreaShapeHelper
 */

CuboidAreaShapeHelper* CuboidAreaShapeHelper::staticInitializer = CuboidAreaShapeHelper::instance();

CuboidAreaShapeHelper::CuboidAreaShapeHelper() {
	className = "CuboidAreaShape";

	Core::getObjectBroker()->registerClass(className, this);
}

void CuboidAreaShapeHelper::finalizeHelper() {
	CuboidAreaShapeHelper::finalize();
}

DistributedObject* CuboidAreaShapeHelper::instantiateObject() {
	return new CuboidAreaShape(DummyConstructorParameter::instance());
}

DistributedObjectServant* CuboidAreaShapeHelper::instantiateServant() {
	return new CuboidAreaShapeImplementation();
}

DistributedObjectPOD* CuboidAreaShapeHelper::instantiatePOD() {
	return new CuboidAreaShapePOD();
}

DistributedObjectAdapter* CuboidAreaShapeHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new CuboidAreaShapeAdapter(static_cast<CuboidAreaShape*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	CuboidAreaShapePOD
 */

CuboidAreaShapePOD::~CuboidAreaShapePOD() {
}

CuboidAreaShapePOD::CuboidAreaShapePOD(void) {
	_className = "CuboidAreaShape";
}


void CuboidAreaShapePOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = CuboidAreaShapePOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int CuboidAreaShapePOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = AreaShapePOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (length) {
	_nameHashCode = 0xa9105d36; //CuboidAreaShape.length
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&length.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (width) {
	_nameHashCode = 0xacf023bd; //CuboidAreaShape.width
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&width.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (height) {
	_nameHashCode = 0x7f122f41; //CuboidAreaShape.height
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&height.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (minX) {
	_nameHashCode = 0x36eb84c7; //CuboidAreaShape.minX
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&minX.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (maxX) {
	_nameHashCode = 0xcda9c44a; //CuboidAreaShape.maxX
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&maxX.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (minY) {
	_nameHashCode = 0x322a9970; //CuboidAreaShape.minY
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&minY.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (maxY) {
	_nameHashCode = 0xc968d9fd; //CuboidAreaShape.maxY
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&maxY.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (minZ) {
	_nameHashCode = 0x3f69bfa9; //CuboidAreaShape.minZ
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&minZ.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (maxZ) {
	_nameHashCode = 0xc42bff24; //CuboidAreaShape.maxZ
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&maxZ.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool CuboidAreaShapePOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (AreaShapePOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xa9105d36: //CuboidAreaShape.length
		{
			float _mnlength;
			TypeInfo<float >::parseFromBinaryStream(&_mnlength, stream);
			length = std::move(_mnlength);
		}
		return true;

	case 0xacf023bd: //CuboidAreaShape.width
		{
			float _mnwidth;
			TypeInfo<float >::parseFromBinaryStream(&_mnwidth, stream);
			width = std::move(_mnwidth);
		}
		return true;

	case 0x7f122f41: //CuboidAreaShape.height
		{
			float _mnheight;
			TypeInfo<float >::parseFromBinaryStream(&_mnheight, stream);
			height = std::move(_mnheight);
		}
		return true;

	case 0x36eb84c7: //CuboidAreaShape.minX
		{
			float _mnminX;
			TypeInfo<float >::parseFromBinaryStream(&_mnminX, stream);
			minX = std::move(_mnminX);
		}
		return true;

	case 0xcda9c44a: //CuboidAreaShape.maxX
		{
			float _mnmaxX;
			TypeInfo<float >::parseFromBinaryStream(&_mnmaxX, stream);
			maxX = std::move(_mnmaxX);
		}
		return true;

	case 0x322a9970: //CuboidAreaShape.minY
		{
			float _mnminY;
			TypeInfo<float >::parseFromBinaryStream(&_mnminY, stream);
			minY = std::move(_mnminY);
		}
		return true;

	case 0xc968d9fd: //CuboidAreaShape.maxY
		{
			float _mnmaxY;
			TypeInfo<float >::parseFromBinaryStream(&_mnmaxY, stream);
			maxY = std::move(_mnmaxY);
		}
		return true;

	case 0x3f69bfa9: //CuboidAreaShape.minZ
		{
			float _mnminZ;
			TypeInfo<float >::parseFromBinaryStream(&_mnminZ, stream);
			minZ = std::move(_mnminZ);
		}
		return true;

	case 0xc42bff24: //CuboidAreaShape.maxZ
		{
			float _mnmaxZ;
			TypeInfo<float >::parseFromBinaryStream(&_mnmaxZ, stream);
			maxZ = std::move(_mnmaxZ);
		}
		return true;

	}

	return false;
}

void CuboidAreaShapePOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(CuboidAreaShapePOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void CuboidAreaShapePOD::writeObjectCompact(ObjectOutputStream* stream) {
	AreaShapePOD::writeObjectCompact(stream);

	TypeInfo<float >::toBinaryStream(&length.value(), stream);

	TypeInfo<float >::toBinaryStream(&width.value(), stream);

	TypeInfo<float >::toBinaryStream(&height.value(), stream);

	TypeInfo<float >::toBinaryStream(&minX.value(), stream);

	TypeInfo<float >::toBinaryStream(&maxX.value(), stream);

	TypeInfo<float >::toBinaryStream(&minY.value(), stream);

	TypeInfo<float >::toBinaryStream(&maxY.value(), stream);

	TypeInfo<float >::toBinaryStream(&minZ.value(), stream);

	TypeInfo<float >::toBinaryStream(&maxZ.value(), stream);


}

