/*
 *	autogen/server/zone/objects/area/areashapes/SphereAreaShape.cpp generated by engine3 IDL compiler 0.70
 */

#include "SphereAreaShape.h"

#include "server/zone/objects/area/areashapes/CuboidAreaShape.h"

/*
 *	SphereAreaShapeStub
 */

enum {RPC_SETRADIUS__FLOAT_ = 398174314,RPC_GETAREA__,RPC_GETRADIUS__,RPC_GETRADIUS2__,RPC_CONTAINSPOINT__FLOAT_FLOAT_FLOAT_,RPC_INTERSECTSWITH__AREASHAPE_,RPC_ISSPHEREAREASHAPE__};

SphereAreaShape::SphereAreaShape() : AreaShape(DummyConstructorParameter::instance()) {
	SphereAreaShapeImplementation* _implementation = new SphereAreaShapeImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("SphereAreaShape");
}

SphereAreaShape::SphereAreaShape(DummyConstructorParameter* param) : AreaShape(param) {
	_setClassName("SphereAreaShape");
}

SphereAreaShape::~SphereAreaShape() {
}



void SphereAreaShape::setRadius(float rad) {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETRADIUS__FLOAT_);
		method.addFloatParameter(rad);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setRadius(rad);
	}
}

float SphereAreaShape::getArea() {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETAREA__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getArea();
	}
}

float SphereAreaShape::getRadius() const {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETRADIUS__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getRadius();
	}
}

float SphereAreaShape::getRadius2() const {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETRADIUS2__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getRadius2();
	}
}

bool SphereAreaShape::containsPoint(float x, float z, float y) const {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CONTAINSPOINT__FLOAT_FLOAT_FLOAT_);
		method.addFloatParameter(x);
		method.addFloatParameter(z);
		method.addFloatParameter(y);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->containsPoint(x, z, y);
	}
}

bool SphereAreaShape::containsPoint(const Vector3& point) const {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->containsPoint(point);
	}
}

Vector3 SphereAreaShape::getRandomPosition() const {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getRandomPosition();
	}
}

Vector3 SphereAreaShape::getRandomPosition(const Vector3& origin, float minDistance, float maxDistance) const {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getRandomPosition(origin, minDistance, maxDistance);
	}
}

bool SphereAreaShape::intersectsWith(AreaShape* areaShape) const {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INTERSECTSWITH__AREASHAPE_);
		method.addObjectParameter(areaShape);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->intersectsWith(areaShape);
	}
}

bool SphereAreaShape::isSphereAreaShape() const {
	SphereAreaShapeImplementation* _implementation = static_cast<SphereAreaShapeImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISSPHEREAREASHAPE__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isSphereAreaShape();
	}
}

DistributedObjectServant* SphereAreaShape::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* SphereAreaShape::_getImplementationForRead() const {
	return _impl;
}

void SphereAreaShape::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	SphereAreaShapeImplementation
 */

SphereAreaShapeImplementation::SphereAreaShapeImplementation(DummyConstructorParameter* param) : AreaShapeImplementation(param) {
	_initializeImplementation();
}


SphereAreaShapeImplementation::~SphereAreaShapeImplementation() {
}


void SphereAreaShapeImplementation::finalize() {
}

void SphereAreaShapeImplementation::_initializeImplementation() {
	_setClassHelper(SphereAreaShapeHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void SphereAreaShapeImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<SphereAreaShape*>(stub);
	AreaShapeImplementation::_setStub(stub);
}

DistributedObjectStub* SphereAreaShapeImplementation::_getStub() {
	return _this.get();
}

SphereAreaShapeImplementation::operator const SphereAreaShape*() {
	return _this.get();
}

void SphereAreaShapeImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void SphereAreaShapeImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void SphereAreaShapeImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void SphereAreaShapeImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void SphereAreaShapeImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void SphereAreaShapeImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void SphereAreaShapeImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void SphereAreaShapeImplementation::_serializationHelperMethod() {
	AreaShapeImplementation::_serializationHelperMethod();

	_setClassName("SphereAreaShape");

}

void SphereAreaShapeImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SphereAreaShapeImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool SphereAreaShapeImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (AreaShapeImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xa8079566: //SphereAreaShape.radius
		TypeInfo<float >::parseFromBinaryStream(&radius, stream);
		return true;

	case 0xbcf5cb03: //SphereAreaShape.radius2
		TypeInfo<float >::parseFromBinaryStream(&radius2, stream);
		return true;

	}

	return false;
}

void SphereAreaShapeImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SphereAreaShapeImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SphereAreaShapeImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = AreaShapeImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xa8079566; //SphereAreaShape.radius
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&radius, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xbcf5cb03; //SphereAreaShape.radius2
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&radius2, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

SphereAreaShapeImplementation::SphereAreaShapeImplementation() : AreaShapeImplementation() {
	_initializeImplementation();
	// server/zone/objects/area/areashapes/SphereAreaShape.idl():  		radius = 0.f;
	radius = 0.f;
	// server/zone/objects/area/areashapes/SphereAreaShape.idl():  		radius2 = 0.f;
	radius2 = 0.f;
	// server/zone/objects/area/areashapes/SphereAreaShape.idl():  		Logger.setLoggingName("SphereAreaShape");
	Logger::setLoggingName("SphereAreaShape");
}

void SphereAreaShapeImplementation::setRadius(float rad) {
	// server/zone/objects/area/areashapes/SphereAreaShape.idl():  		radius = rad;
	radius = rad;
	// server/zone/objects/area/areashapes/SphereAreaShape.idl():  		radius2 = rad * rad;
	radius2 = rad * rad;
}

float SphereAreaShapeImplementation::getArea() {
	// server/zone/objects/area/areashapes/SphereAreaShape.idl():  		return 4 * Math.PI * radius * radius;
	return 4 * Math::PI * radius * radius;
}

float SphereAreaShapeImplementation::getRadius() const{
	// server/zone/objects/area/areashapes/SphereAreaShape.idl():  		return radius;
	return radius;
}

float SphereAreaShapeImplementation::getRadius2() const{
	// server/zone/objects/area/areashapes/SphereAreaShape.idl():  		return radius2;
	return radius2;
}

bool SphereAreaShapeImplementation::isSphereAreaShape() const{
	// server/zone/objects/area/areashapes/SphereAreaShape.idl():  		return true;
	return true;
}

/*
 *	SphereAreaShapeAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


SphereAreaShapeAdapter::SphereAreaShapeAdapter(SphereAreaShape* obj) : AreaShapeAdapter(obj) {
}

void SphereAreaShapeAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_SETRADIUS__FLOAT_:
		{
			float rad = inv->getFloatParameter();
			
			setRadius(rad);
			
		}
		break;
	case RPC_GETAREA__:
		{
			
			float _m_res = getArea();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETRADIUS__:
		{
			
			float _m_res = getRadius();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETRADIUS2__:
		{
			
			float _m_res = getRadius2();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_CONTAINSPOINT__FLOAT_FLOAT_FLOAT_:
		{
			float x = inv->getFloatParameter();
			float z = inv->getFloatParameter();
			float y = inv->getFloatParameter();
			
			bool _m_res = containsPoint(x, z, y);
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_INTERSECTSWITH__AREASHAPE_:
		{
			AreaShape* areaShape = static_cast<AreaShape*>(inv->getObjectParameter());
			
			bool _m_res = intersectsWith(areaShape);
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_ISSPHEREAREASHAPE__:
		{
			
			bool _m_res = isSphereAreaShape();
			resp->insertBoolean(_m_res);
		}
		break;
	default:
		AreaShapeAdapter::invokeMethod(methid, inv);
	}
}

void SphereAreaShapeAdapter::setRadius(float rad) {
	(static_cast<SphereAreaShape*>(stub))->setRadius(rad);
}

float SphereAreaShapeAdapter::getArea() {
	return (static_cast<SphereAreaShape*>(stub))->getArea();
}

float SphereAreaShapeAdapter::getRadius() const {
	return (static_cast<SphereAreaShape*>(stub))->getRadius();
}

float SphereAreaShapeAdapter::getRadius2() const {
	return (static_cast<SphereAreaShape*>(stub))->getRadius2();
}

bool SphereAreaShapeAdapter::containsPoint(float x, float z, float y) const {
	return (static_cast<SphereAreaShape*>(stub))->containsPoint(x, z, y);
}

bool SphereAreaShapeAdapter::intersectsWith(AreaShape* areaShape) const {
	return (static_cast<SphereAreaShape*>(stub))->intersectsWith(areaShape);
}

bool SphereAreaShapeAdapter::isSphereAreaShape() const {
	return (static_cast<SphereAreaShape*>(stub))->isSphereAreaShape();
}

/*
 *	SphereAreaShapeHelper
 */

SphereAreaShapeHelper* SphereAreaShapeHelper::staticInitializer = SphereAreaShapeHelper::instance();

SphereAreaShapeHelper::SphereAreaShapeHelper() {
	className = "SphereAreaShape";

	Core::getObjectBroker()->registerClass(className, this);
}

void SphereAreaShapeHelper::finalizeHelper() {
	SphereAreaShapeHelper::finalize();
}

DistributedObject* SphereAreaShapeHelper::instantiateObject() {
	return new SphereAreaShape(DummyConstructorParameter::instance());
}

DistributedObjectServant* SphereAreaShapeHelper::instantiateServant() {
	return new SphereAreaShapeImplementation();
}

DistributedObjectPOD* SphereAreaShapeHelper::instantiatePOD() {
	return new SphereAreaShapePOD();
}

DistributedObjectAdapter* SphereAreaShapeHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new SphereAreaShapeAdapter(static_cast<SphereAreaShape*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	SphereAreaShapePOD
 */

SphereAreaShapePOD::~SphereAreaShapePOD() {
}

SphereAreaShapePOD::SphereAreaShapePOD(void) {
	_className = "SphereAreaShape";
}


void SphereAreaShapePOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SphereAreaShapePOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SphereAreaShapePOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = AreaShapePOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (radius) {
	_nameHashCode = 0xa8079566; //SphereAreaShape.radius
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&radius.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (radius2) {
	_nameHashCode = 0xbcf5cb03; //SphereAreaShape.radius2
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&radius2.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool SphereAreaShapePOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (AreaShapePOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xa8079566: //SphereAreaShape.radius
		{
			float _mnradius;
			TypeInfo<float >::parseFromBinaryStream(&_mnradius, stream);
			radius = std::move(_mnradius);
		}
		return true;

	case 0xbcf5cb03: //SphereAreaShape.radius2
		{
			float _mnradius2;
			TypeInfo<float >::parseFromBinaryStream(&_mnradius2, stream);
			radius2 = std::move(_mnradius2);
		}
		return true;

	}

	return false;
}

void SphereAreaShapePOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SphereAreaShapePOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void SphereAreaShapePOD::writeObjectCompact(ObjectOutputStream* stream) {
	AreaShapePOD::writeObjectCompact(stream);

	TypeInfo<float >::toBinaryStream(&radius.value(), stream);

	TypeInfo<float >::toBinaryStream(&radius2.value(), stream);


}

