/*
 *	autogen/server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.cpp generated by engine3 IDL compiler 0.70
 */

#include "SpaceSpawner.h"

#include "server/zone/objects/tangible/DespawnLairOnPlayerDisappear.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "server/zone/objects/area/space/SpaceActiveArea.h"

#include "server/zone/TreeEntry.h"

/*
 *	SpaceSpawnerStub
 */

enum {RPC_GETNUMBEROFPLAYERSINRANGE__ = 2155941693,RPC_GETDESPAWNONNOPLAYERSINRANGE__,RPC_SETDESPAWNONNOPLAYERSINRANGE__BOOL_,RPC_NOTIFYINSERT__TREEENTRY_,RPC_NOTIFYDISSAPEAR__TREEENTRY_,RPC_ACTIVATEDESPAWNEVENT__,RPC_CLEARDESPAWNEVENT__,RPC_ISSPACESPAWNER__,RPC_SETSPACEAREA__SPACEACTIVEAREA_,RPC_GETSPACEACTIVEAREA__,RPC_SETSPAWNNAME__STRING_,RPC_GETSPAWNNAME__,};

SpaceSpawner::SpaceSpawner() : TangibleObject(DummyConstructorParameter::instance()) {
	SpaceSpawnerImplementation* _implementation = new SpaceSpawnerImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("SpaceSpawner");
}

SpaceSpawner::SpaceSpawner(DummyConstructorParameter* param) : TangibleObject(param) {
	_setClassName("SpaceSpawner");
}

SpaceSpawner::~SpaceSpawner() {
}



int SpaceSpawner::getNumberOfPlayersInRange() {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETNUMBEROFPLAYERSINRANGE__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getNumberOfPlayersInRange();
	}
}

bool SpaceSpawner::getDespawnOnNoPlayersInRange() const {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETDESPAWNONNOPLAYERSINRANGE__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->getDespawnOnNoPlayersInRange();
	}
}

void SpaceSpawner::setDespawnOnNoPlayersInRange(bool b) {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETDESPAWNONNOPLAYERSINRANGE__BOOL_);
		method.addBooleanParameter(b);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setDespawnOnNoPlayersInRange(b);
	}
}

void SpaceSpawner::notifyInsert(TreeEntry* entry) {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYINSERT__TREEENTRY_);
		method.addObjectParameter(entry);

		method.executeWithVoidReturn();
	} else {
		_implementation->notifyInsert(entry);
	}
}

void SpaceSpawner::notifyDissapear(TreeEntry* entry) {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYDISSAPEAR__TREEENTRY_);
		method.addObjectParameter(entry);

		method.executeWithVoidReturn();
	} else {
		_implementation->notifyDissapear(entry);
	}
}

void SpaceSpawner::activateDespawnEvent() {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ACTIVATEDESPAWNEVENT__);

		method.executeWithVoidReturn();
	} else {
		_implementation->activateDespawnEvent();
	}
}

void SpaceSpawner::clearDespawnEvent() {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CLEARDESPAWNEVENT__);

		method.executeWithVoidReturn();
	} else {
		_implementation->clearDespawnEvent();
	}
}

bool SpaceSpawner::isSpaceSpawner() {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISSPACESPAWNER__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isSpaceSpawner();
	}
}

void SpaceSpawner::setSpaceArea(SpaceActiveArea* area) {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSPACEAREA__SPACEACTIVEAREA_);
		method.addObjectParameter(area);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setSpaceArea(area);
	}
}

ManagedWeakReference<SpaceActiveArea* > SpaceSpawner::getSpaceActiveArea() {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSPACEACTIVEAREA__);

		return static_cast<SpaceActiveArea*>(method.executeWithObjectReturn());
	} else {
		return _implementation->getSpaceActiveArea();
	}
}

void SpaceSpawner::setSpawnName(String& name) {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSPAWNNAME__STRING_);
		method.addAsciiParameter(name);

		method.executeWithVoidReturn();
	} else {
		_implementation->setSpawnName(name);
	}
}

const String SpaceSpawner::getSpawnName() {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSPAWNNAME__);

		String _return_getSpawnName;
		method.executeWithAsciiReturn(_return_getSpawnName);
		return _return_getSpawnName;
	} else {
		return _implementation->getSpawnName();
	}
}

Vector3 SpaceSpawner::getLocationForSpawn() {
	SpaceSpawnerImplementation* _implementation = static_cast<SpaceSpawnerImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getLocationForSpawn();
	}
}

DistributedObjectServant* SpaceSpawner::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* SpaceSpawner::_getImplementationForRead() const {
	return _impl;
}

void SpaceSpawner::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	SpaceSpawnerImplementation
 */

SpaceSpawnerImplementation::SpaceSpawnerImplementation(DummyConstructorParameter* param) : TangibleObjectImplementation(param) {
	_initializeImplementation();
}


SpaceSpawnerImplementation::~SpaceSpawnerImplementation() {
}


void SpaceSpawnerImplementation::finalize() {
}

void SpaceSpawnerImplementation::_initializeImplementation() {
	_setClassHelper(SpaceSpawnerHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void SpaceSpawnerImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<SpaceSpawner*>(stub);
	TangibleObjectImplementation::_setStub(stub);
}

DistributedObjectStub* SpaceSpawnerImplementation::_getStub() {
	return _this.get();
}

SpaceSpawnerImplementation::operator const SpaceSpawner*() {
	return _this.get();
}

void SpaceSpawnerImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void SpaceSpawnerImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void SpaceSpawnerImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void SpaceSpawnerImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void SpaceSpawnerImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void SpaceSpawnerImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void SpaceSpawnerImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void SpaceSpawnerImplementation::_serializationHelperMethod() {
	TangibleObjectImplementation::_serializationHelperMethod();

	_setClassName("SpaceSpawner");

}

void SpaceSpawnerImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SpaceSpawnerImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool SpaceSpawnerImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xa8432043: //SpaceSpawner.despawnOnNoPlayersInRange
		TypeInfo<bool >::parseFromBinaryStream(&despawnOnNoPlayersInRange, stream);
		return true;

	}

	return false;
}

void SpaceSpawnerImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SpaceSpawnerImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SpaceSpawnerImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xa8432043; //SpaceSpawner.despawnOnNoPlayersInRange
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&despawnOnNoPlayersInRange, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void SpaceSpawnerImplementation::writeJSON(nlohmann::json& j) {
	TangibleObjectImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["despawnOnNoPlayersInRange"] = despawnOnNoPlayersInRange;

	j["SpaceSpawner"] = thisObject;
}

SpaceSpawnerImplementation::SpaceSpawnerImplementation() {
	_initializeImplementation();
	Reference<CloseObjectsVector*> _ref0;
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		Logger.setLoggingName("SpaceSpawner");
	Logger::setLoggingName("SpaceSpawner");
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		super.closeobjects = new CloseObjectsVector();
	TangibleObjectImplementation::closeobjects = _ref0 = new CloseObjectsVector();
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		super.closeobjects.setNoDuplicateInsertPlan();
	TangibleObjectImplementation::closeobjects->setNoDuplicateInsertPlan();
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		despawnOnNoPlayersInRange = true;
	despawnOnNoPlayersInRange = true;
}

int SpaceSpawnerImplementation::getNumberOfPlayersInRange() {
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		return numberOfPlayersInRange.get();
	return (&numberOfPlayersInRange)->get();
}

bool SpaceSpawnerImplementation::getDespawnOnNoPlayersInRange() const{
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		return despawnOnNoPlayersInRange;
	return despawnOnNoPlayersInRange;
}

void SpaceSpawnerImplementation::setDespawnOnNoPlayersInRange(bool b) {
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		despawnOnNoPlayersInRange = b;
	despawnOnNoPlayersInRange = b;
}

void SpaceSpawnerImplementation::activateDespawnEvent() {
	Reference<DespawnLairOnPlayerDisappear*> _ref0;
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		despawnEvent 
	if (despawnEvent){
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  			return;
	return;
}
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		despawnEvent = new DespawnLairOnPlayerDisappear(this);
	despawnEvent = _ref0 = new DespawnLairOnPlayerDisappear(_this.getReferenceUnsafeStaticCast());
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		despawnEvent.schedule(300000);
	despawnEvent->schedule(300000);
}

void SpaceSpawnerImplementation::clearDespawnEvent() {
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		despawnEvent.
	if (!despawnEvent)	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  			return;
	return;
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		despawnEvent.cancel();
	despawnEvent->cancel();
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		despawnEvent = null;
	despawnEvent = NULL;
}

bool SpaceSpawnerImplementation::isSpaceSpawner() {
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		return true;
	return true;
}

void SpaceSpawnerImplementation::setSpaceArea(SpaceActiveArea* area) {
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		spaceArea = area;
	spaceArea = area;
}

ManagedWeakReference<SpaceActiveArea* > SpaceSpawnerImplementation::getSpaceActiveArea() {
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		return spaceArea;
	return spaceArea;
}

void SpaceSpawnerImplementation::setSpawnName(String& name) {
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		spawnName = name;
	spawnName = name;
}

const String SpaceSpawnerImplementation::getSpawnName() {
	// server/zone/objects/tangible/space/content_infrastructure/SpaceSpawner.idl():  		return spawnName;
	return spawnName;
}

/*
 *	SpaceSpawnerAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


SpaceSpawnerAdapter::SpaceSpawnerAdapter(SpaceSpawner* obj) : TangibleObjectAdapter(obj) {
}

void SpaceSpawnerAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_GETNUMBEROFPLAYERSINRANGE__:
		{
			
			int _m_res = getNumberOfPlayersInRange();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_GETDESPAWNONNOPLAYERSINRANGE__:
		{
			
			bool _m_res = getDespawnOnNoPlayersInRange();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_SETDESPAWNONNOPLAYERSINRANGE__BOOL_:
		{
			bool b = inv->getBooleanParameter();
			
			setDespawnOnNoPlayersInRange(b);
			
		}
		break;
	case RPC_NOTIFYINSERT__TREEENTRY_:
		{
			TreeEntry* entry = static_cast<TreeEntry*>(inv->getObjectParameter());
			
			notifyInsert(entry);
			
		}
		break;
	case RPC_NOTIFYDISSAPEAR__TREEENTRY_:
		{
			TreeEntry* entry = static_cast<TreeEntry*>(inv->getObjectParameter());
			
			notifyDissapear(entry);
			
		}
		break;
	case RPC_ACTIVATEDESPAWNEVENT__:
		{
			
			activateDespawnEvent();
			
		}
		break;
	case RPC_CLEARDESPAWNEVENT__:
		{
			
			clearDespawnEvent();
			
		}
		break;
	case RPC_ISSPACESPAWNER__:
		{
			
			bool _m_res = isSpaceSpawner();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_SETSPACEAREA__SPACEACTIVEAREA_:
		{
			SpaceActiveArea* area = static_cast<SpaceActiveArea*>(inv->getObjectParameter());
			
			setSpaceArea(area);
			
		}
		break;
	case RPC_GETSPACEACTIVEAREA__:
		{
			
			DistributedObject* _m_res = getSpaceActiveArea().get();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_SETSPAWNNAME__STRING_:
		{
			String name; inv->getAsciiParameter(name);
			
			setSpawnName(name);
			
		}
		break;
	case RPC_GETSPAWNNAME__:
		{
			
			const String _m_res = getSpawnName();
			resp->insertAscii(_m_res);
		}
		break;
	default:
		TangibleObjectAdapter::invokeMethod(methid, inv);
	}
}

int SpaceSpawnerAdapter::getNumberOfPlayersInRange() {
	return (static_cast<SpaceSpawner*>(stub))->getNumberOfPlayersInRange();
}

bool SpaceSpawnerAdapter::getDespawnOnNoPlayersInRange() const {
	return (static_cast<SpaceSpawner*>(stub))->getDespawnOnNoPlayersInRange();
}

void SpaceSpawnerAdapter::setDespawnOnNoPlayersInRange(bool b) {
	(static_cast<SpaceSpawner*>(stub))->setDespawnOnNoPlayersInRange(b);
}

void SpaceSpawnerAdapter::notifyInsert(TreeEntry* entry) {
	(static_cast<SpaceSpawner*>(stub))->notifyInsert(entry);
}

void SpaceSpawnerAdapter::notifyDissapear(TreeEntry* entry) {
	(static_cast<SpaceSpawner*>(stub))->notifyDissapear(entry);
}

void SpaceSpawnerAdapter::activateDespawnEvent() {
	(static_cast<SpaceSpawner*>(stub))->activateDespawnEvent();
}

void SpaceSpawnerAdapter::clearDespawnEvent() {
	(static_cast<SpaceSpawner*>(stub))->clearDespawnEvent();
}

bool SpaceSpawnerAdapter::isSpaceSpawner() {
	return (static_cast<SpaceSpawner*>(stub))->isSpaceSpawner();
}

void SpaceSpawnerAdapter::setSpaceArea(SpaceActiveArea* area) {
	(static_cast<SpaceSpawner*>(stub))->setSpaceArea(area);
}

ManagedWeakReference<SpaceActiveArea* > SpaceSpawnerAdapter::getSpaceActiveArea() {
	return (static_cast<SpaceSpawner*>(stub))->getSpaceActiveArea();
}

void SpaceSpawnerAdapter::setSpawnName(String& name) {
	(static_cast<SpaceSpawner*>(stub))->setSpawnName(name);
}

const String SpaceSpawnerAdapter::getSpawnName() {
	return (static_cast<SpaceSpawner*>(stub))->getSpawnName();
}

/*
 *	SpaceSpawnerHelper
 */

SpaceSpawnerHelper* SpaceSpawnerHelper::staticInitializer = SpaceSpawnerHelper::instance();

SpaceSpawnerHelper::SpaceSpawnerHelper() {
	className = "SpaceSpawner";

	Core::getObjectBroker()->registerClass(className, this);
}

void SpaceSpawnerHelper::finalizeHelper() {
	SpaceSpawnerHelper::finalize();
}

DistributedObject* SpaceSpawnerHelper::instantiateObject() {
	return new SpaceSpawner(DummyConstructorParameter::instance());
}

DistributedObjectServant* SpaceSpawnerHelper::instantiateServant() {
	return new SpaceSpawnerImplementation();
}

DistributedObjectPOD* SpaceSpawnerHelper::instantiatePOD() {
	return new SpaceSpawnerPOD();
}

DistributedObjectAdapter* SpaceSpawnerHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new SpaceSpawnerAdapter(static_cast<SpaceSpawner*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	SpaceSpawnerPOD
 */

SpaceSpawnerPOD::~SpaceSpawnerPOD() {
	finalize();
}

SpaceSpawnerPOD::SpaceSpawnerPOD(void) {
	_className = "SpaceSpawner";
}


void SpaceSpawnerPOD::writeJSON(nlohmann::json& j) {
	TangibleObjectPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (despawnOnNoPlayersInRange)
		thisObject["despawnOnNoPlayersInRange"] = despawnOnNoPlayersInRange.value();

	j["SpaceSpawner"] = thisObject;
}


void SpaceSpawnerPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SpaceSpawnerPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SpaceSpawnerPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (despawnOnNoPlayersInRange) {
	_nameHashCode = 0xa8432043; //SpaceSpawner.despawnOnNoPlayersInRange
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&despawnOnNoPlayersInRange.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool SpaceSpawnerPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xa8432043: //SpaceSpawner.despawnOnNoPlayersInRange
		{
			bool _mndespawnOnNoPlayersInRange;
			TypeInfo<bool >::parseFromBinaryStream(&_mndespawnOnNoPlayersInRange, stream);
			despawnOnNoPlayersInRange = std::move(_mndespawnOnNoPlayersInRange);
		}
		return true;

	}

	return false;
}

void SpaceSpawnerPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SpaceSpawnerPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void SpaceSpawnerPOD::writeObjectCompact(ObjectOutputStream* stream) {
	TangibleObjectPOD::writeObjectCompact(stream);

	TypeInfo<bool >::toBinaryStream(&despawnOnNoPlayersInRange.value(), stream);


}

