/*
 *	autogen/server/zone/objects/tangible/deed/navicomputer/NavicomputerDeed.cpp generated by engine3 IDL compiler 0.70
 */

#include "NavicomputerDeed.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "server/zone/packets/object/ObjectMenuResponse.h"

#include "server/zone/objects/creature/CreatureObject.h"

/*
 *	NavicomputerDeedStub
 */

enum {RPC_INITIALIZETRANSIENTMEMBERS__ = 3174001362,RPC_SETCONTROLDEVICETEMPLATE__STRING_,RPC_GETCONTROLDEVICETEMPLATE__,RPC_ISNAVICOMPUTERDEEDOBJECT__};

NavicomputerDeed::NavicomputerDeed() : Deed(DummyConstructorParameter::instance()) {
	NavicomputerDeedImplementation* _implementation = new NavicomputerDeedImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("NavicomputerDeed");
}

NavicomputerDeed::NavicomputerDeed(DummyConstructorParameter* param) : Deed(param) {
	_setClassName("NavicomputerDeed");
}

NavicomputerDeed::~NavicomputerDeed() {
}



void NavicomputerDeed::initializeTransientMembers() {
	NavicomputerDeedImplementation* _implementation = static_cast<NavicomputerDeedImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INITIALIZETRANSIENTMEMBERS__);

		method.executeWithVoidReturn();
	} else {
		_implementation->initializeTransientMembers();
	}
}

void NavicomputerDeed::loadTemplateData(SharedObjectTemplate* templateData) {
	NavicomputerDeedImplementation* _implementation = static_cast<NavicomputerDeedImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->loadTemplateData(templateData);
	}
}

void NavicomputerDeed::fillAttributeList(AttributeListMessage* alm, CreatureObject* object) {
	NavicomputerDeedImplementation* _implementation = static_cast<NavicomputerDeedImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(alm, object);
	}
}

void NavicomputerDeed::fillObjectMenuResponse(ObjectMenuResponse* menuResponse, CreatureObject* player) {
	NavicomputerDeedImplementation* _implementation = static_cast<NavicomputerDeedImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillObjectMenuResponse(menuResponse, player);
	}
}

int NavicomputerDeed::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	NavicomputerDeedImplementation* _implementation = static_cast<NavicomputerDeedImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		assert((player == NULL) || player->isLockedByCurrentThread());
		return _implementation->handleObjectMenuSelect(player, selectedID);
	}
}

void NavicomputerDeed::updateCraftingValues(CraftingValues* values, bool firstUpdate) {
	NavicomputerDeedImplementation* _implementation = static_cast<NavicomputerDeedImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->updateCraftingValues(values, firstUpdate);
	}
}

void NavicomputerDeed::setControlDeviceTemplate(String& templateString) {
	NavicomputerDeedImplementation* _implementation = static_cast<NavicomputerDeedImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETCONTROLDEVICETEMPLATE__STRING_);
		method.addAsciiParameter(templateString);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setControlDeviceTemplate(templateString);
	}
}

String NavicomputerDeed::getControlDeviceTemplate() const {
	NavicomputerDeedImplementation* _implementation = static_cast<NavicomputerDeedImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETCONTROLDEVICETEMPLATE__);

		String _return_getControlDeviceTemplate;
		method.executeWithAsciiReturn(_return_getControlDeviceTemplate);
		return _return_getControlDeviceTemplate;
	} else {
		return _implementation->getControlDeviceTemplate();
	}
}

bool NavicomputerDeed::isNavicomputerDeedObject() const {
	NavicomputerDeedImplementation* _implementation = static_cast<NavicomputerDeedImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISNAVICOMPUTERDEEDOBJECT__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isNavicomputerDeedObject();
	}
}

DistributedObjectServant* NavicomputerDeed::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* NavicomputerDeed::_getImplementationForRead() const {
	return _impl;
}

void NavicomputerDeed::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	NavicomputerDeedImplementation
 */

NavicomputerDeedImplementation::NavicomputerDeedImplementation(DummyConstructorParameter* param) : DeedImplementation(param) {
	_initializeImplementation();
}


NavicomputerDeedImplementation::~NavicomputerDeedImplementation() {
}


void NavicomputerDeedImplementation::finalize() {
}

void NavicomputerDeedImplementation::_initializeImplementation() {
	_setClassHelper(NavicomputerDeedHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void NavicomputerDeedImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<NavicomputerDeed*>(stub);
	DeedImplementation::_setStub(stub);
}

DistributedObjectStub* NavicomputerDeedImplementation::_getStub() {
	return _this.get();
}

NavicomputerDeedImplementation::operator const NavicomputerDeed*() {
	return _this.get();
}

void NavicomputerDeedImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void NavicomputerDeedImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void NavicomputerDeedImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void NavicomputerDeedImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void NavicomputerDeedImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void NavicomputerDeedImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void NavicomputerDeedImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void NavicomputerDeedImplementation::_serializationHelperMethod() {
	DeedImplementation::_serializationHelperMethod();

	_setClassName("NavicomputerDeed");

}

void NavicomputerDeedImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(NavicomputerDeedImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool NavicomputerDeedImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (DeedImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x4506d18: //NavicomputerDeed.controlDeviceTemplate
		TypeInfo<String >::parseFromBinaryStream(&controlDeviceTemplate, stream);
		return true;

	case 0xdd33e406: //NavicomputerDeed.datapadTemplate
		TypeInfo<String >::parseFromBinaryStream(&datapadTemplate, stream);
		return true;

	}

	return false;
}

void NavicomputerDeedImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = NavicomputerDeedImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int NavicomputerDeedImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = DeedImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x4506d18; //NavicomputerDeed.controlDeviceTemplate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&controlDeviceTemplate, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xdd33e406; //NavicomputerDeed.datapadTemplate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&datapadTemplate, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void NavicomputerDeedImplementation::writeJSON(nlohmann::json& j) {
	DeedImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["controlDeviceTemplate"] = controlDeviceTemplate;

	thisObject["datapadTemplate"] = datapadTemplate;

	j["NavicomputerDeed"] = thisObject;
}

NavicomputerDeedImplementation::NavicomputerDeedImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/deed/navicomputer/NavicomputerDeed.idl():  		Logger.setLoggingName("NavicomputerDeed");
	Logger::setLoggingName("NavicomputerDeed");
	// server/zone/objects/tangible/deed/navicomputer/NavicomputerDeed.idl():  		controlDeviceTemplate = "";
	controlDeviceTemplate = "";
	// server/zone/objects/tangible/deed/navicomputer/NavicomputerDeed.idl():  		datapadTemplate = "";
	datapadTemplate = "";
}

void NavicomputerDeedImplementation::setControlDeviceTemplate(String& templateString) {
	// server/zone/objects/tangible/deed/navicomputer/NavicomputerDeed.idl():  		controlDeviceTemplate = templateString;
	controlDeviceTemplate = templateString;
}

String NavicomputerDeedImplementation::getControlDeviceTemplate() const{
	// server/zone/objects/tangible/deed/navicomputer/NavicomputerDeed.idl():  		return controlDeviceTemplate;
	return controlDeviceTemplate;
}

bool NavicomputerDeedImplementation::isNavicomputerDeedObject() const{
	// server/zone/objects/tangible/deed/navicomputer/NavicomputerDeed.idl():  		return true;
	return true;
}

/*
 *	NavicomputerDeedAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


NavicomputerDeedAdapter::NavicomputerDeedAdapter(NavicomputerDeed* obj) : DeedAdapter(obj) {
}

void NavicomputerDeedAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_INITIALIZETRANSIENTMEMBERS__:
		{
			
			initializeTransientMembers();
			
		}
		break;
	case RPC_SETCONTROLDEVICETEMPLATE__STRING_:
		{
			String templateString; inv->getAsciiParameter(templateString);
			
			setControlDeviceTemplate(templateString);
			
		}
		break;
	case RPC_GETCONTROLDEVICETEMPLATE__:
		{
			
			String _m_res = getControlDeviceTemplate();
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_ISNAVICOMPUTERDEEDOBJECT__:
		{
			
			bool _m_res = isNavicomputerDeedObject();
			resp->insertBoolean(_m_res);
		}
		break;
	default:
		DeedAdapter::invokeMethod(methid, inv);
	}
}

void NavicomputerDeedAdapter::initializeTransientMembers() {
	(static_cast<NavicomputerDeed*>(stub))->initializeTransientMembers();
}

void NavicomputerDeedAdapter::setControlDeviceTemplate(String& templateString) {
	(static_cast<NavicomputerDeed*>(stub))->setControlDeviceTemplate(templateString);
}

String NavicomputerDeedAdapter::getControlDeviceTemplate() const {
	return (static_cast<NavicomputerDeed*>(stub))->getControlDeviceTemplate();
}

bool NavicomputerDeedAdapter::isNavicomputerDeedObject() const {
	return (static_cast<NavicomputerDeed*>(stub))->isNavicomputerDeedObject();
}

/*
 *	NavicomputerDeedHelper
 */

NavicomputerDeedHelper* NavicomputerDeedHelper::staticInitializer = NavicomputerDeedHelper::instance();

NavicomputerDeedHelper::NavicomputerDeedHelper() {
	className = "NavicomputerDeed";

	Core::getObjectBroker()->registerClass(className, this);
}

void NavicomputerDeedHelper::finalizeHelper() {
	NavicomputerDeedHelper::finalize();
}

DistributedObject* NavicomputerDeedHelper::instantiateObject() {
	return new NavicomputerDeed(DummyConstructorParameter::instance());
}

DistributedObjectServant* NavicomputerDeedHelper::instantiateServant() {
	return new NavicomputerDeedImplementation();
}

DistributedObjectPOD* NavicomputerDeedHelper::instantiatePOD() {
	return new NavicomputerDeedPOD();
}

DistributedObjectAdapter* NavicomputerDeedHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new NavicomputerDeedAdapter(static_cast<NavicomputerDeed*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

const char LuaNavicomputerDeed::className[] = "LuaNavicomputerDeed";

Luna<LuaNavicomputerDeed>::RegType LuaNavicomputerDeed::Register[] = {
	{ "initializeTransientMembers", (int (LuaNavicomputerDeed::*)(lua_State*)) &LuaDeed::initializeTransientMembers },
	{ "loadTemplateData", (int (LuaNavicomputerDeed::*)(lua_State*)) &LuaDeed::loadTemplateData },
	{ "fillAttributeList", (int (LuaNavicomputerDeed::*)(lua_State*)) &LuaDeed::fillAttributeList },
	{ "updateCraftingValues", (int (LuaNavicomputerDeed::*)(lua_State*)) &LuaDeed::updateCraftingValues },
	{ "setGeneratedObjectTemplate", (int (LuaNavicomputerDeed::*)(lua_State*)) &LuaDeed::setGeneratedObjectTemplate },
	{ "getGeneratedObjectTemplate", (int (LuaNavicomputerDeed::*)(lua_State*)) &LuaDeed::getGeneratedObjectTemplate },
	{ "setGenerated", (int (LuaNavicomputerDeed::*)(lua_State*)) &LuaDeed::setGenerated },
	{ "isDeedObject", (int (LuaNavicomputerDeed::*)(lua_State*)) &LuaDeed::isDeedObject },
	{ "isGenerated", (int (LuaNavicomputerDeed::*)(lua_State*)) &LuaDeed::isGenerated },
	{ "_setObject", &LuaNavicomputerDeed::_setObject },
	{ "_getObject", &LuaNavicomputerDeed::_getObject },
	{ "initializeTransientMembers", &LuaNavicomputerDeed::initializeTransientMembers },
	{ "loadTemplateData", &LuaNavicomputerDeed::loadTemplateData },
	{ "fillAttributeList", &LuaNavicomputerDeed::fillAttributeList },
	{ "fillObjectMenuResponse", &LuaNavicomputerDeed::fillObjectMenuResponse },
	{ "handleObjectMenuSelect", &LuaNavicomputerDeed::handleObjectMenuSelect },
	{ "updateCraftingValues", &LuaNavicomputerDeed::updateCraftingValues },
	{ "setControlDeviceTemplate", &LuaNavicomputerDeed::setControlDeviceTemplate },
	{ "getControlDeviceTemplate", &LuaNavicomputerDeed::getControlDeviceTemplate },
	{ "isNavicomputerDeedObject", &LuaNavicomputerDeed::isNavicomputerDeedObject },
	{ 0, 0 }
};

LuaNavicomputerDeed::LuaNavicomputerDeed(lua_State *L) : LuaDeed(L) {
	realObject = static_cast<NavicomputerDeed*>(lua_touserdata(L, 1));
}

LuaNavicomputerDeed::~LuaNavicomputerDeed() {
}

int LuaNavicomputerDeed::_setObject(lua_State* L) {
	realObject = static_cast<NavicomputerDeed*>(lua_touserdata(L, -1));

	return 0;
}

int LuaNavicomputerDeed::_getObject(lua_State* L) {
	lua_pushlightuserdata(L, realObject.get());

	return 1;
}

int LuaNavicomputerDeed::initializeTransientMembers(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		realObject->initializeTransientMembers();

		return 0;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'NavicomputerDeed:initializeTransientMembers()'");
	}
	return 0;
}

int LuaNavicomputerDeed::loadTemplateData(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isuserdata(L, -1)) {
		if (parameterCount == 1) {
			SharedObjectTemplate* templateData = static_cast<SharedObjectTemplate*>(lua_touserdata(L, -1));

			realObject->loadTemplateData(templateData);

			return 0;
		} else {
			throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'NavicomputerDeed:loadTemplateData(userdata)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'NavicomputerDeed:loadTemplateData(userdata)'");
	}
	return 0;
}

int LuaNavicomputerDeed::fillAttributeList(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isuserdata(L, -1)) {
		if (lua_isuserdata(L, -2)) {
			if (parameterCount == 2) {
				AttributeListMessage* alm = static_cast<AttributeListMessage*>(lua_touserdata(L, -2));
				CreatureObject* object = static_cast<CreatureObject*>(lua_touserdata(L, -1));

				realObject->fillAttributeList(alm, object);

				return 0;
			} else {
				throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'NavicomputerDeed:fillAttributeList(userdata, userdata)'");
			}
		} else {
			throw LuaCallbackException(L, "invalid argument at 1 for lua method 'NavicomputerDeed:fillAttributeList(userdata, userdata)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'NavicomputerDeed:fillAttributeList(userdata, userdata)'");
	}
	return 0;
}

int LuaNavicomputerDeed::fillObjectMenuResponse(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isuserdata(L, -1)) {
		if (lua_isuserdata(L, -2)) {
			if (parameterCount == 2) {
				ObjectMenuResponse* menuResponse = static_cast<ObjectMenuResponse*>(lua_touserdata(L, -2));
				CreatureObject* player = static_cast<CreatureObject*>(lua_touserdata(L, -1));

				realObject->fillObjectMenuResponse(menuResponse, player);

				return 0;
			} else {
				throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'NavicomputerDeed:fillObjectMenuResponse(userdata, userdata)'");
			}
		} else {
			throw LuaCallbackException(L, "invalid argument at 1 for lua method 'NavicomputerDeed:fillObjectMenuResponse(userdata, userdata)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'NavicomputerDeed:fillObjectMenuResponse(userdata, userdata)'");
	}
	return 0;
}

int LuaNavicomputerDeed::handleObjectMenuSelect(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isnumber(L, -1)) {
		if (lua_isuserdata(L, -2)) {
			if (parameterCount == 2) {
				CreatureObject* player = static_cast<CreatureObject*>(lua_touserdata(L, -2));
				byte selectedID = lua_tointeger(L, -1);

				Locker _guard(realObject);

				int result = realObject->handleObjectMenuSelect(player, selectedID);

				lua_pushinteger(L, result);
				return 1;
			} else {
				throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'NavicomputerDeed:handleObjectMenuSelect(userdata, integer)'");
			}
		} else {
			throw LuaCallbackException(L, "invalid argument at 1 for lua method 'NavicomputerDeed:handleObjectMenuSelect(userdata, integer)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'NavicomputerDeed:handleObjectMenuSelect(userdata, integer)'");
	}
	return 0;
}

int LuaNavicomputerDeed::updateCraftingValues(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isboolean(L, -1)) {
		if (lua_isuserdata(L, -2)) {
			if (parameterCount == 2) {
				CraftingValues* values = static_cast<CraftingValues*>(lua_touserdata(L, -2));
				bool firstUpdate = lua_toboolean(L, -1);

				realObject->updateCraftingValues(values, firstUpdate);

				return 0;
			} else {
				throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'NavicomputerDeed:updateCraftingValues(userdata, boolean)'");
			}
		} else {
			throw LuaCallbackException(L, "invalid argument at 1 for lua method 'NavicomputerDeed:updateCraftingValues(userdata, boolean)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'NavicomputerDeed:updateCraftingValues(userdata, boolean)'");
	}
	return 0;
}

int LuaNavicomputerDeed::setControlDeviceTemplate(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isstring(L, -1)) {
		if (parameterCount == 1) {
			String templateString = lua_tostring(L, -1);

			Locker _guard(realObject);

			realObject->setControlDeviceTemplate(templateString);

			return 0;
		} else {
			throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'NavicomputerDeed:setControlDeviceTemplate(string)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'NavicomputerDeed:setControlDeviceTemplate(string)'");
	}
	return 0;
}

int LuaNavicomputerDeed::getControlDeviceTemplate(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		String result = realObject->getControlDeviceTemplate();

		lua_pushstring(L, result.toCharArray());
		return 1;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'NavicomputerDeed:getControlDeviceTemplate()'");
	}
	return 0;
}

int LuaNavicomputerDeed::isNavicomputerDeedObject(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		bool result = realObject->isNavicomputerDeedObject();

		lua_pushboolean(L, result);
		return 1;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'NavicomputerDeed:isNavicomputerDeedObject()'");
	}
	return 0;
}

/*
 *	NavicomputerDeedPOD
 */

NavicomputerDeedPOD::~NavicomputerDeedPOD() {
	finalize();
}

NavicomputerDeedPOD::NavicomputerDeedPOD(void) {
	_className = "NavicomputerDeed";
}


void NavicomputerDeedPOD::writeJSON(nlohmann::json& j) {
	DeedPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (controlDeviceTemplate)
		thisObject["controlDeviceTemplate"] = controlDeviceTemplate.value();

	if (datapadTemplate)
		thisObject["datapadTemplate"] = datapadTemplate.value();

	j["NavicomputerDeed"] = thisObject;
}


void NavicomputerDeedPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = NavicomputerDeedPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int NavicomputerDeedPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = DeedPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (controlDeviceTemplate) {
	_nameHashCode = 0x4506d18; //NavicomputerDeed.controlDeviceTemplate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&controlDeviceTemplate.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (datapadTemplate) {
	_nameHashCode = 0xdd33e406; //NavicomputerDeed.datapadTemplate
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&datapadTemplate.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool NavicomputerDeedPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (DeedPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x4506d18: //NavicomputerDeed.controlDeviceTemplate
		{
			String _mncontrolDeviceTemplate;
			TypeInfo<String >::parseFromBinaryStream(&_mncontrolDeviceTemplate, stream);
			controlDeviceTemplate = std::move(_mncontrolDeviceTemplate);
		}
		return true;

	case 0xdd33e406: //NavicomputerDeed.datapadTemplate
		{
			String _mndatapadTemplate;
			TypeInfo<String >::parseFromBinaryStream(&_mndatapadTemplate, stream);
			datapadTemplate = std::move(_mndatapadTemplate);
		}
		return true;

	}

	return false;
}

void NavicomputerDeedPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(NavicomputerDeedPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void NavicomputerDeedPOD::writeObjectCompact(ObjectOutputStream* stream) {
	DeedPOD::writeObjectCompact(stream);

	TypeInfo<String >::toBinaryStream(&controlDeviceTemplate.value(), stream);

	TypeInfo<String >::toBinaryStream(&datapadTemplate.value(), stream);


}

