/*
 *	autogen/server/zone/objects/ship/MultiPassengerShipObject.cpp generated by engine3 IDL compiler 0.70
 */

#include "MultiPassengerShipObject.h"

#include "server/zone/Zone.h"

/*
 *	MultiPassengerShipObjectStub
 */

MultiPassengerShipObject::MultiPassengerShipObject() : FighterShipObject(DummyConstructorParameter::instance()) {
	MultiPassengerShipObjectImplementation* _implementation = new MultiPassengerShipObjectImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("MultiPassengerShipObject");
}

MultiPassengerShipObject::MultiPassengerShipObject(DummyConstructorParameter* param) : FighterShipObject(param) {
	_setClassName("MultiPassengerShipObject");
}

MultiPassengerShipObject::~MultiPassengerShipObject() {
}



void MultiPassengerShipObject::loadTemplateData(SharedObjectTemplate* templateData) {
	MultiPassengerShipObjectImplementation* _implementation = static_cast<MultiPassengerShipObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->loadTemplateData(templateData);
	}
}

void MultiPassengerShipObject::loadTemplateData(SharedShipObjectTemplate* shipTemp) {
	MultiPassengerShipObjectImplementation* _implementation = static_cast<MultiPassengerShipObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->loadTemplateData(shipTemp);
	}
}

bool MultiPassengerShipObject::__isMultiPassengerShip() {
	MultiPassengerShipObjectImplementation* _implementation = static_cast<MultiPassengerShipObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->isMultiPassengerShip();
	}
}

MultiPassengerShipObject* MultiPassengerShipObject::__asMultiPassengerShip() {
	MultiPassengerShipObjectImplementation* _implementation = static_cast<MultiPassengerShipObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->asMultiPassengerShip();
	}
}

DistributedObjectServant* MultiPassengerShipObject::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* MultiPassengerShipObject::_getImplementationForRead() const {
	return _impl;
}

void MultiPassengerShipObject::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	MultiPassengerShipObjectImplementation
 */

MultiPassengerShipObjectImplementation::MultiPassengerShipObjectImplementation(DummyConstructorParameter* param) : FighterShipObjectImplementation(param) {
	_initializeImplementation();
}


MultiPassengerShipObjectImplementation::~MultiPassengerShipObjectImplementation() {
}


void MultiPassengerShipObjectImplementation::finalize() {
}

void MultiPassengerShipObjectImplementation::_initializeImplementation() {
	_setClassHelper(MultiPassengerShipObjectHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void MultiPassengerShipObjectImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<MultiPassengerShipObject*>(stub);
	FighterShipObjectImplementation::_setStub(stub);
}

DistributedObjectStub* MultiPassengerShipObjectImplementation::_getStub() {
	return _this.get();
}

MultiPassengerShipObjectImplementation::operator const MultiPassengerShipObject*() {
	return _this.get();
}

void MultiPassengerShipObjectImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void MultiPassengerShipObjectImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void MultiPassengerShipObjectImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void MultiPassengerShipObjectImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void MultiPassengerShipObjectImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void MultiPassengerShipObjectImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void MultiPassengerShipObjectImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void MultiPassengerShipObjectImplementation::_serializationHelperMethod() {
	FighterShipObjectImplementation::_serializationHelperMethod();

	_setClassName("MultiPassengerShipObject");

}

void MultiPassengerShipObjectImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(MultiPassengerShipObjectImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool MultiPassengerShipObjectImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (FighterShipObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void MultiPassengerShipObjectImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = MultiPassengerShipObjectImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int MultiPassengerShipObjectImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = FighterShipObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

MultiPassengerShipObjectImplementation::MultiPassengerShipObjectImplementation() {
	_initializeImplementation();
	// server/zone/objects/ship/MultiPassengerShipObject.idl():  		Logger.setLoggingName("MultiPassengerShipObject");
	Logger::setLoggingName("MultiPassengerShipObject");
}

/*
 *	MultiPassengerShipObjectAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


MultiPassengerShipObjectAdapter::MultiPassengerShipObjectAdapter(MultiPassengerShipObject* obj) : FighterShipObjectAdapter(obj) {
}

void MultiPassengerShipObjectAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		FighterShipObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	MultiPassengerShipObjectHelper
 */

MultiPassengerShipObjectHelper* MultiPassengerShipObjectHelper::staticInitializer = MultiPassengerShipObjectHelper::instance();

MultiPassengerShipObjectHelper::MultiPassengerShipObjectHelper() {
	className = "MultiPassengerShipObject";

	Core::getObjectBroker()->registerClass(className, this);
}

void MultiPassengerShipObjectHelper::finalizeHelper() {
	MultiPassengerShipObjectHelper::finalize();
}

DistributedObject* MultiPassengerShipObjectHelper::instantiateObject() {
	return new MultiPassengerShipObject(DummyConstructorParameter::instance());
}

DistributedObjectServant* MultiPassengerShipObjectHelper::instantiateServant() {
	return new MultiPassengerShipObjectImplementation();
}

DistributedObjectPOD* MultiPassengerShipObjectHelper::instantiatePOD() {
	return new MultiPassengerShipObjectPOD();
}

DistributedObjectAdapter* MultiPassengerShipObjectHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new MultiPassengerShipObjectAdapter(static_cast<MultiPassengerShipObject*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	MultiPassengerShipObjectPOD
 */

MultiPassengerShipObjectPOD::~MultiPassengerShipObjectPOD() {
	finalize();
}

MultiPassengerShipObjectPOD::MultiPassengerShipObjectPOD(void) {
	_className = "MultiPassengerShipObject";
}


void MultiPassengerShipObjectPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = MultiPassengerShipObjectPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int MultiPassengerShipObjectPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = FighterShipObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool MultiPassengerShipObjectPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (FighterShipObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void MultiPassengerShipObjectPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(MultiPassengerShipObjectPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void MultiPassengerShipObjectPOD::writeObjectCompact(ObjectOutputStream* stream) {
	FighterShipObjectPOD::writeObjectCompact(stream);


}

