/*
 *	autogen/server/zone/objects/staticobject/SpaceObject.h generated by engine3 IDL compiler 0.70
 */

#ifndef SPACEOBJECT_H_
#define SPACEOBJECT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "server/zone/objects/staticobject/StaticObject.h"

namespace server {
namespace zone {
namespace objects {
namespace staticobject {

class SpaceObject : public StaticObject {
public:
	SpaceObject();

	float getOutOfRangeDistance(unsigned long long specialRangeObjectID = 0);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	SpaceObject(DummyConstructorParameter* param);

	virtual ~SpaceObject();

	friend class SpaceObjectHelper;
};

} // namespace staticobject
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::staticobject;

namespace server {
namespace zone {
namespace objects {
namespace staticobject {

class SpaceObjectImplementation : public StaticObjectImplementation {

public:
	SpaceObjectImplementation();

	SpaceObjectImplementation(DummyConstructorParameter* param);

	virtual float getOutOfRangeDistance(unsigned long long specialRangeObjectID = 0);

	WeakReference<SpaceObject*> _this;

	operator const SpaceObject*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	virtual void writeJSON(nlohmann::json& j);
protected:
	virtual ~SpaceObjectImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class SpaceObject;
};

class SpaceObjectAdapter : public StaticObjectAdapter {
public:
	SpaceObjectAdapter(SpaceObject* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	float getOutOfRangeDistance(unsigned long long specialRangeObjectID);

};

class SpaceObjectHelper : public DistributedObjectClassHelper, public Singleton<SpaceObjectHelper> {
	static SpaceObjectHelper* staticInitializer;

public:
	SpaceObjectHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<SpaceObjectHelper>;
};

} // namespace staticobject
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::staticobject;

namespace server {
namespace zone {
namespace objects {
namespace staticobject {

class SpaceObjectPOD : public StaticObjectPOD {
public:

	SpaceObjectPOD();
	virtual void writeJSON(nlohmann::json& j);
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~SpaceObjectPOD();

};

} // namespace staticobject
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::staticobject;

#endif /*SPACEOBJECTPOD_H_*/
