/*
 *	autogen/server/zone/objects/tangible/misc/SchematicFragment.h generated by engine3 IDL compiler 0.70
 */

#ifndef SCHEMATICFRAGMENT_H_
#define SCHEMATICFRAGMENT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace scene {

class SceneObject;

class SceneObjectPOD;

} // namespace scene
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::scene;

namespace server {
namespace zone {

class Zone;

class ZonePOD;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {
namespace packets {
namespace scene {

class AttributeListMessage;

} // namespace scene
} // namespace packets
} // namespace zone
} // namespace server

using namespace server::zone::packets::scene;

namespace server {
namespace zone {

class ZoneServer;

class ZoneServerPOD;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

#include "engine/lua/Luna.h"

#include "templates/SharedObjectTemplate.h"

#include "server/zone/objects/tangible/TangibleObject.h"

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace misc {

class SchematicFragment : public TangibleObject {
public:
	SchematicFragment();

	void initializeMembers();

	/**
	 * Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
	 * @pre { templateData is a valid pointer }
	 * @post { TangibleObject members are initialized }
	 * @param templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
	 */
	void loadTemplateData(SharedObjectTemplate* templateData);

	int getTotalFragments() const;

	unsigned int getFragmentBitmask() const;

	unsigned int getTargetSchematic();

	bool isSchematicFragmentObject();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	SchematicFragment(DummyConstructorParameter* param);

	virtual ~SchematicFragment();

	friend class SchematicFragmentHelper;
};

} // namespace misc
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::misc;

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace misc {

class SchematicFragmentImplementation : public TangibleObjectImplementation {
protected:
	unsigned int targetSchematic;

	int totalFragments;

	unsigned int fragmentBitmask;

public:
	SchematicFragmentImplementation();

	SchematicFragmentImplementation(DummyConstructorParameter* param);

	void initializeMembers();

	/**
	 * Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
	 * @pre { templateData is a valid pointer }
	 * @post { TangibleObject members are initialized }
	 * @param templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
	 */
	void loadTemplateData(SharedObjectTemplate* templateData);

	int getTotalFragments() const;

	unsigned int getFragmentBitmask() const;

	unsigned int getTargetSchematic();

	bool isSchematicFragmentObject();

	WeakReference<SchematicFragment*> _this;

	operator const SchematicFragment*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	virtual void writeJSON(nlohmann::json& j);
protected:
	virtual ~SchematicFragmentImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class SchematicFragment;
};

class SchematicFragmentAdapter : public TangibleObjectAdapter {
public:
	SchematicFragmentAdapter(SchematicFragment* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void initializeMembers();

	unsigned int getTargetSchematic();

	bool isSchematicFragmentObject();

};

class SchematicFragmentHelper : public DistributedObjectClassHelper, public Singleton<SchematicFragmentHelper> {
	static SchematicFragmentHelper* staticInitializer;

public:
	SchematicFragmentHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<SchematicFragmentHelper>;
};

class LuaSchematicFragment {
public:
	static const char className[];
	static Luna<LuaSchematicFragment>::RegType Register[];

	LuaSchematicFragment(lua_State *L);
	virtual ~LuaSchematicFragment();

	int _setObject(lua_State *L);
	int _getObject(lua_State *L);
	int initializeMembers(lua_State *L);
	int loadTemplateData(lua_State *L);
	int getTotalFragments(lua_State *L);
	int getFragmentBitmask(lua_State *L);
	int getTargetSchematic(lua_State *L);
	int isSchematicFragmentObject(lua_State *L);

	Reference<SchematicFragment*> realObject;
};

} // namespace misc
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::misc;

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace misc {

class SchematicFragmentPOD : public TangibleObjectPOD {
public:
	Optional<unsigned int> targetSchematic;

	Optional<int> totalFragments;

	Optional<unsigned int> fragmentBitmask;

	String _className;
	SchematicFragmentPOD();
	virtual void writeJSON(nlohmann::json& j);
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~SchematicFragmentPOD();

};

} // namespace misc
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::misc;

#endif /*SCHEMATICFRAGMENTPOD_H_*/
