/*
 *	autogen/server/zone/objects/tangible/misc/SchematicFragment.cpp generated by engine3 IDL compiler 0.70
 */

#include "SchematicFragment.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "server/zone/Zone.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "server/zone/ZoneServer.h"

#include "server/zone/objects/creature/CreatureObject.h"

/*
 *	SchematicFragmentStub
 */

enum {RPC_INITIALIZEMEMBERS__ = 277348600,RPC_GETTARGETSCHEMATIC__,RPC_ISSCHEMATICFRAGMENTOBJECT__};

SchematicFragment::SchematicFragment() : TangibleObject(DummyConstructorParameter::instance()) {
	SchematicFragmentImplementation* _implementation = new SchematicFragmentImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("SchematicFragment");
}

SchematicFragment::SchematicFragment(DummyConstructorParameter* param) : TangibleObject(param) {
	_setClassName("SchematicFragment");
}

SchematicFragment::~SchematicFragment() {
}



void SchematicFragment::initializeMembers() {
	SchematicFragmentImplementation* _implementation = static_cast<SchematicFragmentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INITIALIZEMEMBERS__);

		method.executeWithVoidReturn();
	} else {
		_implementation->initializeMembers();
	}
}

void SchematicFragment::loadTemplateData(SharedObjectTemplate* templateData) {
	SchematicFragmentImplementation* _implementation = static_cast<SchematicFragmentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->loadTemplateData(templateData);
	}
}

int SchematicFragment::getTotalFragments() const {
	SchematicFragmentImplementation* _implementation = static_cast<SchematicFragmentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getTotalFragments();
	}
}

unsigned int SchematicFragment::getFragmentBitmask() const {
	SchematicFragmentImplementation* _implementation = static_cast<SchematicFragmentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getFragmentBitmask();
	}
}

unsigned int SchematicFragment::getTargetSchematic() {
	SchematicFragmentImplementation* _implementation = static_cast<SchematicFragmentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETTARGETSCHEMATIC__);

		return method.executeWithUnsignedIntReturn();
	} else {
		return _implementation->getTargetSchematic();
	}
}

bool SchematicFragment::isSchematicFragmentObject() {
	SchematicFragmentImplementation* _implementation = static_cast<SchematicFragmentImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISSCHEMATICFRAGMENTOBJECT__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isSchematicFragmentObject();
	}
}

DistributedObjectServant* SchematicFragment::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* SchematicFragment::_getImplementationForRead() const {
	return _impl;
}

void SchematicFragment::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	SchematicFragmentImplementation
 */

SchematicFragmentImplementation::SchematicFragmentImplementation(DummyConstructorParameter* param) : TangibleObjectImplementation(param) {
	_initializeImplementation();
}


SchematicFragmentImplementation::~SchematicFragmentImplementation() {
}


void SchematicFragmentImplementation::finalize() {
}

void SchematicFragmentImplementation::_initializeImplementation() {
	_setClassHelper(SchematicFragmentHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void SchematicFragmentImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<SchematicFragment*>(stub);
	TangibleObjectImplementation::_setStub(stub);
}

DistributedObjectStub* SchematicFragmentImplementation::_getStub() {
	return _this.get();
}

SchematicFragmentImplementation::operator const SchematicFragment*() {
	return _this.get();
}

void SchematicFragmentImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void SchematicFragmentImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void SchematicFragmentImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void SchematicFragmentImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void SchematicFragmentImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void SchematicFragmentImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void SchematicFragmentImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void SchematicFragmentImplementation::_serializationHelperMethod() {
	TangibleObjectImplementation::_serializationHelperMethod();

	_setClassName("SchematicFragment");

}

void SchematicFragmentImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SchematicFragmentImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool SchematicFragmentImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x93f21964: //SchematicFragment.targetSchematic
		TypeInfo<unsigned int >::parseFromBinaryStream(&targetSchematic, stream);
		return true;

	case 0xab66f0c8: //SchematicFragment.totalFragments
		TypeInfo<int >::parseFromBinaryStream(&totalFragments, stream);
		return true;

	case 0xbc31fb52: //SchematicFragment.fragmentBitmask
		TypeInfo<unsigned int >::parseFromBinaryStream(&fragmentBitmask, stream);
		return true;

	}

	return false;
}

void SchematicFragmentImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SchematicFragmentImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SchematicFragmentImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x93f21964; //SchematicFragment.targetSchematic
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<unsigned int >::toBinaryStream(&targetSchematic, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xab66f0c8; //SchematicFragment.totalFragments
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&totalFragments, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xbc31fb52; //SchematicFragment.fragmentBitmask
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<unsigned int >::toBinaryStream(&fragmentBitmask, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void SchematicFragmentImplementation::writeJSON(nlohmann::json& j) {
	TangibleObjectImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["targetSchematic"] = targetSchematic;

	thisObject["totalFragments"] = totalFragments;

	thisObject["fragmentBitmask"] = fragmentBitmask;

	j["SchematicFragment"] = thisObject;
}

SchematicFragmentImplementation::SchematicFragmentImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/misc/SchematicFragment.idl():  		setLoggingName("SchematicFragment");
	setLoggingName("SchematicFragment");
	// server/zone/objects/tangible/misc/SchematicFragment.idl():  		initializeMembers();
	initializeMembers();
}

void SchematicFragmentImplementation::initializeMembers() {
	// server/zone/objects/tangible/misc/SchematicFragment.idl():  		targetSchematic = 0;
	targetSchematic = 0;
	// server/zone/objects/tangible/misc/SchematicFragment.idl():  		totalFragments = 0;
	totalFragments = 0;
	// server/zone/objects/tangible/misc/SchematicFragment.idl():  		fragmentBitmask = 0;
	fragmentBitmask = 0;
}

int SchematicFragmentImplementation::getTotalFragments() const{
	// server/zone/objects/tangible/misc/SchematicFragment.idl():  		return totalFragments;
	return totalFragments;
}

unsigned int SchematicFragmentImplementation::getFragmentBitmask() const{
	// server/zone/objects/tangible/misc/SchematicFragment.idl():  		return fragmentBitmask;
	return fragmentBitmask;
}

unsigned int SchematicFragmentImplementation::getTargetSchematic() {
	// server/zone/objects/tangible/misc/SchematicFragment.idl():  		return targetSchematic;
	return targetSchematic;
}

bool SchematicFragmentImplementation::isSchematicFragmentObject() {
	// server/zone/objects/tangible/misc/SchematicFragment.idl():  		return true;
	return true;
}

/*
 *	SchematicFragmentAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


SchematicFragmentAdapter::SchematicFragmentAdapter(SchematicFragment* obj) : TangibleObjectAdapter(obj) {
}

void SchematicFragmentAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_INITIALIZEMEMBERS__:
		{
			
			initializeMembers();
			
		}
		break;
	case RPC_GETTARGETSCHEMATIC__:
		{
			
			unsigned int _m_res = getTargetSchematic();
			resp->insertInt(_m_res);
		}
		break;
	case RPC_ISSCHEMATICFRAGMENTOBJECT__:
		{
			
			bool _m_res = isSchematicFragmentObject();
			resp->insertBoolean(_m_res);
		}
		break;
	default:
		TangibleObjectAdapter::invokeMethod(methid, inv);
	}
}

void SchematicFragmentAdapter::initializeMembers() {
	(static_cast<SchematicFragment*>(stub))->initializeMembers();
}

unsigned int SchematicFragmentAdapter::getTargetSchematic() {
	return (static_cast<SchematicFragment*>(stub))->getTargetSchematic();
}

bool SchematicFragmentAdapter::isSchematicFragmentObject() {
	return (static_cast<SchematicFragment*>(stub))->isSchematicFragmentObject();
}

/*
 *	SchematicFragmentHelper
 */

SchematicFragmentHelper* SchematicFragmentHelper::staticInitializer = SchematicFragmentHelper::instance();

SchematicFragmentHelper::SchematicFragmentHelper() {
	className = "SchematicFragment";

	Core::getObjectBroker()->registerClass(className, this);
}

void SchematicFragmentHelper::finalizeHelper() {
	SchematicFragmentHelper::finalize();
}

DistributedObject* SchematicFragmentHelper::instantiateObject() {
	return new SchematicFragment(DummyConstructorParameter::instance());
}

DistributedObjectServant* SchematicFragmentHelper::instantiateServant() {
	return new SchematicFragmentImplementation();
}

DistributedObjectPOD* SchematicFragmentHelper::instantiatePOD() {
	return new SchematicFragmentPOD();
}

DistributedObjectAdapter* SchematicFragmentHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new SchematicFragmentAdapter(static_cast<SchematicFragment*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

const char LuaSchematicFragment::className[] = "LuaSchematicFragment";

Luna<LuaSchematicFragment>::RegType LuaSchematicFragment::Register[] = {
	{ "_setObject", &LuaSchematicFragment::_setObject },
	{ "_getObject", &LuaSchematicFragment::_getObject },
	{ "initializeMembers", &LuaSchematicFragment::initializeMembers },
	{ "loadTemplateData", &LuaSchematicFragment::loadTemplateData },
	{ "getTotalFragments", &LuaSchematicFragment::getTotalFragments },
	{ "getFragmentBitmask", &LuaSchematicFragment::getFragmentBitmask },
	{ "getTargetSchematic", &LuaSchematicFragment::getTargetSchematic },
	{ "isSchematicFragmentObject", &LuaSchematicFragment::isSchematicFragmentObject },
	{ 0, 0 }
};

LuaSchematicFragment::LuaSchematicFragment(lua_State *L) {
	realObject = static_cast<SchematicFragment*>(lua_touserdata(L, 1));
}

LuaSchematicFragment::~LuaSchematicFragment() {
}

int LuaSchematicFragment::_setObject(lua_State* L) {
	realObject = static_cast<SchematicFragment*>(lua_touserdata(L, -1));

	return 0;
}

int LuaSchematicFragment::_getObject(lua_State* L) {
	lua_pushlightuserdata(L, realObject.get());

	return 1;
}

int LuaSchematicFragment::initializeMembers(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		realObject->initializeMembers();

		return 0;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'SchematicFragment:initializeMembers()'");
	}
	return 0;
}

int LuaSchematicFragment::loadTemplateData(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isuserdata(L, -1)) {
		if (parameterCount == 1) {
			SharedObjectTemplate* templateData = static_cast<SharedObjectTemplate*>(lua_touserdata(L, -1));

			realObject->loadTemplateData(templateData);

			return 0;
		} else {
			throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'SchematicFragment:loadTemplateData(userdata)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'SchematicFragment:loadTemplateData(userdata)'");
	}
	return 0;
}

int LuaSchematicFragment::getTotalFragments(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		int result = realObject->getTotalFragments();

		lua_pushinteger(L, result);
		return 1;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'SchematicFragment:getTotalFragments()'");
	}
	return 0;
}

int LuaSchematicFragment::getFragmentBitmask(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		unsigned int result = realObject->getFragmentBitmask();

		lua_pushinteger(L, result);
		return 1;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'SchematicFragment:getFragmentBitmask()'");
	}
	return 0;
}

int LuaSchematicFragment::getTargetSchematic(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		unsigned int result = realObject->getTargetSchematic();

		lua_pushinteger(L, result);
		return 1;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'SchematicFragment:getTargetSchematic()'");
	}
	return 0;
}

int LuaSchematicFragment::isSchematicFragmentObject(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		bool result = realObject->isSchematicFragmentObject();

		lua_pushboolean(L, result);
		return 1;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'SchematicFragment:isSchematicFragmentObject()'");
	}
	return 0;
}

/*
 *	SchematicFragmentPOD
 */

SchematicFragmentPOD::~SchematicFragmentPOD() {
	finalize();
}

SchematicFragmentPOD::SchematicFragmentPOD(void) {
	_className = "SchematicFragment";
}


void SchematicFragmentPOD::writeJSON(nlohmann::json& j) {
	TangibleObjectPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (targetSchematic)
		thisObject["targetSchematic"] = targetSchematic.value();

	if (totalFragments)
		thisObject["totalFragments"] = totalFragments.value();

	if (fragmentBitmask)
		thisObject["fragmentBitmask"] = fragmentBitmask.value();

	j["SchematicFragment"] = thisObject;
}


void SchematicFragmentPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SchematicFragmentPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SchematicFragmentPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (targetSchematic) {
	_nameHashCode = 0x93f21964; //SchematicFragment.targetSchematic
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<unsigned int >::toBinaryStream(&targetSchematic.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (totalFragments) {
	_nameHashCode = 0xab66f0c8; //SchematicFragment.totalFragments
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&totalFragments.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (fragmentBitmask) {
	_nameHashCode = 0xbc31fb52; //SchematicFragment.fragmentBitmask
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<unsigned int >::toBinaryStream(&fragmentBitmask.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool SchematicFragmentPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x93f21964: //SchematicFragment.targetSchematic
		{
			unsigned int _mntargetSchematic;
			TypeInfo<unsigned int >::parseFromBinaryStream(&_mntargetSchematic, stream);
			targetSchematic = std::move(_mntargetSchematic);
		}
		return true;

	case 0xab66f0c8: //SchematicFragment.totalFragments
		{
			int _mntotalFragments;
			TypeInfo<int >::parseFromBinaryStream(&_mntotalFragments, stream);
			totalFragments = std::move(_mntotalFragments);
		}
		return true;

	case 0xbc31fb52: //SchematicFragment.fragmentBitmask
		{
			unsigned int _mnfragmentBitmask;
			TypeInfo<unsigned int >::parseFromBinaryStream(&_mnfragmentBitmask, stream);
			fragmentBitmask = std::move(_mnfragmentBitmask);
		}
		return true;

	}

	return false;
}

void SchematicFragmentPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SchematicFragmentPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void SchematicFragmentPOD::writeObjectCompact(ObjectOutputStream* stream) {
	TangibleObjectPOD::writeObjectCompact(stream);

	TypeInfo<unsigned int >::toBinaryStream(&targetSchematic.value(), stream);

	TypeInfo<int >::toBinaryStream(&totalFragments.value(), stream);

	TypeInfo<unsigned int >::toBinaryStream(&fragmentBitmask.value(), stream);


}

