/*
 *	autogen/server/zone/objects/tangible/tool/componentanalysis/ComponentAnalysisTool.cpp generated by engine3 IDL compiler 0.70
 */

#include "ComponentAnalysisTool.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "server/zone/packets/object/ObjectMenuResponse.h"

#include "server/zone/objects/ship/components/ShipComponent.h"

/*
 *	ComponentAnalysisToolStub
 */

enum {RPC_INITIALIZEPRIVATEDATA__ = 537953379,RPC_ISCOMPONENTANALYSISTOOL__,RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_,RPC_CANADDOBJECT__SCENEOBJECT_INT_STRING_,RPC_REVERSEENGINEER__CREATUREOBJECT_,};

ComponentAnalysisTool::ComponentAnalysisTool() : Container(DummyConstructorParameter::instance()) {
	ComponentAnalysisToolImplementation* _implementation = new ComponentAnalysisToolImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("ComponentAnalysisTool");
}

ComponentAnalysisTool::ComponentAnalysisTool(DummyConstructorParameter* param) : Container(param) {
	_setClassName("ComponentAnalysisTool");
}

ComponentAnalysisTool::~ComponentAnalysisTool() {
}



void ComponentAnalysisTool::initializePrivateData() {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INITIALIZEPRIVATEDATA__);

		method.executeWithVoidReturn();
	} else {
		_implementation->initializePrivateData();
	}
}

bool ComponentAnalysisTool::isComponentAnalysisTool() {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISCOMPONENTANALYSISTOOL__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isComponentAnalysisTool();
	}
}

void ComponentAnalysisTool::fillAttributeList(AttributeListMessage* msg, CreatureObject* object) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(msg, object);
	}
}

void ComponentAnalysisTool::fillObjectMenuResponse(ObjectMenuResponse* menuResponse, CreatureObject* player) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillObjectMenuResponse(menuResponse, player);
	}
}

int ComponentAnalysisTool::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_);
		method.addObjectParameter(player);
		method.addByteParameter(selectedID);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->handleObjectMenuSelect(player, selectedID);
	}
}

void ComponentAnalysisTool::updateCraftingValues(CraftingValues* values, bool firstUpdate) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->updateCraftingValues(values, firstUpdate);
	}
}

int ComponentAnalysisTool::canAddObject(SceneObject* object, int containmentType, String& errorDescription) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CANADDOBJECT__SCENEOBJECT_INT_STRING_);
		method.addObjectParameter(object);
		method.addSignedIntParameter(containmentType);
		method.addAsciiParameter(errorDescription);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->canAddObject(object, containmentType, errorDescription);
	}
}

int ComponentAnalysisTool::notifyObjectInserted(SceneObject* object) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->notifyObjectInserted(object);
	}
}

int ComponentAnalysisTool::notifyObjectRemoved(SceneObject* object) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->notifyObjectRemoved(object);
	}
}

void ComponentAnalysisTool::decrementCharges(CreatureObject* player) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->decrementCharges(player);
	}
}

void ComponentAnalysisTool::reverseEngineer(CreatureObject* player) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_REVERSEENGINEER__CREATUREOBJECT_);
		method.addObjectParameter(player);

		method.executeWithVoidReturn();
	} else {
		assert((player == NULL) || player->isLockedByCurrentThread());
		_implementation->reverseEngineer(player);
	}
}

void ComponentAnalysisTool::combineComponent(ShipComponent* baseComponent, ShipComponent* object) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->combineComponent(baseComponent, object);
	}
}

void ComponentAnalysisTool::applyEngineeringBonus(CreatureObject* player, SceneObject* object) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		assert((player == NULL) || player->isLockedByCurrentThread());
		_implementation->applyEngineeringBonus(player, object);
	}
}

void ComponentAnalysisTool::createSchematic(CreatureObject* player) {
	ComponentAnalysisToolImplementation* _implementation = static_cast<ComponentAnalysisToolImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		assert((player == NULL) || player->isLockedByCurrentThread());
		_implementation->createSchematic(player);
	}
}

DistributedObjectServant* ComponentAnalysisTool::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ComponentAnalysisTool::_getImplementationForRead() const {
	return _impl;
}

void ComponentAnalysisTool::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ComponentAnalysisToolImplementation
 */

ComponentAnalysisToolImplementation::ComponentAnalysisToolImplementation(DummyConstructorParameter* param) : ContainerImplementation(param) {
	_initializeImplementation();
}


ComponentAnalysisToolImplementation::~ComponentAnalysisToolImplementation() {
}


void ComponentAnalysisToolImplementation::finalize() {
}

void ComponentAnalysisToolImplementation::_initializeImplementation() {
	_setClassHelper(ComponentAnalysisToolHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ComponentAnalysisToolImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ComponentAnalysisTool*>(stub);
	ContainerImplementation::_setStub(stub);
}

DistributedObjectStub* ComponentAnalysisToolImplementation::_getStub() {
	return _this.get();
}

ComponentAnalysisToolImplementation::operator const ComponentAnalysisTool*() {
	return _this.get();
}

void ComponentAnalysisToolImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ComponentAnalysisToolImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ComponentAnalysisToolImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ComponentAnalysisToolImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ComponentAnalysisToolImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ComponentAnalysisToolImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ComponentAnalysisToolImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ComponentAnalysisToolImplementation::_serializationHelperMethod() {
	ContainerImplementation::_serializationHelperMethod();

	_setClassName("ComponentAnalysisTool");

}

void ComponentAnalysisToolImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ComponentAnalysisToolImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ComponentAnalysisToolImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ContainerImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x2d6130a1: //ComponentAnalysisTool.componentType
		TypeInfo<int >::parseFromBinaryStream(&componentType, stream);
		return true;

	case 0xd0c0c355: //ComponentAnalysisTool.engineeringLevel
		TypeInfo<int >::parseFromBinaryStream(&engineeringLevel, stream);
		return true;

	case 0x9c48db1: //ComponentAnalysisTool.chargeCounter
		TypeInfo<int >::parseFromBinaryStream(&chargeCounter, stream);
		return true;

	}

	return false;
}

void ComponentAnalysisToolImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ComponentAnalysisToolImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ComponentAnalysisToolImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ContainerImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x2d6130a1; //ComponentAnalysisTool.componentType
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&componentType, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xd0c0c355; //ComponentAnalysisTool.engineeringLevel
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&engineeringLevel, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x9c48db1; //ComponentAnalysisTool.chargeCounter
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&chargeCounter, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void ComponentAnalysisToolImplementation::writeJSON(nlohmann::json& j) {
	ContainerImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["componentType"] = componentType;

	thisObject["engineeringLevel"] = engineeringLevel;

	thisObject["chargeCounter"] = chargeCounter;

	j["ComponentAnalysisTool"] = thisObject;
}

ComponentAnalysisToolImplementation::ComponentAnalysisToolImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/tool/componentanalysis/ComponentAnalysisTool.idl():  		setLoggingName("ComponentAnalysisTool");
	setLoggingName("ComponentAnalysisTool");
	// server/zone/objects/tangible/tool/componentanalysis/ComponentAnalysisTool.idl():  		initializePrivateData();
	initializePrivateData();
}

bool ComponentAnalysisToolImplementation::isComponentAnalysisTool() {
	// server/zone/objects/tangible/tool/componentanalysis/ComponentAnalysisTool.idl():  		return true;
	return true;
}

/*
 *	ComponentAnalysisToolAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ComponentAnalysisToolAdapter::ComponentAnalysisToolAdapter(ComponentAnalysisTool* obj) : ContainerAdapter(obj) {
}

void ComponentAnalysisToolAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_INITIALIZEPRIVATEDATA__:
		{
			
			initializePrivateData();
			
		}
		break;
	case RPC_ISCOMPONENTANALYSISTOOL__:
		{
			
			bool _m_res = isComponentAnalysisTool();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			byte selectedID = inv->getByteParameter();
			
			int _m_res = handleObjectMenuSelect(player, selectedID);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_CANADDOBJECT__SCENEOBJECT_INT_STRING_:
		{
			SceneObject* object = static_cast<SceneObject*>(inv->getObjectParameter());
			int containmentType = inv->getSignedIntParameter();
			String errorDescription; inv->getAsciiParameter(errorDescription);
			
			int _m_res = canAddObject(object, containmentType, errorDescription);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_REVERSEENGINEER__CREATUREOBJECT_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			
			reverseEngineer(player);
			
		}
		break;
	default:
		ContainerAdapter::invokeMethod(methid, inv);
	}
}

void ComponentAnalysisToolAdapter::initializePrivateData() {
	(static_cast<ComponentAnalysisTool*>(stub))->initializePrivateData();
}

bool ComponentAnalysisToolAdapter::isComponentAnalysisTool() {
	return (static_cast<ComponentAnalysisTool*>(stub))->isComponentAnalysisTool();
}

int ComponentAnalysisToolAdapter::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	return (static_cast<ComponentAnalysisTool*>(stub))->handleObjectMenuSelect(player, selectedID);
}

int ComponentAnalysisToolAdapter::canAddObject(SceneObject* object, int containmentType, String& errorDescription) {
	return (static_cast<ComponentAnalysisTool*>(stub))->canAddObject(object, containmentType, errorDescription);
}

void ComponentAnalysisToolAdapter::reverseEngineer(CreatureObject* player) {
	(static_cast<ComponentAnalysisTool*>(stub))->reverseEngineer(player);
}

/*
 *	ComponentAnalysisToolHelper
 */

ComponentAnalysisToolHelper* ComponentAnalysisToolHelper::staticInitializer = ComponentAnalysisToolHelper::instance();

ComponentAnalysisToolHelper::ComponentAnalysisToolHelper() {
	className = "ComponentAnalysisTool";

	Core::getObjectBroker()->registerClass(className, this);
}

void ComponentAnalysisToolHelper::finalizeHelper() {
	ComponentAnalysisToolHelper::finalize();
}

DistributedObject* ComponentAnalysisToolHelper::instantiateObject() {
	return new ComponentAnalysisTool(DummyConstructorParameter::instance());
}

DistributedObjectServant* ComponentAnalysisToolHelper::instantiateServant() {
	return new ComponentAnalysisToolImplementation();
}

DistributedObjectPOD* ComponentAnalysisToolHelper::instantiatePOD() {
	return new ComponentAnalysisToolPOD();
}

DistributedObjectAdapter* ComponentAnalysisToolHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ComponentAnalysisToolAdapter(static_cast<ComponentAnalysisTool*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ComponentAnalysisToolPOD
 */

ComponentAnalysisToolPOD::~ComponentAnalysisToolPOD() {
	finalize();
}

ComponentAnalysisToolPOD::ComponentAnalysisToolPOD(void) {
	_className = "ComponentAnalysisTool";
}


void ComponentAnalysisToolPOD::writeJSON(nlohmann::json& j) {
	ContainerPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (componentType)
		thisObject["componentType"] = componentType.value();

	if (engineeringLevel)
		thisObject["engineeringLevel"] = engineeringLevel.value();

	if (chargeCounter)
		thisObject["chargeCounter"] = chargeCounter.value();

	j["ComponentAnalysisTool"] = thisObject;
}


void ComponentAnalysisToolPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ComponentAnalysisToolPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ComponentAnalysisToolPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ContainerPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (componentType) {
	_nameHashCode = 0x2d6130a1; //ComponentAnalysisTool.componentType
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&componentType.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (engineeringLevel) {
	_nameHashCode = 0xd0c0c355; //ComponentAnalysisTool.engineeringLevel
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&engineeringLevel.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (chargeCounter) {
	_nameHashCode = 0x9c48db1; //ComponentAnalysisTool.chargeCounter
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&chargeCounter.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ComponentAnalysisToolPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ContainerPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x2d6130a1: //ComponentAnalysisTool.componentType
		{
			int _mncomponentType;
			TypeInfo<int >::parseFromBinaryStream(&_mncomponentType, stream);
			componentType = std::move(_mncomponentType);
		}
		return true;

	case 0xd0c0c355: //ComponentAnalysisTool.engineeringLevel
		{
			int _mnengineeringLevel;
			TypeInfo<int >::parseFromBinaryStream(&_mnengineeringLevel, stream);
			engineeringLevel = std::move(_mnengineeringLevel);
		}
		return true;

	case 0x9c48db1: //ComponentAnalysisTool.chargeCounter
		{
			int _mnchargeCounter;
			TypeInfo<int >::parseFromBinaryStream(&_mnchargeCounter, stream);
			chargeCounter = std::move(_mnchargeCounter);
		}
		return true;

	}

	return false;
}

void ComponentAnalysisToolPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ComponentAnalysisToolPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ComponentAnalysisToolPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ContainerPOD::writeObjectCompact(stream);

	TypeInfo<int >::toBinaryStream(&componentType.value(), stream);

	TypeInfo<int >::toBinaryStream(&engineeringLevel.value(), stream);

	TypeInfo<int >::toBinaryStream(&chargeCounter.value(), stream);


}

