/*
 *	autogen/server/zone/managers/frs/FrsManager.h generated by engine3 IDL compiler 0.70
 */

#ifndef FRSMANAGER_H_
#define FRSMANAGER_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

namespace server {
namespace zone {

class ZoneServer;

class ZoneServerPOD;

} // namespace zone
} // namespace server

using namespace server::zone;

#include "server/zone/objects/tangible/threat/ThreatMap.h"

#include "engine/core/ManagedService.h"

#include "engine/log/Logger.h"

namespace server {
namespace zone {
namespace managers {
namespace frs {

class FrsManager : public ManagedService {
public:
	static const short COUNCIL_LIGHT = 1;

	static const short COUNCIL_DARK = 2;

	static const int ARENA_CELL = 3435643;

	FrsManager(ZoneServer* zserv);

	void initialize();

	void stop();

	void sendRankPlayerList(CreatureObject* player, int councilType, int rank);

	bool isFrsEnabled();

	void adjustFrsExperience(CreatureObject* player, int amount, bool sendSystemMessage = true);

	int calculatePvpExperienceChange(CreatureObject* attacker, CreatureObject* victim, float contribution, bool isVictim);

	bool isValidFrsBattle(CreatureObject* attacker, CreatureObject* victim);

	void handleSuddenDeathLoss(CreatureObject* player, ThreatMap* threatMap);

	bool handleDarkCouncilDeath(CreatureObject* killer, CreatureObject* victim, bool forfeit = false);

	bool handleDarkCouncilIncap(CreatureObject* killer, CreatureObject* victim);

	void handleSkillRevoked(CreatureObject* player, const String& skillName);

	bool isPlayerFightingInArena(unsigned long long playerID);

	void handleLeftArena(CreatureObject* player);

	bool isPlayerInEnclave(CreatureObject* player);

	void setPlayerRank(CreatureObject* player, int rank);

	void playerLoggedIn(CreatureObject* player);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	FrsManager(DummyConstructorParameter* param);

	virtual ~FrsManager();

	friend class FrsManagerHelper;
};

} // namespace frs
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::frs;

namespace server {
namespace zone {
namespace managers {
namespace frs {

class FrsManagerImplementation : public ManagedServiceImplementation, public Logger {
public:
	static const short COUNCIL_LIGHT = 1;

	static const short COUNCIL_DARK = 2;

	static const int ARENA_CELL = 3435643;

	FrsManagerImplementation(ZoneServer* zserv);

	FrsManagerImplementation(DummyConstructorParameter* param);

	void initialize();

	void stop();

	void sendRankPlayerList(CreatureObject* player, int councilType, int rank);

	bool isFrsEnabled();

	void adjustFrsExperience(CreatureObject* player, int amount, bool sendSystemMessage = true);

	int calculatePvpExperienceChange(CreatureObject* attacker, CreatureObject* victim, float contribution, bool isVictim);

	bool isValidFrsBattle(CreatureObject* attacker, CreatureObject* victim);

	void handleSuddenDeathLoss(CreatureObject* player, ThreatMap* threatMap);

	bool handleDarkCouncilDeath(CreatureObject* killer, CreatureObject* victim, bool forfeit = false);

	bool handleDarkCouncilIncap(CreatureObject* killer, CreatureObject* victim);

	void handleSkillRevoked(CreatureObject* player, const String& skillName);

	bool isPlayerFightingInArena(unsigned long long playerID);

	void handleLeftArena(CreatureObject* player);

	bool isPlayerInEnclave(CreatureObject* player);

	void setPlayerRank(CreatureObject* player, int rank);

	void playerLoggedIn(CreatureObject* player);

	WeakReference<FrsManager*> _this;

	operator const FrsManager*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~FrsManagerImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class FrsManager;
};

class FrsManagerAdapter : public ManagedServiceAdapter {
public:
	FrsManagerAdapter(FrsManager* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void initialize();

	void stop();

	void sendRankPlayerList(CreatureObject* player, int councilType, int rank);

	bool isFrsEnabled();

	void adjustFrsExperience(CreatureObject* player, int amount, bool sendSystemMessage);

	int calculatePvpExperienceChange(CreatureObject* attacker, CreatureObject* victim, float contribution, bool isVictim);

	bool isValidFrsBattle(CreatureObject* attacker, CreatureObject* victim);

	bool handleDarkCouncilDeath(CreatureObject* killer, CreatureObject* victim, bool forfeit);

	bool handleDarkCouncilIncap(CreatureObject* killer, CreatureObject* victim);

	void handleSkillRevoked(CreatureObject* player, const String& skillName);

	bool isPlayerFightingInArena(unsigned long long playerID);

	void handleLeftArena(CreatureObject* player);

	bool isPlayerInEnclave(CreatureObject* player);

	void setPlayerRank(CreatureObject* player, int rank);

	void playerLoggedIn(CreatureObject* player);

};

class FrsManagerHelper : public DistributedObjectClassHelper, public Singleton<FrsManagerHelper> {
	static FrsManagerHelper* staticInitializer;

public:
	FrsManagerHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<FrsManagerHelper>;
};

} // namespace frs
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::frs;

namespace server {
namespace zone {
namespace managers {
namespace frs {

class FrsManagerPOD : public ManagedServicePOD {
public:
	String _className;
	FrsManagerPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~FrsManagerPOD();

};

} // namespace frs
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::frs;

#endif /*FRSMANAGERPOD_H_*/
