/*
 *	autogen/server/zone/objects/player/sessions/NpcActorCreationSession.h generated by engine3 IDL compiler 0.70
 */

#ifndef NPCACTORCREATIONSESSION_H_
#define NPCACTORCREATIONSESSION_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

#include "server/zone/objects/scene/SessionFacadeType.h"

#include "server/zone/objects/player/sui/listbox/SuiListBox.h"

#include "server/zone/objects/player/sui/inputbox/SuiInputBox.h"

#include "server/zone/managers/vendor/VendorSelectionNode.h"

#include "server/zone/objects/tangible/deed/eventperk/EventPerkDeed.h"

#include "engine/util/u3d/Vector3.h"

#include "engine/log/Logger.h"

#include "engine/util/Facade.h"

namespace server {
namespace zone {
namespace objects {
namespace player {
namespace sessions {
namespace vendor {

class NpcActorCreationSession : public Facade {
public:
	NpcActorCreationSession(CreatureObject* player, EventPerkDeed* eventDeed, const String& nameOfZone);

	int initializeSession();

	int cancelSession();

	int clearSession();

	void setNpcActorSelection(int menuID);

	void promptNameSelection();

	void createNpcActor(const String& name);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	NpcActorCreationSession(DummyConstructorParameter* param);

	virtual ~NpcActorCreationSession();

	friend class NpcActorCreationSessionHelper;
};

} // namespace vendor
} // namespace sessions
} // namespace player
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::player::sessions::vendor;

namespace server {
namespace zone {
namespace objects {
namespace player {
namespace sessions {
namespace vendor {

class NpcActorCreationSessionImplementation : public FacadeImplementation {
protected:
	ManagedWeakReference<CreatureObject* > weakPlayer;

	ManagedWeakReference<EventPerkDeed* > weakPerkDeed;

private:
	Reference<VendorSelectionNode* > currentNode;

protected:
	ManagedReference<SuiListBox* > actorSelection;

	ManagedReference<SuiInputBox* > suiNameActor;

private:
	Vector3 actorPosition;

	String zoneName;

	String templatePath;

public:
	NpcActorCreationSessionImplementation(CreatureObject* player, EventPerkDeed* eventDeed, const String& nameOfZone);

	NpcActorCreationSessionImplementation(DummyConstructorParameter* param);

	int initializeSession();

	int cancelSession();

	int clearSession();

	void setNpcActorSelection(int menuID);

	void promptNameSelection();

	void createNpcActor(const String& name);

	WeakReference<NpcActorCreationSession*> _this;

	operator const NpcActorCreationSession*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~NpcActorCreationSessionImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class NpcActorCreationSession;
};

class NpcActorCreationSessionAdapter : public FacadeAdapter {
public:
	NpcActorCreationSessionAdapter(NpcActorCreationSession* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	int initializeSession();

	int cancelSession();

	int clearSession();

	void setNpcActorSelection(int menuID);

	void promptNameSelection();

	void createNpcActor(const String& name);

};

class NpcActorCreationSessionHelper : public DistributedObjectClassHelper, public Singleton<NpcActorCreationSessionHelper> {
	static NpcActorCreationSessionHelper* staticInitializer;

public:
	NpcActorCreationSessionHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<NpcActorCreationSessionHelper>;
};

} // namespace vendor
} // namespace sessions
} // namespace player
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::player::sessions::vendor;

namespace server {
namespace zone {
namespace objects {
namespace player {
namespace sessions {
namespace vendor {

class NpcActorCreationSessionPOD : public FacadePOD {
public:
	Optional<ManagedWeakReference<CreatureObjectPOD* >> weakPlayer;

	Optional<ManagedWeakReference<EventPerkDeedPOD* >> weakPerkDeed;

	Optional<Reference<VendorSelectionNode* >> currentNode;

	Optional<ManagedReference<SuiListBoxPOD* >> actorSelection;

	Optional<ManagedReference<SuiInputBoxPOD* >> suiNameActor;

	Optional<Vector3> actorPosition;

	Optional<String> zoneName;

	Optional<String> templatePath;

	String _className;
	NpcActorCreationSessionPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~NpcActorCreationSessionPOD();

};

} // namespace vendor
} // namespace sessions
} // namespace player
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::player::sessions::vendor;

#endif /*NPCACTORCREATIONSESSIONPOD_H_*/
