/*
 *	autogen/server/zone/objects/region/space/SpaceRegion.cpp generated by engine3 IDL compiler 0.70
 */

#include "SpaceRegion.h"

#include "server/zone/objects/scene/SceneObject.h"

/*
 *	SpaceRegionStub
 */

enum {RPC_NOTIFYLOADFROMDATABASE__ = 1156896984,RPC_ENQUEUEENTEREVENT__SCENEOBJECT_,RPC_ENQUEUEEXITEVENT__SCENEOBJECT_,RPC_NOTIFYENTER__SCENEOBJECT_,RPC_NOTIFYEXIT__SCENEOBJECT_,RPC_ISSPACEREGION__,RPC_ISSPACESPAWNAREAOBJECT__};

SpaceRegion::SpaceRegion() : SpaceActiveArea(DummyConstructorParameter::instance()) {
	SpaceRegionImplementation* _implementation = new SpaceRegionImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("SpaceRegion");
}

SpaceRegion::SpaceRegion(DummyConstructorParameter* param) : SpaceActiveArea(param) {
	_setClassName("SpaceRegion");
}

SpaceRegion::~SpaceRegion() {
}



void SpaceRegion::notifyLoadFromDatabase() {
	SpaceRegionImplementation* _implementation = static_cast<SpaceRegionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYLOADFROMDATABASE__);

		method.executeWithVoidReturn();
	} else {
		_implementation->notifyLoadFromDatabase();
	}
}

void SpaceRegion::enqueueEnterEvent(SceneObject* obj) {
	SpaceRegionImplementation* _implementation = static_cast<SpaceRegionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ENQUEUEENTEREVENT__SCENEOBJECT_);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		_implementation->enqueueEnterEvent(obj);
	}
}

void SpaceRegion::enqueueExitEvent(SceneObject* obj) {
	SpaceRegionImplementation* _implementation = static_cast<SpaceRegionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ENQUEUEEXITEVENT__SCENEOBJECT_);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		_implementation->enqueueExitEvent(obj);
	}
}

void SpaceRegion::notifyEnter(SceneObject* object) {
	SpaceRegionImplementation* _implementation = static_cast<SpaceRegionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYENTER__SCENEOBJECT_);
		method.addObjectParameter(object);

		method.executeWithVoidReturn();
	} else {
		_implementation->notifyEnter(object);
	}
}

void SpaceRegion::notifyExit(SceneObject* object) {
	SpaceRegionImplementation* _implementation = static_cast<SpaceRegionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYEXIT__SCENEOBJECT_);
		method.addObjectParameter(object);

		method.executeWithVoidReturn();
	} else {
		_implementation->notifyExit(object);
	}
}

bool SpaceRegion::isSpaceRegion() {
	SpaceRegionImplementation* _implementation = static_cast<SpaceRegionImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISSPACEREGION__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isSpaceRegion();
	}
}

bool SpaceRegion::isSpaceSpawnAreaObject() {
	SpaceRegionImplementation* _implementation = static_cast<SpaceRegionImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISSPACESPAWNAREAOBJECT__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isSpaceSpawnAreaObject();
	}
}

DistributedObjectServant* SpaceRegion::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* SpaceRegion::_getImplementationForRead() const {
	return _impl;
}

void SpaceRegion::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	SpaceRegionImplementation
 */

SpaceRegionImplementation::SpaceRegionImplementation(DummyConstructorParameter* param) : SpaceActiveAreaImplementation(param) {
	_initializeImplementation();
}


SpaceRegionImplementation::~SpaceRegionImplementation() {
}


void SpaceRegionImplementation::finalize() {
}

void SpaceRegionImplementation::_initializeImplementation() {
	_setClassHelper(SpaceRegionHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void SpaceRegionImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<SpaceRegion*>(stub);
	SpaceActiveAreaImplementation::_setStub(stub);
}

DistributedObjectStub* SpaceRegionImplementation::_getStub() {
	return _this.get();
}

SpaceRegionImplementation::operator const SpaceRegion*() {
	return _this.get();
}

void SpaceRegionImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void SpaceRegionImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void SpaceRegionImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void SpaceRegionImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void SpaceRegionImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void SpaceRegionImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void SpaceRegionImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void SpaceRegionImplementation::_serializationHelperMethod() {
	SpaceActiveAreaImplementation::_serializationHelperMethod();

	_setClassName("SpaceRegion");

}

void SpaceRegionImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SpaceRegionImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool SpaceRegionImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SpaceActiveAreaImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void SpaceRegionImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SpaceRegionImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SpaceRegionImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SpaceActiveAreaImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

void SpaceRegionImplementation::writeJSON(nlohmann::json& j) {
	SpaceActiveAreaImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
}

SpaceRegionImplementation::SpaceRegionImplementation() : SpaceActiveAreaImplementation() {
	_initializeImplementation();
}

void SpaceRegionImplementation::enqueueEnterEvent(SceneObject* obj) {
	// server/zone/objects/region/space/SpaceRegion.idl():  		notifyEnter(obj);
	notifyEnter(obj);
}

void SpaceRegionImplementation::enqueueExitEvent(SceneObject* obj) {
	// server/zone/objects/region/space/SpaceRegion.idl():  		notifyExit(obj);
	notifyExit(obj);
}

void SpaceRegionImplementation::notifyEnter(SceneObject* object) {
	// server/zone/objects/region/space/SpaceRegion.idl():  		super.notifyEnter(object);
	SpaceActiveAreaImplementation::notifyEnter(object);
}

void SpaceRegionImplementation::notifyExit(SceneObject* object) {
	// server/zone/objects/region/space/SpaceRegion.idl():  		super.notifyExit(object);
	SpaceActiveAreaImplementation::notifyExit(object);
}

bool SpaceRegionImplementation::isSpaceRegion() {
	// server/zone/objects/region/space/SpaceRegion.idl():  		return true;
	return true;
}

bool SpaceRegionImplementation::isSpaceSpawnAreaObject() {
	// server/zone/objects/region/space/SpaceRegion.idl():  		return false;
	return false;
}

/*
 *	SpaceRegionAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


SpaceRegionAdapter::SpaceRegionAdapter(SpaceRegion* obj) : SpaceActiveAreaAdapter(obj) {
}

void SpaceRegionAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_NOTIFYLOADFROMDATABASE__:
		{
			
			notifyLoadFromDatabase();
			
		}
		break;
	case RPC_ENQUEUEENTEREVENT__SCENEOBJECT_:
		{
			SceneObject* obj = static_cast<SceneObject*>(inv->getObjectParameter());
			
			enqueueEnterEvent(obj);
			
		}
		break;
	case RPC_ENQUEUEEXITEVENT__SCENEOBJECT_:
		{
			SceneObject* obj = static_cast<SceneObject*>(inv->getObjectParameter());
			
			enqueueExitEvent(obj);
			
		}
		break;
	case RPC_NOTIFYENTER__SCENEOBJECT_:
		{
			SceneObject* object = static_cast<SceneObject*>(inv->getObjectParameter());
			
			notifyEnter(object);
			
		}
		break;
	case RPC_NOTIFYEXIT__SCENEOBJECT_:
		{
			SceneObject* object = static_cast<SceneObject*>(inv->getObjectParameter());
			
			notifyExit(object);
			
		}
		break;
	case RPC_ISSPACEREGION__:
		{
			
			bool _m_res = isSpaceRegion();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_ISSPACESPAWNAREAOBJECT__:
		{
			
			bool _m_res = isSpaceSpawnAreaObject();
			resp->insertBoolean(_m_res);
		}
		break;
	default:
		SpaceActiveAreaAdapter::invokeMethod(methid, inv);
	}
}

void SpaceRegionAdapter::notifyLoadFromDatabase() {
	(static_cast<SpaceRegion*>(stub))->notifyLoadFromDatabase();
}

void SpaceRegionAdapter::enqueueEnterEvent(SceneObject* obj) {
	(static_cast<SpaceRegion*>(stub))->enqueueEnterEvent(obj);
}

void SpaceRegionAdapter::enqueueExitEvent(SceneObject* obj) {
	(static_cast<SpaceRegion*>(stub))->enqueueExitEvent(obj);
}

void SpaceRegionAdapter::notifyEnter(SceneObject* object) {
	(static_cast<SpaceRegion*>(stub))->notifyEnter(object);
}

void SpaceRegionAdapter::notifyExit(SceneObject* object) {
	(static_cast<SpaceRegion*>(stub))->notifyExit(object);
}

bool SpaceRegionAdapter::isSpaceRegion() {
	return (static_cast<SpaceRegion*>(stub))->isSpaceRegion();
}

bool SpaceRegionAdapter::isSpaceSpawnAreaObject() {
	return (static_cast<SpaceRegion*>(stub))->isSpaceSpawnAreaObject();
}

/*
 *	SpaceRegionHelper
 */

SpaceRegionHelper* SpaceRegionHelper::staticInitializer = SpaceRegionHelper::instance();

SpaceRegionHelper::SpaceRegionHelper() {
	className = "SpaceRegion";

	Core::getObjectBroker()->registerClass(className, this);
}

void SpaceRegionHelper::finalizeHelper() {
	SpaceRegionHelper::finalize();
}

DistributedObject* SpaceRegionHelper::instantiateObject() {
	return new SpaceRegion(DummyConstructorParameter::instance());
}

DistributedObjectServant* SpaceRegionHelper::instantiateServant() {
	return new SpaceRegionImplementation();
}

DistributedObjectPOD* SpaceRegionHelper::instantiatePOD() {
	return new SpaceRegionPOD();
}

DistributedObjectAdapter* SpaceRegionHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new SpaceRegionAdapter(static_cast<SpaceRegion*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	SpaceRegionPOD
 */

SpaceRegionPOD::~SpaceRegionPOD() {
	finalize();
}

SpaceRegionPOD::SpaceRegionPOD(void) {
	_className = "SpaceRegion";
}


void SpaceRegionPOD::writeJSON(nlohmann::json& j) {
	SpaceActiveAreaPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
}


void SpaceRegionPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SpaceRegionPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SpaceRegionPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SpaceActiveAreaPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool SpaceRegionPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SpaceActiveAreaPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void SpaceRegionPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SpaceRegionPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void SpaceRegionPOD::writeObjectCompact(ObjectOutputStream* stream) {
	SpaceActiveAreaPOD::writeObjectCompact(stream);


}

