/*
 *	autogen/server/zone/objects/area/space/SpaceActiveArea.h generated by engine3 IDL compiler 0.70
 */

#ifndef SPACEACTIVEAREA_H_
#define SPACEACTIVEAREA_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace scene {

class SceneObject;

class SceneObjectPOD;

} // namespace scene
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::scene;

#include "gmock/gmock.h"

#include "engine/util/u3d/Vector3.h"

#include "server/zone/objects/area/ActiveArea.h"

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace space {

class SpaceActiveArea : public ActiveArea {
public:
	SpaceActiveArea();

	void notifyEnter(SceneObject* object);

	void notifyExit(SceneObject* object);

	Vector3 getRandomPosition();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	SpaceActiveArea(DummyConstructorParameter* param);

	virtual ~SpaceActiveArea();

	friend class SpaceActiveAreaHelper;
};

} // namespace space
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::space;

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace space {

class SpaceActiveAreaImplementation : public ActiveAreaImplementation {

public:
	SpaceActiveAreaImplementation();

	SpaceActiveAreaImplementation(DummyConstructorParameter* param);

	virtual void notifyEnter(SceneObject* object);

	virtual void notifyExit(SceneObject* object);

	Vector3 getRandomPosition();

	WeakReference<SpaceActiveArea*> _this;

	operator const SpaceActiveArea*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	virtual void writeJSON(nlohmann::json& j);
protected:
	virtual ~SpaceActiveAreaImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class SpaceActiveArea;
};

class SpaceActiveAreaAdapter : public ActiveAreaAdapter {
public:
	SpaceActiveAreaAdapter(SpaceActiveArea* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void notifyEnter(SceneObject* object);

	void notifyExit(SceneObject* object);

};

class SpaceActiveAreaHelper : public DistributedObjectClassHelper, public Singleton<SpaceActiveAreaHelper> {
	static SpaceActiveAreaHelper* staticInitializer;

public:
	SpaceActiveAreaHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<SpaceActiveAreaHelper>;
};

class MockSpaceActiveArea : public SpaceActiveArea {
public:

	MOCK_METHOD1(enqueueEnterEvent,void(SceneObject* obj));
	MOCK_METHOD1(enqueueExitEvent,void(SceneObject* obj));
	MOCK_METHOD2(isInRange,bool(SceneObject* obj, float range));
	MOCK_METHOD1(getSlottedObjects,void(VectorMap<String, ManagedReference<SceneObject* > >& objects));
	MOCK_METHOD1(getDistanceTo,float(SceneObject* object));
	MOCK_METHOD1(getDistanceTo3d,float(SceneObject* object));
	MOCK_METHOD1(getDistanceTo,float(Coordinate* coordinate));
	MOCK_METHOD1(getDistanceTo3d,float(Coordinate* coordinate));
	MOCK_METHOD0(getZone,Zone*());
	MOCK_METHOD0(getZoneUnsafe,Zone*());
	MOCK_METHOD1(getSlottedObject,Reference<SceneObject* >(const String& slot));
	MOCK_METHOD0(getInventory,Reference<SceneObject* >());
	MOCK_METHOD0(getDatapad,Reference<SceneObject* >());
	MOCK_METHOD1(isFacingObject,bool(SceneObject* obj));
	MOCK_METHOD0(getParent,ManagedWeakReference<SceneObject* >());
	MOCK_METHOD0(asCreatureObject,CreatureObject*());
	MOCK_METHOD0(asAiAgent,AiAgent*());
	MOCK_METHOD0(asShipAiAgent,ShipAiAgent*());
	MOCK_METHOD0(asShipObject,ShipObject*());
	MOCK_METHOD0(asSpaceStationObject,SpaceStationObject*());
	MOCK_METHOD0(asCapitalShipObject,CapitalShipObject*());
	MOCK_METHOD0(asPobShip,PobShipObject*());
	MOCK_METHOD0(asMultiPassengerShip,MultiPassengerShipObject*());
	MOCK_METHOD0(asFighterShip,FighterShipObject*());
	MOCK_METHOD0(asTangibleObject,TangibleObject*());
	MOCK_METHOD0(getTemplateRadius,float());

};

} // namespace space
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::space;

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace space {

class SpaceActiveAreaPOD : public ActiveAreaPOD {
public:

	SpaceActiveAreaPOD();
	virtual void writeJSON(nlohmann::json& j);
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~SpaceActiveAreaPOD();

};

} // namespace space
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::space;

#endif /*SPACEACTIVEAREAPOD_H_*/
