/*
 *	autogen/server/zone/objects/area/space/SpaceActiveArea.cpp generated by engine3 IDL compiler 0.70
 */

#include "SpaceActiveArea.h"

#include "server/zone/objects/scene/SceneObject.h"

/*
 *	SpaceActiveAreaStub
 */

enum {RPC_NOTIFYENTER__SCENEOBJECT_ = 1610933816,RPC_NOTIFYEXIT__SCENEOBJECT_,};

SpaceActiveArea::SpaceActiveArea() : ActiveArea(DummyConstructorParameter::instance()) {
	SpaceActiveAreaImplementation* _implementation = new SpaceActiveAreaImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("SpaceActiveArea");
}

SpaceActiveArea::SpaceActiveArea(DummyConstructorParameter* param) : ActiveArea(param) {
	_setClassName("SpaceActiveArea");
}

SpaceActiveArea::~SpaceActiveArea() {
}



void SpaceActiveArea::notifyEnter(SceneObject* object) {
	SpaceActiveAreaImplementation* _implementation = static_cast<SpaceActiveAreaImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYENTER__SCENEOBJECT_);
		method.addObjectParameter(object);

		method.executeWithVoidReturn();
	} else {
		_implementation->notifyEnter(object);
	}
}

void SpaceActiveArea::notifyExit(SceneObject* object) {
	SpaceActiveAreaImplementation* _implementation = static_cast<SpaceActiveAreaImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYEXIT__SCENEOBJECT_);
		method.addObjectParameter(object);

		method.executeWithVoidReturn();
	} else {
		_implementation->notifyExit(object);
	}
}

Vector3 SpaceActiveArea::getRandomPosition() {
	SpaceActiveAreaImplementation* _implementation = static_cast<SpaceActiveAreaImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getRandomPosition();
	}
}

DistributedObjectServant* SpaceActiveArea::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* SpaceActiveArea::_getImplementationForRead() const {
	return _impl;
}

void SpaceActiveArea::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	SpaceActiveAreaImplementation
 */

SpaceActiveAreaImplementation::SpaceActiveAreaImplementation(DummyConstructorParameter* param) : ActiveAreaImplementation(param) {
	_initializeImplementation();
}


SpaceActiveAreaImplementation::~SpaceActiveAreaImplementation() {
}


void SpaceActiveAreaImplementation::finalize() {
}

void SpaceActiveAreaImplementation::_initializeImplementation() {
	_setClassHelper(SpaceActiveAreaHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void SpaceActiveAreaImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<SpaceActiveArea*>(stub);
	ActiveAreaImplementation::_setStub(stub);
}

DistributedObjectStub* SpaceActiveAreaImplementation::_getStub() {
	return _this.get();
}

SpaceActiveAreaImplementation::operator const SpaceActiveArea*() {
	return _this.get();
}

void SpaceActiveAreaImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void SpaceActiveAreaImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void SpaceActiveAreaImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void SpaceActiveAreaImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void SpaceActiveAreaImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void SpaceActiveAreaImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void SpaceActiveAreaImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void SpaceActiveAreaImplementation::_serializationHelperMethod() {
	ActiveAreaImplementation::_serializationHelperMethod();

	_setClassName("SpaceActiveArea");

}

void SpaceActiveAreaImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SpaceActiveAreaImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool SpaceActiveAreaImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ActiveAreaImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void SpaceActiveAreaImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SpaceActiveAreaImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SpaceActiveAreaImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ActiveAreaImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

void SpaceActiveAreaImplementation::writeJSON(nlohmann::json& j) {
	ActiveAreaImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
}

SpaceActiveAreaImplementation::SpaceActiveAreaImplementation() : ActiveAreaImplementation() {
	_initializeImplementation();
	// server/zone/objects/area/space/SpaceActiveArea.idl():  		Logger.setLoggingName("SpaceActiveArea");
	Logger::setLoggingName("SpaceActiveArea");
}

/*
 *	SpaceActiveAreaAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


SpaceActiveAreaAdapter::SpaceActiveAreaAdapter(SpaceActiveArea* obj) : ActiveAreaAdapter(obj) {
}

void SpaceActiveAreaAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_NOTIFYENTER__SCENEOBJECT_:
		{
			SceneObject* object = static_cast<SceneObject*>(inv->getObjectParameter());
			
			notifyEnter(object);
			
		}
		break;
	case RPC_NOTIFYEXIT__SCENEOBJECT_:
		{
			SceneObject* object = static_cast<SceneObject*>(inv->getObjectParameter());
			
			notifyExit(object);
			
		}
		break;
	default:
		ActiveAreaAdapter::invokeMethod(methid, inv);
	}
}

void SpaceActiveAreaAdapter::notifyEnter(SceneObject* object) {
	(static_cast<SpaceActiveArea*>(stub))->notifyEnter(object);
}

void SpaceActiveAreaAdapter::notifyExit(SceneObject* object) {
	(static_cast<SpaceActiveArea*>(stub))->notifyExit(object);
}

/*
 *	SpaceActiveAreaHelper
 */

SpaceActiveAreaHelper* SpaceActiveAreaHelper::staticInitializer = SpaceActiveAreaHelper::instance();

SpaceActiveAreaHelper::SpaceActiveAreaHelper() {
	className = "SpaceActiveArea";

	Core::getObjectBroker()->registerClass(className, this);
}

void SpaceActiveAreaHelper::finalizeHelper() {
	SpaceActiveAreaHelper::finalize();
}

DistributedObject* SpaceActiveAreaHelper::instantiateObject() {
	return new SpaceActiveArea(DummyConstructorParameter::instance());
}

DistributedObjectServant* SpaceActiveAreaHelper::instantiateServant() {
	return new SpaceActiveAreaImplementation();
}

DistributedObjectPOD* SpaceActiveAreaHelper::instantiatePOD() {
	return new SpaceActiveAreaPOD();
}

DistributedObjectAdapter* SpaceActiveAreaHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new SpaceActiveAreaAdapter(static_cast<SpaceActiveArea*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	SpaceActiveAreaPOD
 */

SpaceActiveAreaPOD::~SpaceActiveAreaPOD() {
	finalize();
}

SpaceActiveAreaPOD::SpaceActiveAreaPOD(void) {
	_className = "SpaceActiveArea";
}


void SpaceActiveAreaPOD::writeJSON(nlohmann::json& j) {
	ActiveAreaPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
}


void SpaceActiveAreaPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SpaceActiveAreaPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SpaceActiveAreaPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ActiveAreaPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool SpaceActiveAreaPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ActiveAreaPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void SpaceActiveAreaPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SpaceActiveAreaPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void SpaceActiveAreaPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ActiveAreaPOD::writeObjectCompact(stream);


}

