/*
 *	autogen/server/zone/managers/ship/SpaceSpawnObserver.h generated by engine3 IDL compiler 0.70
 */

#ifndef SPACESPAWNOBSERVER_H_
#define SPACESPAWNOBSERVER_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace scene {

class SceneObject;

class SceneObjectPOD;

} // namespace scene
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::scene;

namespace server {
namespace zone {
namespace objects {
namespace ship {
namespace ai {

class ShipAiAgent;

class ShipAiAgentPOD;

} // namespace ai
} // namespace ship
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::ship::ai;

#include "system/util/SortedVector.h"

#include "system/thread/atomic/AtomicInteger.h"

#include "server/zone/managers/creature/SpawnObserver.h"

#include "engine/core/ManagedObject.h"

#include "engine/util/Observable.h"

#include "system/thread/Mutex.h"

namespace server {
namespace zone {
namespace managers {
namespace ship {

class SpaceSpawnObserver : public SpawnObserver {
public:
	SpaceSpawnObserver();

	int notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2);

	void despawnSpawns();

	void addSpawnedShip(ShipAiAgent* shipAgent);

	void removeSpawnedShip(ShipAiAgent* shipAgent);

	void setCapitalShip(ShipAiAgent* capShip);

	bool isSpaceSpawnObserver();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	SpaceSpawnObserver(DummyConstructorParameter* param);

	virtual ~SpaceSpawnObserver();

	friend class SpaceSpawnObserverHelper;
};

} // namespace ship
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::ship;

namespace server {
namespace zone {
namespace managers {
namespace ship {

class SpaceSpawnObserverImplementation : public SpawnObserverImplementation {
protected:
	AtomicInteger shipSpawnCount;

	SortedVector<ManagedWeakReference<ShipAiAgent*> > spawnedShipAgents;

	ManagedWeakReference<ShipAiAgent* > weakCapitalShip;

	Mutex spawnMutex;

public:
	SpaceSpawnObserverImplementation();

	SpaceSpawnObserverImplementation(DummyConstructorParameter* param);

	int notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2);

	virtual void despawnSpawns();

	void addSpawnedShip(ShipAiAgent* shipAgent);

	void removeSpawnedShip(ShipAiAgent* shipAgent);

	void setCapitalShip(ShipAiAgent* capShip);

	bool isSpaceSpawnObserver();

	WeakReference<SpaceSpawnObserver*> _this;

	operator const SpaceSpawnObserver*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~SpaceSpawnObserverImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class SpaceSpawnObserver;
};

class SpaceSpawnObserverAdapter : public SpawnObserverAdapter {
public:
	SpaceSpawnObserverAdapter(SpaceSpawnObserver* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	int notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2);

	void despawnSpawns();

	void addSpawnedShip(ShipAiAgent* shipAgent);

	void removeSpawnedShip(ShipAiAgent* shipAgent);

	void setCapitalShip(ShipAiAgent* capShip);

	bool isSpaceSpawnObserver();

};

class SpaceSpawnObserverHelper : public DistributedObjectClassHelper, public Singleton<SpaceSpawnObserverHelper> {
	static SpaceSpawnObserverHelper* staticInitializer;

public:
	SpaceSpawnObserverHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<SpaceSpawnObserverHelper>;
};

} // namespace ship
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::ship;

namespace server {
namespace zone {
namespace managers {
namespace ship {

class SpaceSpawnObserverPOD : public SpawnObserverPOD {
public:
	String _className;
	SpaceSpawnObserverPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~SpaceSpawnObserverPOD();

};

} // namespace ship
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::ship;

#endif /*SPACESPAWNOBSERVERPOD_H_*/
