/*
 *	autogen/server/zone/objects/tangible/ship/interiorComponents/ShipPlasmaConduit.h generated by engine3 IDL compiler 0.70
 */

#ifndef SHIPPLASMACONDUIT_H_
#define SHIPPLASMACONDUIT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.h"

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace ship {
namespace interiorComponents {

class ShipPlasmaConduit : public ShipInteriorComponent {
public:
	ShipPlasmaConduit();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ShipPlasmaConduit(DummyConstructorParameter* param);

	virtual ~ShipPlasmaConduit();

	friend class ShipPlasmaConduitHelper;
};

} // namespace interiorComponents
} // namespace ship
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::ship::interiorComponents;

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace ship {
namespace interiorComponents {

class ShipPlasmaConduitImplementation : public ShipInteriorComponentImplementation {

public:
	ShipPlasmaConduitImplementation();

	ShipPlasmaConduitImplementation(DummyConstructorParameter* param);

	WeakReference<ShipPlasmaConduit*> _this;

	operator const ShipPlasmaConduit*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ShipPlasmaConduitImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ShipPlasmaConduit;
};

class ShipPlasmaConduitAdapter : public ShipInteriorComponentAdapter {
public:
	ShipPlasmaConduitAdapter(ShipPlasmaConduit* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class ShipPlasmaConduitHelper : public DistributedObjectClassHelper, public Singleton<ShipPlasmaConduitHelper> {
	static ShipPlasmaConduitHelper* staticInitializer;

public:
	ShipPlasmaConduitHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ShipPlasmaConduitHelper>;
};

} // namespace interiorComponents
} // namespace ship
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::ship::interiorComponents;

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace ship {
namespace interiorComponents {

class ShipPlasmaConduitPOD : public ShipInteriorComponentPOD {
public:

	ShipPlasmaConduitPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ShipPlasmaConduitPOD();

};

} // namespace interiorComponents
} // namespace ship
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::ship::interiorComponents;

#endif /*SHIPPLASMACONDUITPOD_H_*/
