/*
 *	autogen/server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.h generated by engine3 IDL compiler 0.70
 */

#ifndef SHIPINTERIORCOMPONENT_H_
#define SHIPINTERIORCOMPONENT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "server/zone/objects/tangible/TangibleObject.h"

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace ship {
namespace interiorComponents {

class ShipInteriorComponent : public TangibleObject {
public:
	ShipInteriorComponent();

	void setComponentSlot(int slot);

	void setPlasmaConduitType(int type);

	int getComponentSlot();

	int getPlasmaConduitType();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ShipInteriorComponent(DummyConstructorParameter* param);

	virtual ~ShipInteriorComponent();

	friend class ShipInteriorComponentHelper;
};

} // namespace interiorComponents
} // namespace ship
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::ship::interiorComponents;

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace ship {
namespace interiorComponents {

class ShipInteriorComponentImplementation : public TangibleObjectImplementation {
protected:
	int componentSlot;

	int plasmaConduitType;

public:
	ShipInteriorComponentImplementation();

	ShipInteriorComponentImplementation(DummyConstructorParameter* param);

	void setComponentSlot(int slot);

	void setPlasmaConduitType(int type);

	int getComponentSlot();

	int getPlasmaConduitType();

	WeakReference<ShipInteriorComponent*> _this;

	operator const ShipInteriorComponent*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	virtual void writeJSON(nlohmann::json& j);
protected:
	virtual ~ShipInteriorComponentImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ShipInteriorComponent;
};

class ShipInteriorComponentAdapter : public TangibleObjectAdapter {
public:
	ShipInteriorComponentAdapter(ShipInteriorComponent* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void setComponentSlot(int slot);

	void setPlasmaConduitType(int type);

	int getComponentSlot();

	int getPlasmaConduitType();

};

class ShipInteriorComponentHelper : public DistributedObjectClassHelper, public Singleton<ShipInteriorComponentHelper> {
	static ShipInteriorComponentHelper* staticInitializer;

public:
	ShipInteriorComponentHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ShipInteriorComponentHelper>;
};

} // namespace interiorComponents
} // namespace ship
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::ship::interiorComponents;

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace ship {
namespace interiorComponents {

class ShipInteriorComponentPOD : public TangibleObjectPOD {
public:
	Optional<int> componentSlot;

	Optional<int> plasmaConduitType;

	String _className;
	ShipInteriorComponentPOD();
	virtual void writeJSON(nlohmann::json& j);
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ShipInteriorComponentPOD();

};

} // namespace interiorComponents
} // namespace ship
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::ship::interiorComponents;

#endif /*SHIPINTERIORCOMPONENTPOD_H_*/
