/*
 *	autogen/server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.cpp generated by engine3 IDL compiler 0.70
 */

#include "ShipInteriorComponent.h"

/*
 *	ShipInteriorComponentStub
 */

enum {RPC_SETCOMPONENTSLOT__INT_ = 325666000,RPC_SETPLASMACONDUITTYPE__INT_,RPC_GETCOMPONENTSLOT__,RPC_GETPLASMACONDUITTYPE__};

ShipInteriorComponent::ShipInteriorComponent() : TangibleObject(DummyConstructorParameter::instance()) {
	ShipInteriorComponentImplementation* _implementation = new ShipInteriorComponentImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("ShipInteriorComponent");
}

ShipInteriorComponent::ShipInteriorComponent(DummyConstructorParameter* param) : TangibleObject(param) {
	_setClassName("ShipInteriorComponent");
}

ShipInteriorComponent::~ShipInteriorComponent() {
}



void ShipInteriorComponent::setComponentSlot(int slot) {
	ShipInteriorComponentImplementation* _implementation = static_cast<ShipInteriorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETCOMPONENTSLOT__INT_);
		method.addSignedIntParameter(slot);

		method.executeWithVoidReturn();
	} else {
		_implementation->setComponentSlot(slot);
	}
}

void ShipInteriorComponent::setPlasmaConduitType(int type) {
	ShipInteriorComponentImplementation* _implementation = static_cast<ShipInteriorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETPLASMACONDUITTYPE__INT_);
		method.addSignedIntParameter(type);

		method.executeWithVoidReturn();
	} else {
		_implementation->setPlasmaConduitType(type);
	}
}

int ShipInteriorComponent::getComponentSlot() {
	ShipInteriorComponentImplementation* _implementation = static_cast<ShipInteriorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETCOMPONENTSLOT__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getComponentSlot();
	}
}

int ShipInteriorComponent::getPlasmaConduitType() {
	ShipInteriorComponentImplementation* _implementation = static_cast<ShipInteriorComponentImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETPLASMACONDUITTYPE__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getPlasmaConduitType();
	}
}

DistributedObjectServant* ShipInteriorComponent::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ShipInteriorComponent::_getImplementationForRead() const {
	return _impl;
}

void ShipInteriorComponent::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ShipInteriorComponentImplementation
 */

ShipInteriorComponentImplementation::ShipInteriorComponentImplementation(DummyConstructorParameter* param) : TangibleObjectImplementation(param) {
	_initializeImplementation();
}


ShipInteriorComponentImplementation::~ShipInteriorComponentImplementation() {
}


void ShipInteriorComponentImplementation::finalize() {
}

void ShipInteriorComponentImplementation::_initializeImplementation() {
	_setClassHelper(ShipInteriorComponentHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ShipInteriorComponentImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ShipInteriorComponent*>(stub);
	TangibleObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ShipInteriorComponentImplementation::_getStub() {
	return _this.get();
}

ShipInteriorComponentImplementation::operator const ShipInteriorComponent*() {
	return _this.get();
}

void ShipInteriorComponentImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ShipInteriorComponentImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ShipInteriorComponentImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ShipInteriorComponentImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ShipInteriorComponentImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ShipInteriorComponentImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ShipInteriorComponentImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ShipInteriorComponentImplementation::_serializationHelperMethod() {
	TangibleObjectImplementation::_serializationHelperMethod();

	_setClassName("ShipInteriorComponent");

}

void ShipInteriorComponentImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipInteriorComponentImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ShipInteriorComponentImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xec789005: //ShipInteriorComponent.componentSlot
		TypeInfo<int >::parseFromBinaryStream(&componentSlot, stream);
		return true;

	case 0xe4325cf1: //ShipInteriorComponent.plasmaConduitType
		TypeInfo<int >::parseFromBinaryStream(&plasmaConduitType, stream);
		return true;

	}

	return false;
}

void ShipInteriorComponentImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipInteriorComponentImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipInteriorComponentImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xec789005; //ShipInteriorComponent.componentSlot
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&componentSlot, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xe4325cf1; //ShipInteriorComponent.plasmaConduitType
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&plasmaConduitType, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void ShipInteriorComponentImplementation::writeJSON(nlohmann::json& j) {
	TangibleObjectImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["componentSlot"] = componentSlot;

	thisObject["plasmaConduitType"] = plasmaConduitType;

	j["ShipInteriorComponent"] = thisObject;
}

ShipInteriorComponentImplementation::ShipInteriorComponentImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.idl():  		setLoggingName("ShipInteriorComponent");
	setLoggingName("ShipInteriorComponent");
	// server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.idl():  		componentSlot = -2;
	componentSlot = -2;
	// server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.idl():  		plasmaConduitType = -1;
	plasmaConduitType = -1;
}

void ShipInteriorComponentImplementation::setComponentSlot(int slot) {
	// server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.idl():  		componentSlot = slot;
	componentSlot = slot;
}

void ShipInteriorComponentImplementation::setPlasmaConduitType(int type) {
	// server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.idl():  		plasmaConduitType = type;
	plasmaConduitType = type;
}

int ShipInteriorComponentImplementation::getComponentSlot() {
	// server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.idl():  		return componentSlot;
	return componentSlot;
}

int ShipInteriorComponentImplementation::getPlasmaConduitType() {
	// server/zone/objects/tangible/ship/interiorComponents/ShipInteriorComponent.idl():  		return plasmaConduitType;
	return plasmaConduitType;
}

/*
 *	ShipInteriorComponentAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ShipInteriorComponentAdapter::ShipInteriorComponentAdapter(ShipInteriorComponent* obj) : TangibleObjectAdapter(obj) {
}

void ShipInteriorComponentAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_SETCOMPONENTSLOT__INT_:
		{
			int slot = inv->getSignedIntParameter();
			
			setComponentSlot(slot);
			
		}
		break;
	case RPC_SETPLASMACONDUITTYPE__INT_:
		{
			int type = inv->getSignedIntParameter();
			
			setPlasmaConduitType(type);
			
		}
		break;
	case RPC_GETCOMPONENTSLOT__:
		{
			
			int _m_res = getComponentSlot();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_GETPLASMACONDUITTYPE__:
		{
			
			int _m_res = getPlasmaConduitType();
			resp->insertSignedInt(_m_res);
		}
		break;
	default:
		TangibleObjectAdapter::invokeMethod(methid, inv);
	}
}

void ShipInteriorComponentAdapter::setComponentSlot(int slot) {
	(static_cast<ShipInteriorComponent*>(stub))->setComponentSlot(slot);
}

void ShipInteriorComponentAdapter::setPlasmaConduitType(int type) {
	(static_cast<ShipInteriorComponent*>(stub))->setPlasmaConduitType(type);
}

int ShipInteriorComponentAdapter::getComponentSlot() {
	return (static_cast<ShipInteriorComponent*>(stub))->getComponentSlot();
}

int ShipInteriorComponentAdapter::getPlasmaConduitType() {
	return (static_cast<ShipInteriorComponent*>(stub))->getPlasmaConduitType();
}

/*
 *	ShipInteriorComponentHelper
 */

ShipInteriorComponentHelper* ShipInteriorComponentHelper::staticInitializer = ShipInteriorComponentHelper::instance();

ShipInteriorComponentHelper::ShipInteriorComponentHelper() {
	className = "ShipInteriorComponent";

	Core::getObjectBroker()->registerClass(className, this);
}

void ShipInteriorComponentHelper::finalizeHelper() {
	ShipInteriorComponentHelper::finalize();
}

DistributedObject* ShipInteriorComponentHelper::instantiateObject() {
	return new ShipInteriorComponent(DummyConstructorParameter::instance());
}

DistributedObjectServant* ShipInteriorComponentHelper::instantiateServant() {
	return new ShipInteriorComponentImplementation();
}

DistributedObjectPOD* ShipInteriorComponentHelper::instantiatePOD() {
	return new ShipInteriorComponentPOD();
}

DistributedObjectAdapter* ShipInteriorComponentHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ShipInteriorComponentAdapter(static_cast<ShipInteriorComponent*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ShipInteriorComponentPOD
 */

ShipInteriorComponentPOD::~ShipInteriorComponentPOD() {
	finalize();
}

ShipInteriorComponentPOD::ShipInteriorComponentPOD(void) {
	_className = "ShipInteriorComponent";
}


void ShipInteriorComponentPOD::writeJSON(nlohmann::json& j) {
	TangibleObjectPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (componentSlot)
		thisObject["componentSlot"] = componentSlot.value();

	if (plasmaConduitType)
		thisObject["plasmaConduitType"] = plasmaConduitType.value();

	j["ShipInteriorComponent"] = thisObject;
}


void ShipInteriorComponentPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipInteriorComponentPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipInteriorComponentPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (componentSlot) {
	_nameHashCode = 0xec789005; //ShipInteriorComponent.componentSlot
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&componentSlot.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (plasmaConduitType) {
	_nameHashCode = 0xe4325cf1; //ShipInteriorComponent.plasmaConduitType
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&plasmaConduitType.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ShipInteriorComponentPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xec789005: //ShipInteriorComponent.componentSlot
		{
			int _mncomponentSlot;
			TypeInfo<int >::parseFromBinaryStream(&_mncomponentSlot, stream);
			componentSlot = std::move(_mncomponentSlot);
		}
		return true;

	case 0xe4325cf1: //ShipInteriorComponent.plasmaConduitType
		{
			int _mnplasmaConduitType;
			TypeInfo<int >::parseFromBinaryStream(&_mnplasmaConduitType, stream);
			plasmaConduitType = std::move(_mnplasmaConduitType);
		}
		return true;

	}

	return false;
}

void ShipInteriorComponentPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipInteriorComponentPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ShipInteriorComponentPOD::writeObjectCompact(ObjectOutputStream* stream) {
	TangibleObjectPOD::writeObjectCompact(stream);

	TypeInfo<int >::toBinaryStream(&componentSlot.value(), stream);

	TypeInfo<int >::toBinaryStream(&plasmaConduitType.value(), stream);


}

