/*
 *	autogen/server/zone/objects/installation/TurretObject.cpp generated by engine3 IDL compiler 0.70
 */

#include "TurretObject.h"

#include "server/zone/objects/tangible/weapon/WeaponObject.h"

/*
 *	TurretObjectStub
 */

enum {RPC_INITIALIZETRANSIENTMEMBERS__ = 628943437,RPC_CREATECHILDOBJECTS__,RPC_GETARMORRESISTREDUCTION__FLOAT_,RPC_GETKINETIC__,RPC_GETENERGY__,RPC_GETELECTRICITY__,RPC_GETSTUN__,RPC_GETBLAST__,RPC_GETHEAT__,RPC_GETCOLD__,RPC_GETACID__,RPC_GETLIGHTSABER__,RPC_SETTURRETWEAPON__WEAPONOBJECT_,RPC_SETARMORRATING__INT_,RPC_SETKINETIC__FLOAT_,RPC_SETENERGY__FLOAT_,RPC_SETELECTRICITY__FLOAT_,RPC_SETSTUN__FLOAT_,RPC_SETBLAST__FLOAT_,RPC_SETHEAT__FLOAT_,RPC_SETCOLD__FLOAT_,RPC_SETACID__FLOAT_,RPC_SETLIGHTSABER__FLOAT_,RPC_SETCHANCEHIT__FLOAT_,RPC_GETTURRETWEAPON__,RPC_GETARMORRATING__,RPC_GETCHANCEHIT__};

TurretObject::TurretObject() : InstallationObject(DummyConstructorParameter::instance()) {
	TurretObjectImplementation* _implementation = new TurretObjectImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("TurretObject");
}

TurretObject::TurretObject(DummyConstructorParameter* param) : InstallationObject(param) {
	_setClassName("TurretObject");
}

TurretObject::~TurretObject() {
}



void TurretObject::initializeTransientMembers() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INITIALIZETRANSIENTMEMBERS__);

		method.executeWithVoidReturn();
	} else {
		_implementation->initializeTransientMembers();
	}
}

void TurretObject::loadTemplateData(SharedObjectTemplate* templateData) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->loadTemplateData(templateData);
	}
}

void TurretObject::createChildObjects() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CREATECHILDOBJECTS__);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->createChildObjects();
	}
}

void TurretObject::fillAttributeList(AttributeListMessage* alm, CreatureObject* player) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(alm, player);
	}
}

float TurretObject::getArmorResistReduction(float value) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETARMORRESISTREDUCTION__FLOAT_);
		method.addFloatParameter(value);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getArmorResistReduction(value);
	}
}

float TurretObject::getKinetic() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETKINETIC__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getKinetic();
	}
}

float TurretObject::getEnergy() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETENERGY__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getEnergy();
	}
}

float TurretObject::getElectricity() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETELECTRICITY__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getElectricity();
	}
}

float TurretObject::getStun() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSTUN__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getStun();
	}
}

float TurretObject::getBlast() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETBLAST__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getBlast();
	}
}

float TurretObject::getHeat() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETHEAT__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getHeat();
	}
}

float TurretObject::getCold() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETCOLD__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getCold();
	}
}

float TurretObject::getAcid() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETACID__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getAcid();
	}
}

float TurretObject::getLightSaber() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETLIGHTSABER__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getLightSaber();
	}
}

void TurretObject::setTurretWeapon(WeaponObject* turretWeapon) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETTURRETWEAPON__WEAPONOBJECT_);
		method.addObjectParameter(turretWeapon);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setTurretWeapon(turretWeapon);
	}
}

void TurretObject::setArmorRating(unsigned int rating) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETARMORRATING__INT_);
		method.addUnsignedIntParameter(rating);

		method.executeWithVoidReturn();
	} else {
		_implementation->setArmorRating(rating);
	}
}

void TurretObject::setKinetic(float resist) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETKINETIC__FLOAT_);
		method.addFloatParameter(resist);

		method.executeWithVoidReturn();
	} else {
		_implementation->setKinetic(resist);
	}
}

void TurretObject::setEnergy(float resist) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETENERGY__FLOAT_);
		method.addFloatParameter(resist);

		method.executeWithVoidReturn();
	} else {
		_implementation->setEnergy(resist);
	}
}

void TurretObject::setElectricity(float resist) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETELECTRICITY__FLOAT_);
		method.addFloatParameter(resist);

		method.executeWithVoidReturn();
	} else {
		_implementation->setElectricity(resist);
	}
}

void TurretObject::setStun(float resist) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSTUN__FLOAT_);
		method.addFloatParameter(resist);

		method.executeWithVoidReturn();
	} else {
		_implementation->setStun(resist);
	}
}

void TurretObject::setBlast(float resist) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETBLAST__FLOAT_);
		method.addFloatParameter(resist);

		method.executeWithVoidReturn();
	} else {
		_implementation->setBlast(resist);
	}
}

void TurretObject::setHeat(float resist) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETHEAT__FLOAT_);
		method.addFloatParameter(resist);

		method.executeWithVoidReturn();
	} else {
		_implementation->setHeat(resist);
	}
}

void TurretObject::setCold(float resist) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETCOLD__FLOAT_);
		method.addFloatParameter(resist);

		method.executeWithVoidReturn();
	} else {
		_implementation->setCold(resist);
	}
}

void TurretObject::setAcid(float resist) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETACID__FLOAT_);
		method.addFloatParameter(resist);

		method.executeWithVoidReturn();
	} else {
		_implementation->setAcid(resist);
	}
}

void TurretObject::setLightSaber(float resist) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETLIGHTSABER__FLOAT_);
		method.addFloatParameter(resist);

		method.executeWithVoidReturn();
	} else {
		_implementation->setLightSaber(resist);
	}
}

void TurretObject::setChanceHit(float chance) {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETCHANCEHIT__FLOAT_);
		method.addFloatParameter(chance);

		method.executeWithVoidReturn();
	} else {
		_implementation->setChanceHit(chance);
	}
}

WeaponObject* TurretObject::getTurretWeapon() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETTURRETWEAPON__);

		return static_cast<WeaponObject*>(method.executeWithObjectReturn());
	} else {
		return _implementation->getTurretWeapon();
	}
}

unsigned int TurretObject::getArmorRating() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETARMORRATING__);

		return method.executeWithUnsignedIntReturn();
	} else {
		return _implementation->getArmorRating();
	}
}

float TurretObject::getChanceHit() {
	TurretObjectImplementation* _implementation = static_cast<TurretObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETCHANCEHIT__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getChanceHit();
	}
}

DistributedObjectServant* TurretObject::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* TurretObject::_getImplementationForRead() const {
	return _impl;
}

void TurretObject::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	TurretObjectImplementation
 */

TurretObjectImplementation::TurretObjectImplementation(DummyConstructorParameter* param) : InstallationObjectImplementation(param) {
	_initializeImplementation();
}


TurretObjectImplementation::~TurretObjectImplementation() {
}


void TurretObjectImplementation::finalize() {
}

void TurretObjectImplementation::_initializeImplementation() {
	_setClassHelper(TurretObjectHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void TurretObjectImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<TurretObject*>(stub);
	InstallationObjectImplementation::_setStub(stub);
}

DistributedObjectStub* TurretObjectImplementation::_getStub() {
	return _this.get();
}

TurretObjectImplementation::operator const TurretObject*() {
	return _this.get();
}

void TurretObjectImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void TurretObjectImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void TurretObjectImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void TurretObjectImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void TurretObjectImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void TurretObjectImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void TurretObjectImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void TurretObjectImplementation::_serializationHelperMethod() {
	InstallationObjectImplementation::_serializationHelperMethod();

	_setClassName("TurretObject");

}

void TurretObjectImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(TurretObjectImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool TurretObjectImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (InstallationObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x13b63a0e: //TurretObject.armorRating
		TypeInfo<unsigned int >::parseFromBinaryStream(&armorRating, stream);
		return true;

	case 0xa4a57959: //TurretObject.kinetic
		TypeInfo<float >::parseFromBinaryStream(&kinetic, stream);
		return true;

	case 0x5123eb81: //TurretObject.energy
		TypeInfo<float >::parseFromBinaryStream(&energy, stream);
		return true;

	case 0xd117c7ae: //TurretObject.electricity
		TypeInfo<float >::parseFromBinaryStream(&electricity, stream);
		return true;

	case 0x162201b3: //TurretObject.stun
		TypeInfo<float >::parseFromBinaryStream(&stun, stream);
		return true;

	case 0xe53c90c2: //TurretObject.blast
		TypeInfo<float >::parseFromBinaryStream(&blast, stream);
		return true;

	case 0x5217d59f: //TurretObject.heat
		TypeInfo<float >::parseFromBinaryStream(&heat, stream);
		return true;

	case 0x979aba9a: //TurretObject.cold
		TypeInfo<float >::parseFromBinaryStream(&cold, stream);
		return true;

	case 0xb51aa412: //TurretObject.acid
		TypeInfo<float >::parseFromBinaryStream(&acid, stream);
		return true;

	case 0x8fe072cd: //TurretObject.lightsaber
		TypeInfo<float >::parseFromBinaryStream(&lightsaber, stream);
		return true;

	case 0x3de4f7f8: //TurretObject.chanceHit
		TypeInfo<float >::parseFromBinaryStream(&chanceHit, stream);
		return true;

	}

	return false;
}

void TurretObjectImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = TurretObjectImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int TurretObjectImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = InstallationObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x13b63a0e; //TurretObject.armorRating
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<unsigned int >::toBinaryStream(&armorRating, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xa4a57959; //TurretObject.kinetic
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&kinetic, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x5123eb81; //TurretObject.energy
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&energy, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xd117c7ae; //TurretObject.electricity
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&electricity, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x162201b3; //TurretObject.stun
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&stun, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xe53c90c2; //TurretObject.blast
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&blast, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x5217d59f; //TurretObject.heat
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&heat, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x979aba9a; //TurretObject.cold
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&cold, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xb51aa412; //TurretObject.acid
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&acid, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x8fe072cd; //TurretObject.lightsaber
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&lightsaber, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x3de4f7f8; //TurretObject.chanceHit
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&chanceHit, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void TurretObjectImplementation::writeJSON(nlohmann::json& j) {
	InstallationObjectImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["armorRating"] = armorRating;

	thisObject["kinetic"] = kinetic;

	thisObject["energy"] = energy;

	thisObject["electricity"] = electricity;

	thisObject["stun"] = stun;

	thisObject["blast"] = blast;

	thisObject["heat"] = heat;

	thisObject["cold"] = cold;

	thisObject["acid"] = acid;

	thisObject["lightsaber"] = lightsaber;

	thisObject["chanceHit"] = chanceHit;

	j["TurretObject"] = thisObject;
}

TurretObjectImplementation::TurretObjectImplementation() {
	_initializeImplementation();
	// server/zone/objects/installation/TurretObject.idl():  		weapon = null;
	weapon = NULL;
	// server/zone/objects/installation/TurretObject.idl():  		armorRating = 0;
	armorRating = 0;
	// server/zone/objects/installation/TurretObject.idl():  		kinetic = -1.f;
	kinetic = -1.f;
	// server/zone/objects/installation/TurretObject.idl():  		energy = -1.f;
	energy = -1.f;
	// server/zone/objects/installation/TurretObject.idl():  		electricity = -1.f;
	electricity = -1.f;
	// server/zone/objects/installation/TurretObject.idl():  		stun = -1.f;
	stun = -1.f;
	// server/zone/objects/installation/TurretObject.idl():  		blast = -1.f;
	blast = -1.f;
	// server/zone/objects/installation/TurretObject.idl():  		heat = -1.f;
	heat = -1.f;
	// server/zone/objects/installation/TurretObject.idl():  		cold = -1.f;
	cold = -1.f;
	// server/zone/objects/installation/TurretObject.idl():  		acid = -1.f;
	acid = -1.f;
	// server/zone/objects/installation/TurretObject.idl():  		lightsaber = -1.f;
	lightsaber = -1.f;
	// server/zone/objects/installation/TurretObject.idl():  		chanceHit = 1.f;
	chanceHit = 1.f;
}

void TurretObjectImplementation::setTurretWeapon(WeaponObject* turretWeapon) {
	// server/zone/objects/installation/TurretObject.idl():  		weapon = turretWeapon;
	weapon = turretWeapon;
}

void TurretObjectImplementation::setArmorRating(unsigned int rating) {
	// server/zone/objects/installation/TurretObject.idl():  		armorRating = rating;
	armorRating = rating;
}

void TurretObjectImplementation::setKinetic(float resist) {
	// server/zone/objects/installation/TurretObject.idl():  		kinetic = resist;
	kinetic = resist;
}

void TurretObjectImplementation::setEnergy(float resist) {
	// server/zone/objects/installation/TurretObject.idl():  		energy = resist;
	energy = resist;
}

void TurretObjectImplementation::setElectricity(float resist) {
	// server/zone/objects/installation/TurretObject.idl():  		electricity = resist;
	electricity = resist;
}

void TurretObjectImplementation::setStun(float resist) {
	// server/zone/objects/installation/TurretObject.idl():  		stun = resist;
	stun = resist;
}

void TurretObjectImplementation::setBlast(float resist) {
	// server/zone/objects/installation/TurretObject.idl():  		blast = resist;
	blast = resist;
}

void TurretObjectImplementation::setHeat(float resist) {
	// server/zone/objects/installation/TurretObject.idl():  		heat = resist;
	heat = resist;
}

void TurretObjectImplementation::setCold(float resist) {
	// server/zone/objects/installation/TurretObject.idl():  		cold = resist;
	cold = resist;
}

void TurretObjectImplementation::setAcid(float resist) {
	// server/zone/objects/installation/TurretObject.idl():  		acid = resist;
	acid = resist;
}

void TurretObjectImplementation::setLightSaber(float resist) {
	// server/zone/objects/installation/TurretObject.idl():  		lightsaber = resist;
	lightsaber = resist;
}

void TurretObjectImplementation::setChanceHit(float chance) {
	// server/zone/objects/installation/TurretObject.idl():  		chanceHit = chance;
	chanceHit = chance;
}

WeaponObject* TurretObjectImplementation::getTurretWeapon() {
	// server/zone/objects/installation/TurretObject.idl():  		return weapon;
	return weapon;
}

unsigned int TurretObjectImplementation::getArmorRating() {
	// server/zone/objects/installation/TurretObject.idl():  		return armorRating;
	return armorRating;
}

float TurretObjectImplementation::getChanceHit() {
	// server/zone/objects/installation/TurretObject.idl():  		return chanceHit;
	return chanceHit;
}

/*
 *	TurretObjectAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


TurretObjectAdapter::TurretObjectAdapter(TurretObject* obj) : InstallationObjectAdapter(obj) {
}

void TurretObjectAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_INITIALIZETRANSIENTMEMBERS__:
		{
			
			initializeTransientMembers();
			
		}
		break;
	case RPC_CREATECHILDOBJECTS__:
		{
			
			createChildObjects();
			
		}
		break;
	case RPC_GETARMORRESISTREDUCTION__FLOAT_:
		{
			float value = inv->getFloatParameter();
			
			float _m_res = getArmorResistReduction(value);
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETKINETIC__:
		{
			
			float _m_res = getKinetic();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETENERGY__:
		{
			
			float _m_res = getEnergy();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETELECTRICITY__:
		{
			
			float _m_res = getElectricity();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETSTUN__:
		{
			
			float _m_res = getStun();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETBLAST__:
		{
			
			float _m_res = getBlast();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETHEAT__:
		{
			
			float _m_res = getHeat();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETCOLD__:
		{
			
			float _m_res = getCold();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETACID__:
		{
			
			float _m_res = getAcid();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETLIGHTSABER__:
		{
			
			float _m_res = getLightSaber();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_SETTURRETWEAPON__WEAPONOBJECT_:
		{
			WeaponObject* turretWeapon = static_cast<WeaponObject*>(inv->getObjectParameter());
			
			setTurretWeapon(turretWeapon);
			
		}
		break;
	case RPC_SETARMORRATING__INT_:
		{
			unsigned int rating = inv->getUnsignedIntParameter();
			
			setArmorRating(rating);
			
		}
		break;
	case RPC_SETKINETIC__FLOAT_:
		{
			float resist = inv->getFloatParameter();
			
			setKinetic(resist);
			
		}
		break;
	case RPC_SETENERGY__FLOAT_:
		{
			float resist = inv->getFloatParameter();
			
			setEnergy(resist);
			
		}
		break;
	case RPC_SETELECTRICITY__FLOAT_:
		{
			float resist = inv->getFloatParameter();
			
			setElectricity(resist);
			
		}
		break;
	case RPC_SETSTUN__FLOAT_:
		{
			float resist = inv->getFloatParameter();
			
			setStun(resist);
			
		}
		break;
	case RPC_SETBLAST__FLOAT_:
		{
			float resist = inv->getFloatParameter();
			
			setBlast(resist);
			
		}
		break;
	case RPC_SETHEAT__FLOAT_:
		{
			float resist = inv->getFloatParameter();
			
			setHeat(resist);
			
		}
		break;
	case RPC_SETCOLD__FLOAT_:
		{
			float resist = inv->getFloatParameter();
			
			setCold(resist);
			
		}
		break;
	case RPC_SETACID__FLOAT_:
		{
			float resist = inv->getFloatParameter();
			
			setAcid(resist);
			
		}
		break;
	case RPC_SETLIGHTSABER__FLOAT_:
		{
			float resist = inv->getFloatParameter();
			
			setLightSaber(resist);
			
		}
		break;
	case RPC_SETCHANCEHIT__FLOAT_:
		{
			float chance = inv->getFloatParameter();
			
			setChanceHit(chance);
			
		}
		break;
	case RPC_GETTURRETWEAPON__:
		{
			
			DistributedObject* _m_res = getTurretWeapon();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_GETARMORRATING__:
		{
			
			unsigned int _m_res = getArmorRating();
			resp->insertInt(_m_res);
		}
		break;
	case RPC_GETCHANCEHIT__:
		{
			
			float _m_res = getChanceHit();
			resp->insertFloat(_m_res);
		}
		break;
	default:
		InstallationObjectAdapter::invokeMethod(methid, inv);
	}
}

void TurretObjectAdapter::initializeTransientMembers() {
	(static_cast<TurretObject*>(stub))->initializeTransientMembers();
}

void TurretObjectAdapter::createChildObjects() {
	(static_cast<TurretObject*>(stub))->createChildObjects();
}

float TurretObjectAdapter::getArmorResistReduction(float value) {
	return (static_cast<TurretObject*>(stub))->getArmorResistReduction(value);
}

float TurretObjectAdapter::getKinetic() {
	return (static_cast<TurretObject*>(stub))->getKinetic();
}

float TurretObjectAdapter::getEnergy() {
	return (static_cast<TurretObject*>(stub))->getEnergy();
}

float TurretObjectAdapter::getElectricity() {
	return (static_cast<TurretObject*>(stub))->getElectricity();
}

float TurretObjectAdapter::getStun() {
	return (static_cast<TurretObject*>(stub))->getStun();
}

float TurretObjectAdapter::getBlast() {
	return (static_cast<TurretObject*>(stub))->getBlast();
}

float TurretObjectAdapter::getHeat() {
	return (static_cast<TurretObject*>(stub))->getHeat();
}

float TurretObjectAdapter::getCold() {
	return (static_cast<TurretObject*>(stub))->getCold();
}

float TurretObjectAdapter::getAcid() {
	return (static_cast<TurretObject*>(stub))->getAcid();
}

float TurretObjectAdapter::getLightSaber() {
	return (static_cast<TurretObject*>(stub))->getLightSaber();
}

void TurretObjectAdapter::setTurretWeapon(WeaponObject* turretWeapon) {
	(static_cast<TurretObject*>(stub))->setTurretWeapon(turretWeapon);
}

void TurretObjectAdapter::setArmorRating(unsigned int rating) {
	(static_cast<TurretObject*>(stub))->setArmorRating(rating);
}

void TurretObjectAdapter::setKinetic(float resist) {
	(static_cast<TurretObject*>(stub))->setKinetic(resist);
}

void TurretObjectAdapter::setEnergy(float resist) {
	(static_cast<TurretObject*>(stub))->setEnergy(resist);
}

void TurretObjectAdapter::setElectricity(float resist) {
	(static_cast<TurretObject*>(stub))->setElectricity(resist);
}

void TurretObjectAdapter::setStun(float resist) {
	(static_cast<TurretObject*>(stub))->setStun(resist);
}

void TurretObjectAdapter::setBlast(float resist) {
	(static_cast<TurretObject*>(stub))->setBlast(resist);
}

void TurretObjectAdapter::setHeat(float resist) {
	(static_cast<TurretObject*>(stub))->setHeat(resist);
}

void TurretObjectAdapter::setCold(float resist) {
	(static_cast<TurretObject*>(stub))->setCold(resist);
}

void TurretObjectAdapter::setAcid(float resist) {
	(static_cast<TurretObject*>(stub))->setAcid(resist);
}

void TurretObjectAdapter::setLightSaber(float resist) {
	(static_cast<TurretObject*>(stub))->setLightSaber(resist);
}

void TurretObjectAdapter::setChanceHit(float chance) {
	(static_cast<TurretObject*>(stub))->setChanceHit(chance);
}

WeaponObject* TurretObjectAdapter::getTurretWeapon() {
	return (static_cast<TurretObject*>(stub))->getTurretWeapon();
}

unsigned int TurretObjectAdapter::getArmorRating() {
	return (static_cast<TurretObject*>(stub))->getArmorRating();
}

float TurretObjectAdapter::getChanceHit() {
	return (static_cast<TurretObject*>(stub))->getChanceHit();
}

/*
 *	TurretObjectHelper
 */

TurretObjectHelper* TurretObjectHelper::staticInitializer = TurretObjectHelper::instance();

TurretObjectHelper::TurretObjectHelper() {
	className = "TurretObject";

	Core::getObjectBroker()->registerClass(className, this);
}

void TurretObjectHelper::finalizeHelper() {
	TurretObjectHelper::finalize();
}

DistributedObject* TurretObjectHelper::instantiateObject() {
	return new TurretObject(DummyConstructorParameter::instance());
}

DistributedObjectServant* TurretObjectHelper::instantiateServant() {
	return new TurretObjectImplementation();
}

DistributedObjectPOD* TurretObjectHelper::instantiatePOD() {
	return new TurretObjectPOD();
}

DistributedObjectAdapter* TurretObjectHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new TurretObjectAdapter(static_cast<TurretObject*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	TurretObjectPOD
 */

TurretObjectPOD::~TurretObjectPOD() {
	finalize();
}

TurretObjectPOD::TurretObjectPOD(void) {
	_className = "TurretObject";
}


void TurretObjectPOD::writeJSON(nlohmann::json& j) {
	InstallationObjectPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (armorRating)
		thisObject["armorRating"] = armorRating.value();

	if (kinetic)
		thisObject["kinetic"] = kinetic.value();

	if (energy)
		thisObject["energy"] = energy.value();

	if (electricity)
		thisObject["electricity"] = electricity.value();

	if (stun)
		thisObject["stun"] = stun.value();

	if (blast)
		thisObject["blast"] = blast.value();

	if (heat)
		thisObject["heat"] = heat.value();

	if (cold)
		thisObject["cold"] = cold.value();

	if (acid)
		thisObject["acid"] = acid.value();

	if (lightsaber)
		thisObject["lightsaber"] = lightsaber.value();

	if (chanceHit)
		thisObject["chanceHit"] = chanceHit.value();

	j["TurretObject"] = thisObject;
}


void TurretObjectPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = TurretObjectPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int TurretObjectPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = InstallationObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (armorRating) {
	_nameHashCode = 0x13b63a0e; //TurretObject.armorRating
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<unsigned int >::toBinaryStream(&armorRating.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (kinetic) {
	_nameHashCode = 0xa4a57959; //TurretObject.kinetic
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&kinetic.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (energy) {
	_nameHashCode = 0x5123eb81; //TurretObject.energy
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&energy.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (electricity) {
	_nameHashCode = 0xd117c7ae; //TurretObject.electricity
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&electricity.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (stun) {
	_nameHashCode = 0x162201b3; //TurretObject.stun
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&stun.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (blast) {
	_nameHashCode = 0xe53c90c2; //TurretObject.blast
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&blast.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (heat) {
	_nameHashCode = 0x5217d59f; //TurretObject.heat
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&heat.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (cold) {
	_nameHashCode = 0x979aba9a; //TurretObject.cold
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&cold.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (acid) {
	_nameHashCode = 0xb51aa412; //TurretObject.acid
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&acid.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (lightsaber) {
	_nameHashCode = 0x8fe072cd; //TurretObject.lightsaber
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&lightsaber.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (chanceHit) {
	_nameHashCode = 0x3de4f7f8; //TurretObject.chanceHit
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&chanceHit.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool TurretObjectPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (InstallationObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x13b63a0e: //TurretObject.armorRating
		{
			unsigned int _mnarmorRating;
			TypeInfo<unsigned int >::parseFromBinaryStream(&_mnarmorRating, stream);
			armorRating = std::move(_mnarmorRating);
		}
		return true;

	case 0xa4a57959: //TurretObject.kinetic
		{
			float _mnkinetic;
			TypeInfo<float >::parseFromBinaryStream(&_mnkinetic, stream);
			kinetic = std::move(_mnkinetic);
		}
		return true;

	case 0x5123eb81: //TurretObject.energy
		{
			float _mnenergy;
			TypeInfo<float >::parseFromBinaryStream(&_mnenergy, stream);
			energy = std::move(_mnenergy);
		}
		return true;

	case 0xd117c7ae: //TurretObject.electricity
		{
			float _mnelectricity;
			TypeInfo<float >::parseFromBinaryStream(&_mnelectricity, stream);
			electricity = std::move(_mnelectricity);
		}
		return true;

	case 0x162201b3: //TurretObject.stun
		{
			float _mnstun;
			TypeInfo<float >::parseFromBinaryStream(&_mnstun, stream);
			stun = std::move(_mnstun);
		}
		return true;

	case 0xe53c90c2: //TurretObject.blast
		{
			float _mnblast;
			TypeInfo<float >::parseFromBinaryStream(&_mnblast, stream);
			blast = std::move(_mnblast);
		}
		return true;

	case 0x5217d59f: //TurretObject.heat
		{
			float _mnheat;
			TypeInfo<float >::parseFromBinaryStream(&_mnheat, stream);
			heat = std::move(_mnheat);
		}
		return true;

	case 0x979aba9a: //TurretObject.cold
		{
			float _mncold;
			TypeInfo<float >::parseFromBinaryStream(&_mncold, stream);
			cold = std::move(_mncold);
		}
		return true;

	case 0xb51aa412: //TurretObject.acid
		{
			float _mnacid;
			TypeInfo<float >::parseFromBinaryStream(&_mnacid, stream);
			acid = std::move(_mnacid);
		}
		return true;

	case 0x8fe072cd: //TurretObject.lightsaber
		{
			float _mnlightsaber;
			TypeInfo<float >::parseFromBinaryStream(&_mnlightsaber, stream);
			lightsaber = std::move(_mnlightsaber);
		}
		return true;

	case 0x3de4f7f8: //TurretObject.chanceHit
		{
			float _mnchanceHit;
			TypeInfo<float >::parseFromBinaryStream(&_mnchanceHit, stream);
			chanceHit = std::move(_mnchanceHit);
		}
		return true;

	}

	return false;
}

void TurretObjectPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(TurretObjectPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void TurretObjectPOD::writeObjectCompact(ObjectOutputStream* stream) {
	InstallationObjectPOD::writeObjectCompact(stream);

	TypeInfo<unsigned int >::toBinaryStream(&armorRating.value(), stream);

	TypeInfo<float >::toBinaryStream(&kinetic.value(), stream);

	TypeInfo<float >::toBinaryStream(&energy.value(), stream);

	TypeInfo<float >::toBinaryStream(&electricity.value(), stream);

	TypeInfo<float >::toBinaryStream(&stun.value(), stream);

	TypeInfo<float >::toBinaryStream(&blast.value(), stream);

	TypeInfo<float >::toBinaryStream(&heat.value(), stream);

	TypeInfo<float >::toBinaryStream(&cold.value(), stream);

	TypeInfo<float >::toBinaryStream(&acid.value(), stream);

	TypeInfo<float >::toBinaryStream(&lightsaber.value(), stream);

	TypeInfo<float >::toBinaryStream(&chanceHit.value(), stream);


}

