/*
 *	autogen/server/zone/objects/tangible/deed/ship/ShipDeed.h generated by engine3 IDL compiler 0.70
 */

#ifndef SHIPDEED_H_
#define SHIPDEED_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace packets {
namespace scene {

class AttributeListMessage;

} // namespace scene
} // namespace packets
} // namespace zone
} // namespace server

using namespace server::zone::packets::scene;

namespace server {
namespace zone {
namespace packets {
namespace object {

class ObjectMenuResponse;

} // namespace object
} // namespace packets
} // namespace zone
} // namespace server

using namespace server::zone::packets::object;

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

#include "engine/lua/Luna.h"

#include "templates/SharedObjectTemplate.h"

#include "server/zone/objects/manufactureschematic/craftingvalues/CraftingValues.h"

#include "server/zone/objects/tangible/deed/Deed.h"

#include "system/util/Vector.h"

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace deed {

class ShipDeed : public Deed {
public:
	ShipDeed();

	void initializeTransientMembers();

	/**
	 * Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
	 * @pre { templateData is a valid pointer }
	 * @post { TangibleObject members are initialized }
	 * @param templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
	 */
	void loadTemplateData(SharedObjectTemplate* templateData);

	void fillAttributeList(AttributeListMessage* alm, CreatureObject* object);

	void fillObjectMenuResponse(ObjectMenuResponse* menuResponse, CreatureObject* player);

	int handleObjectMenuSelect(CreatureObject* player, byte selectedID);

	void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void setControlDeviceTemplate(String& templateString);

	void setHitPointsDamage(float value);

	void setMaxHitPoints(float value);

	void setMass(float value);

	void setCertificationRequired(String& cert);

	void setParkingLocation(String& loc);

	void setShipType(int type);

	void setCreateComponents(bool val);

	void addSkillRequired(String& skill);

	String getControlDeviceTemplate() const;

	float getHitPointsDamage() const;

	float getMaxHitPoints() const;

	float getMass() const;

	String getParkingLocation() const;

	String getCertificationRequired() const;

	int getTotalSkillsRequired();

	String getSkillRequired(int index);

	bool shouldCreateComponents();

	int getShipType() const;

	bool isShipDeedObject();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ShipDeed(DummyConstructorParameter* param);

	virtual ~ShipDeed();

	friend class ShipDeedHelper;
};

} // namespace deed
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::deed;

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace deed {

class ShipDeedImplementation : public DeedImplementation {
protected:
	String controlDeviceTemplate;

	float hitPointsDamage;

	float maxHitPoints;

	float mass;

	String certRequired;

	String parkingLocation;

private:
	Vector<String> skillsRequired;

protected:
	int shipType;

	bool createComponents;

public:
	ShipDeedImplementation();

	ShipDeedImplementation(DummyConstructorParameter* param);

	void initializeTransientMembers();

	/**
	 * Reads and sets the template data from a SharedTangibleObjectTemplate LuaObject
	 * @pre { templateData is a valid pointer }
	 * @post { TangibleObject members are initialized }
	 * @param templateData templateData points to the SharedTangibleObjectTemplate LuaObject that is used to initialize the TangibleObject members
	 */
	void loadTemplateData(SharedObjectTemplate* templateData);

	void fillAttributeList(AttributeListMessage* alm, CreatureObject* object);

	virtual void fillObjectMenuResponse(ObjectMenuResponse* menuResponse, CreatureObject* player);

	virtual int handleObjectMenuSelect(CreatureObject* player, byte selectedID);

	void updateCraftingValues(CraftingValues* values, bool firstUpdate);

	void setControlDeviceTemplate(String& templateString);

	void setHitPointsDamage(float value);

	void setMaxHitPoints(float value);

	void setMass(float value);

	void setCertificationRequired(String& cert);

	void setParkingLocation(String& loc);

	void setShipType(int type);

	void setCreateComponents(bool val);

	void addSkillRequired(String& skill);

	String getControlDeviceTemplate() const;

	float getHitPointsDamage() const;

	float getMaxHitPoints() const;

	float getMass() const;

	String getParkingLocation() const;

	String getCertificationRequired() const;

	int getTotalSkillsRequired();

	String getSkillRequired(int index);

	bool shouldCreateComponents();

	int getShipType() const;

	bool isShipDeedObject();

	WeakReference<ShipDeed*> _this;

	operator const ShipDeed*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	virtual void writeJSON(nlohmann::json& j);
protected:
	virtual ~ShipDeedImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ShipDeed;
};

class ShipDeedAdapter : public DeedAdapter {
public:
	ShipDeedAdapter(ShipDeed* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void initializeTransientMembers();

	void setControlDeviceTemplate(String& templateString);

	void setHitPointsDamage(float value);

	void setMaxHitPoints(float value);

	void setMass(float value);

	void setCertificationRequired(String& cert);

	void setParkingLocation(String& loc);

	void setCreateComponents(bool val);

	void addSkillRequired(String& skill);

	String getControlDeviceTemplate() const;

	float getHitPointsDamage() const;

	float getMaxHitPoints() const;

	float getMass() const;

	String getParkingLocation() const;

	String getCertificationRequired() const;

	int getTotalSkillsRequired();

	String getSkillRequired(int index);

	bool shouldCreateComponents();

	int getShipType() const;

	bool isShipDeedObject();

};

class ShipDeedHelper : public DistributedObjectClassHelper, public Singleton<ShipDeedHelper> {
	static ShipDeedHelper* staticInitializer;

public:
	ShipDeedHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ShipDeedHelper>;
};

class LuaShipDeed : public LuaDeed {
public:
	static const char className[];
	static Luna<LuaShipDeed>::RegType Register[];

	LuaShipDeed(lua_State *L);
	virtual ~LuaShipDeed();

	int _setObject(lua_State *L);
	int _getObject(lua_State *L);
	int initializeTransientMembers(lua_State *L);
	int loadTemplateData(lua_State *L);
	int fillAttributeList(lua_State *L);
	int fillObjectMenuResponse(lua_State *L);
	int handleObjectMenuSelect(lua_State *L);
	int updateCraftingValues(lua_State *L);
	int setControlDeviceTemplate(lua_State *L);
	int setHitPointsDamage(lua_State *L);
	int setMaxHitPoints(lua_State *L);
	int setMass(lua_State *L);
	int setCertificationRequired(lua_State *L);
	int setParkingLocation(lua_State *L);
	int setShipType(lua_State *L);
	int setCreateComponents(lua_State *L);
	int addSkillRequired(lua_State *L);
	int getControlDeviceTemplate(lua_State *L);
	int getHitPointsDamage(lua_State *L);
	int getMaxHitPoints(lua_State *L);
	int getMass(lua_State *L);
	int getParkingLocation(lua_State *L);
	int getCertificationRequired(lua_State *L);
	int getTotalSkillsRequired(lua_State *L);
	int getSkillRequired(lua_State *L);
	int shouldCreateComponents(lua_State *L);
	int getShipType(lua_State *L);
	int isShipDeedObject(lua_State *L);

	Reference<ShipDeed*> realObject;
};

} // namespace deed
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::deed;

namespace server {
namespace zone {
namespace objects {
namespace tangible {
namespace deed {

class ShipDeedPOD : public DeedPOD {
public:
	Optional<String> controlDeviceTemplate;

	Optional<float> hitPointsDamage;

	Optional<float> maxHitPoints;

	Optional<float> mass;

	Optional<String> certRequired;

	Optional<String> parkingLocation;

	Optional<Vector<String>> skillsRequired;

	Optional<int> shipType;

	Optional<bool> createComponents;

	String _className;
	ShipDeedPOD();
	virtual void writeJSON(nlohmann::json& j);
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ShipDeedPOD();

};

} // namespace deed
} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible::deed;

#endif /*SHIPDEEDPOD_H_*/
